import { readError, toPersistedMemoryAuditDto, toPersistedMemoryDetailResponseDto, toPersistedMemoryItemDto, toPersistedMemoryListResponseDto, toPersistedMemoryPatchDto, toPersistedMemorySourceDto } from "@/lib/api/persisted-memory-read-dto";
import type { PersistedMemoryAuditDto, PersistedMemoryDetailRequest, PersistedMemoryDetailResult, PersistedMemoryItemDto, PersistedMemoryListRequest, PersistedMemoryListResult, PersistedMemoryPatchDto, PersistedMemoryReadContext, PersistedMemorySourceDto } from "@/lib/services/persisted-memory-read-contract";
import type { PersistedMemoryReadRepository } from "@/lib/db/persisted-memory-read-repository-contract";

type Row = Record<string, unknown>;
function clone<T>(v: T): T { return JSON.parse(JSON.stringify(v)) as T; }
function blocker(ctx: PersistedMemoryReadContext, req: PersistedMemoryListRequest | PersistedMemoryDetailRequest) { if (!ctx?.userId) return readError("auth_required", "Server-authenticated userId is required."); if (!ctx.namespace || !req.namespace) return readError("namespace_required", "Namespace is required."); if (ctx.namespace !== req.namespace) return readError("namespace_mismatch", "Requested namespace does not match authenticated context."); if ("userId" in req || "user_id" in req || "filter" in req && (req.filter?.userId || req.filter?.user_id)) return readError("client_user_id_rejected", "Client-supplied user_id/userId is rejected."); return null; }
function pageRows(rows: Row[], req: PersistedMemoryListRequest) { const page = Math.max(1, req.page ?? 1); const pageSize = Math.min(100, Math.max(1, req.pageSize ?? 25)); return { page, pageSize, rows: rows.slice((page - 1) * pageSize, page * pageSize) }; }
function filterRows(rows: Row[], ctx: PersistedMemoryReadContext, req: PersistedMemoryListRequest) { const f = req.filter ?? {}; return rows.filter((r) => r.user_id === ctx.userId && r.namespace === ctx.namespace).filter((r) => !f.itemId || r.id === f.itemId || r.memory_item_id === f.itemId).filter((r) => !f.sourceId || r.id === f.sourceId).filter((r) => !f.reviewItemId || (r.metadata as Row | undefined)?.review_item_id === f.reviewItemId).filter((r) => !f.decisionId || (r.metadata as Row | undefined)?.decision_id === f.decisionId).filter((r) => !f.memoryKind || r.memory_type === f.memoryKind).filter((r) => !f.category || (r.metadata as Row | undefined)?.category === f.category).filter((r) => !f.createdFrom || String(r.created_at) >= f.createdFrom!).filter((r) => !f.createdTo || String(r.created_at) <= f.createdTo!).filter((r) => !f.keyword || JSON.stringify(r).toLowerCase().includes(f.keyword.toLowerCase())); }
export class InMemoryPersistedMemoryReadRepository implements PersistedMemoryReadRepository {
  private items: Row[] = []; private sources: Row[] = []; private patches: Row[] = []; private audits: Row[] = [];
  seed(data: { items?: Row[]; sources?: Row[]; patches?: Row[]; auditEvents?: Row[] }) { this.items = clone(data.items ?? []); this.sources = clone(data.sources ?? []); this.patches = clone(data.patches ?? []); this.audits = clone(data.auditEvents ?? []); }
  async listMemoryItems(ctx: PersistedMemoryReadContext, req: PersistedMemoryListRequest): Promise<PersistedMemoryListResult<PersistedMemoryItemDto>> { const b = blocker(ctx, req); if (b) return b; const all = filterRows(this.items, ctx, req); const p = pageRows(all, req); return toPersistedMemoryListResponseDto(p.rows.map((r) => toPersistedMemoryItemDto(clone(r), ctx)), p.page, p.pageSize, all.length); }
  async getMemoryItemDetail(ctx: PersistedMemoryReadContext, req: PersistedMemoryDetailRequest): Promise<PersistedMemoryDetailResult<PersistedMemoryItemDto>> { const b = blocker(ctx, req); if (b) return b; const row = this.items.find((r) => r.id === req.id && r.user_id === ctx.userId && r.namespace === ctx.namespace); return row ? toPersistedMemoryDetailResponseDto(toPersistedMemoryItemDto(clone(row), ctx)) : readError("not_found", "Memory item not found."); }
  async listMemorySources(ctx: PersistedMemoryReadContext, req: PersistedMemoryListRequest): Promise<PersistedMemoryListResult<PersistedMemorySourceDto>> { const b = blocker(ctx, req); if (b) return b; const all = filterRows(this.sources, ctx, req); const p = pageRows(all, req); return toPersistedMemoryListResponseDto(p.rows.map((r) => toPersistedMemorySourceDto(clone(r))), p.page, p.pageSize, all.length); }
  async getMemorySourceDetail(ctx: PersistedMemoryReadContext, req: PersistedMemoryDetailRequest): Promise<PersistedMemoryDetailResult<PersistedMemorySourceDto>> { const b = blocker(ctx, req); if (b) return b; const row = this.sources.find((r) => r.id === req.id && r.user_id === ctx.userId && r.namespace === ctx.namespace); return row ? toPersistedMemoryDetailResponseDto(toPersistedMemorySourceDto(clone(row))) : readError("not_found", "Memory source not found."); }
  async listMemoryPatches(ctx: PersistedMemoryReadContext, req: PersistedMemoryListRequest): Promise<PersistedMemoryListResult<PersistedMemoryPatchDto>> { const b = blocker(ctx, req); if (b) return b; const all = filterRows(this.patches, ctx, req); const p = pageRows(all, req); return toPersistedMemoryListResponseDto(p.rows.map((r) => toPersistedMemoryPatchDto(clone(r))), p.page, p.pageSize, all.length); }
  async listMemoryAuditEvents(ctx: PersistedMemoryReadContext, req: PersistedMemoryListRequest): Promise<PersistedMemoryListResult<PersistedMemoryAuditDto>> { const b = blocker(ctx, req); if (b) return b; const all = filterRows(this.audits, ctx, req); const p = pageRows(all, req); return toPersistedMemoryListResponseDto(p.rows.map((r) => toPersistedMemoryAuditDto(clone(r))), p.page, p.pageSize, all.length); }
}
