import { readError, toPersistedMemoryAuditDto, toPersistedMemoryDetailResponseDto, toPersistedMemoryItemDto, toPersistedMemoryListResponseDto, toPersistedMemoryPatchDto, toPersistedMemorySourceDto } from "@/lib/api/persisted-memory-read-dto";
import type { PersistedMemoryDetailRequest, PersistedMemoryDetailResult, PersistedMemoryListRequest, PersistedMemoryListResult, PersistedMemoryReadContext } from "@/lib/services/persisted-memory-read-contract";
import type { PersistedMemoryReadRepository } from "@/lib/db/persisted-memory-read-repository-contract";

type Query = { select: (c?: string, o?: unknown) => Query; eq: (c: string, v: unknown) => Query; gte: (c: string, v: unknown) => Query; lte: (c: string, v: unknown) => Query; or: (f: string) => Query; range: (f: number, t: number) => Promise<{ data: Record<string, unknown>[] | null; error: { message: string } | null; count?: number | null }>; single: () => Promise<{ data: Record<string, unknown> | null; error: { message: string; code?: string } | null }> };
type Client = { from: (table: string) => Query };
function validate(ctx: PersistedMemoryReadContext, req: PersistedMemoryListRequest | PersistedMemoryDetailRequest) { if (!ctx?.userId) return readError("auth_required", "Server-authenticated userId is required."); if (!ctx.namespace || !req.namespace) return readError("namespace_required", "Namespace is required."); if (ctx.namespace !== req.namespace) return readError("namespace_mismatch", "Requested namespace does not match authenticated context."); if ("userId" in req || "user_id" in req || "filter" in req && (req.filter?.userId || req.filter?.user_id)) return readError("client_user_id_rejected", "Client-supplied user_id/userId is rejected."); return null; }
function page(req: PersistedMemoryListRequest) { const p = Math.max(1, req.page ?? 1); const s = Math.min(100, Math.max(1, req.pageSize ?? 25)); return { p, s, from: (p - 1) * s, to: p * s - 1 }; }
function apply(q: Query, ctx: PersistedMemoryReadContext, req: PersistedMemoryListRequest) { const f = req.filter ?? {}; q = q.eq("user_id", ctx.userId).eq("namespace", ctx.namespace); if (f.itemId) q = q.eq("memory_item_id", f.itemId); if (f.sourceId) q = q.eq("id", f.sourceId); if (f.createdFrom) q = q.gte("created_at", f.createdFrom); if (f.createdTo) q = q.lte("created_at", f.createdTo); if (f.memoryKind) q = q.eq("memory_type", f.memoryKind); if (f.keyword) q = q.or(`title.ilike.%${f.keyword}%,body.ilike.%${f.keyword}%,source_summary.ilike.%${f.keyword}%`); return q; }
export class SupabasePersistedMemoryReadRepository implements PersistedMemoryReadRepository {
  constructor(private readonly client: Client) {}
  private async list<T>(table: string, ctx: PersistedMemoryReadContext, req: PersistedMemoryListRequest, map: (r: Record<string, unknown>) => T): Promise<PersistedMemoryListResult<T>> { const b = validate(ctx, req); if (b) return b; const pg = page(req); const res = await apply(this.client.from(table).select("*", { count: "exact" }), ctx, req).range(pg.from, pg.to); if (res.error) return { ok: false, blocker: { code: "read_error", message: res.error.message } }; return toPersistedMemoryListResponseDto((res.data ?? []).map(map), pg.p, pg.s, res.count ?? undefined); }
  private async detail<T>(table: string, ctx: PersistedMemoryReadContext, req: PersistedMemoryDetailRequest, map: (r: Record<string, unknown>) => T): Promise<PersistedMemoryDetailResult<T>> { const b = validate(ctx, req); if (b) return b; let q = this.client.from(table).select("*").eq("id", req.id).eq("user_id", ctx.userId).eq("namespace", ctx.namespace); if (req.itemId) q = q.eq("memory_item_id", req.itemId); const res = await q.single(); if (res.error || !res.data) return readError(res.error?.code === "PGRST116" ? "not_found" : "read_error", res.error?.message ?? "Record not found."); return toPersistedMemoryDetailResponseDto(map(res.data)); }
  listMemoryItems(c: PersistedMemoryReadContext, r: PersistedMemoryListRequest) { return this.list("memory_items", c, r, (x) => toPersistedMemoryItemDto(x, c)); }
  getMemoryItemDetail(c: PersistedMemoryReadContext, r: PersistedMemoryDetailRequest) { return this.detail("memory_items", c, r, (x) => toPersistedMemoryItemDto(x, c)); }
  listMemorySources(c: PersistedMemoryReadContext, r: PersistedMemoryListRequest) { return this.list("memory_sources", c, r, toPersistedMemorySourceDto); }
  getMemorySourceDetail(c: PersistedMemoryReadContext, r: PersistedMemoryDetailRequest) { return this.detail("memory_sources", c, r, toPersistedMemorySourceDto); }
  listMemoryPatches(c: PersistedMemoryReadContext, r: PersistedMemoryListRequest) { return this.list("memory_patches", c, r, toPersistedMemoryPatchDto); }
  listMemoryAuditEvents(c: PersistedMemoryReadContext, r: PersistedMemoryListRequest) { return this.list("audit_logs", c, r, toPersistedMemoryAuditDto); }
}
