import { NextResponse, type NextRequest } from "next/server";
import { createRepositoryContext, type RepositoryContext } from "@/lib/db/repository-context";
import type { MemoryReviewQueueRepository } from "@/lib/db/memory-review-queue-repository-contract";
import type { ApprovedReviewMemoryPersistenceRepository } from "@/lib/db/approved-review-memory-persistence-repository-contract";
import { previewApprovedReviewMemoryPersistence } from "@/lib/services/approved-review-memory-persistence-preview";
import { executeApprovedReviewMemoryPersistence } from "@/lib/services/approved-review-memory-persistence-executor";
import { resolveAdminPersistencePermission } from "@/lib/security/admin-persistence-permissions";
import { blockedResult, toGateSafeDto, toPreviewSafeDto, toReviewItemSafeDto, toExecutionResultSafeDto } from "@/lib/api/admin-persistence-console-dto";
import type { MemoryNamespace } from "@/lib/services/memory-extraction-contract";

export type AdminPersistenceExecutionRouteDependencies = { resolveAuth?: (request: NextRequest) => Promise<Pick<RepositoryContext, "userId"> | null>; reviewQueueRepository?: MemoryReviewQueueRepository; previewService?: typeof previewApprovedReviewMemoryPersistence; executorService?: typeof executeApprovedReviewMemoryPersistence; persistenceRepository?: ApprovedReviewMemoryPersistenceRepository; env?: () => NodeJS.ProcessEnv; permissionResolver?: typeof resolveAdminPersistencePermission; enabled?: boolean };
type Params = { params: Promise<{ id?: string }> };
function bodyHasUserId(url: URL, body: Record<string, unknown>) { return url.searchParams.has("user_id") || url.searchParams.has("userId") || body.user_id || body.userId || body.client_user_id || body.clientUserId; }
async function parse(request: NextRequest) { return await request.json().catch(() => ({})) as Record<string, unknown>; }
function ns(body: Record<string, unknown>, url: URL): MemoryNamespace | null { const raw = body.namespace ?? url.searchParams.get("namespace"); return raw === "real_life" || raw === "au" ? raw : null; }
async function ctx(request: NextRequest, deps: AdminPersistenceExecutionRouteDependencies, namespace: MemoryNamespace) { const auth = await deps.resolveAuth?.(request); return createRepositoryContext({ userId: auth?.userId ?? null, namespace, requestId: request.headers.get("x-request-id") ?? undefined }); }
function envVars(deps: AdminPersistenceExecutionRouteDependencies) { const e = deps.env?.() ?? process.env; return { PANDORA_ENABLE_APPROVED_REVIEW_MEMORY_PERSISTENCE: e.PANDORA_ENABLE_APPROVED_REVIEW_MEMORY_PERSISTENCE, PANDORA_ENABLE_ADMIN_PERSISTENCE_CONSOLE: e.PANDORA_ENABLE_ADMIN_PERSISTENCE_CONSOLE }; }
function disabled(status=501) { return NextResponse.json(blockedResult("Admin persistence console is disabled. Approved-review persistence execution is internal-gated. Public production persistence is not enabled.", ["admin_console_disabled"]), { status }); }
export function createAdminPersistenceExecutionRouteHandler(deps: AdminPersistenceExecutionRouteDependencies = {}) {
  async function common(request: NextRequest, params: Params) {
    const body = await parse(request); const url = new URL(request.url); if (bodyHasUserId(url, body)) return { early: NextResponse.json(blockedResult("Client user_id/userId is not accepted.", ["client_user_id_override_attempt"]), { status: 400 }) };
    if (!deps.enabled || !deps.resolveAuth || !deps.reviewQueueRepository) return { early: disabled() };
    const namespace = ns(body, url); if (!namespace) return { early: NextResponse.json(blockedResult("Namespace must be explicit.", ["missing_namespace"]), { status: 400 }) }; const context = await ctx(request, deps, namespace); if (!context.ok) return { early: NextResponse.json(blockedResult(context.error.message, [context.error.code]), { status: 401 }) };
    const gate = (deps.permissionResolver ?? resolveAdminPersistencePermission)({ context: context.data, namespace, env: envVars(deps), headers: request.headers, routeContext: "admin" });
    if (!gate.allowed) return { early: NextResponse.json({ ...blockedResult("Admin persistence console is disabled.", gate.blockers), gate: toGateSafeDto(gate) }, { status: 403 }) };
    return { body, context: context.data, id: (await params.params).id };
  }
  return {
    list: async (request: NextRequest, params: Params) => { const c = await common(request, params); if (c.early) return c.early; const items = await deps.reviewQueueRepository!.listReviewQueueItems(c.context!, { status: "approved_for_append" }); return NextResponse.json({ ok: items.ok, items: items.ok ? items.data.map(toReviewItemSafeDto) : [], blockers: items.ok ? [] : [items.error.code] }); },
    read: async (request: NextRequest, params: Params) => { const c = await common(request, params); if (c.early) return c.early; const item = await deps.reviewQueueRepository!.readReviewQueueItemById(c.context!, c.id!); return item.ok ? NextResponse.json({ ok: true, item: toReviewItemSafeDto(item.data) }) : NextResponse.json(blockedResult(item.error.message, [item.error.code]), { status: 404 }); },
    preview: async (request: NextRequest, params: Params) => { const c = await common(request, params); if (c.early) return c.early; const item = await deps.reviewQueueRepository!.readReviewQueueItemById(c.context!, c.id!); if (!item.ok) return NextResponse.json(blockedResult(item.error.message, [item.error.code]), { status: 404 }); if (item.data.status !== "approved_for_append") return NextResponse.json(blockedResult("Review item is not approved_for_append.", ["not_approved_for_append"]), { status: 403 }); const preview = (deps.previewService ?? previewApprovedReviewMemoryPersistence)({ context: c.context!, items: [item.data] }); return NextResponse.json({ ok: preview.ok, preview: toPreviewSafeDto(preview) }); },
    execute: async (request: NextRequest, params: Params) => { const c = await common(request, params); if (c.early) return c.early; if (!deps.persistenceRepository) return disabled(501); if (!c.body!.idempotencyKey) return NextResponse.json(blockedResult("Execution requires preview and idempotency key.", ["missing_idempotency_key"]), { status: 400 }); const item = await deps.reviewQueueRepository!.readReviewQueueItemById(c.context!, c.id!); if (!item.ok || item.data.status !== "approved_for_append") return NextResponse.json(blockedResult("Review item is not approved_for_append.", ["not_approved_for_append"]), { status: 403 }); const preview = (deps.previewService ?? previewApprovedReviewMemoryPersistence)({ context: c.context!, items: [item.data] }); if (!preview.ok) return NextResponse.json(blockedResult("Preview is required before execution.", preview.blockers), { status: 403 }); const result = await (deps.executorService ?? executeApprovedReviewMemoryPersistence)({ context: c.context!, item: item.data, preview, repository: deps.persistenceRepository, env: envVars(deps), headers: request.headers, routeContext: "internal" }); return NextResponse.json({ ok: result.executed, result: toExecutionResultSafeDto(result) }, { status: result.executed ? 200 : 403 }); },
  };
}
