import { NextResponse, type NextRequest } from "next/server";
import { resolvePandoraRuntimeSafetyConfig } from "@/lib/config/pandora-runtime-safety-config";
import { assertNoClientUserIdOverride } from "@/lib/auth/pandora-server-session-resolver";
import { runLiveOneReviewedItemWorkflow } from "@/lib/services/live-one-reviewed-item-workflow-runner";
import { toLiveOneReviewedItemWorkflowSafeDto } from "@/lib/api/live-one-reviewed-item-workflow-dto";
import type { PandoraServerSessionResult } from "@/lib/auth/pandora-server-session-contract";
export type LiveOneReviewedItemWorkflowRouteDependencies = { enabled?: boolean; env?: () => NodeJS.ProcessEnv; resolveSession?: (request: NextRequest) => Promise<PandoraServerSessionResult>; workflowRunner?: typeof runLiveOneReviewedItemWorkflow; reviewRepository?: unknown; previewService?: unknown; approvedReviewPersistenceExecutor?: unknown; persistedMemoryReadRepository?: unknown; browserLoader?: unknown; auditVerifier?: unknown };
const disabled = { ok: false, executed: false, internalOnly: true, oneItemOnly: true, publicPersistenceEnabled: false, productionIngestEnabled: false, publicReadEnabled: false, message: "Live one-item memory workflow is disabled by default and requires internal operator wiring.", blockers: ["live_one_item_workflow_disabled", "internal_admin_gate_required"] };
export function createLiveOneReviewedItemWorkflowRouteHandler(deps: LiveOneReviewedItemWorkflowRouteDependencies = {}) { return {
  GET() { const runtime = resolvePandoraRuntimeSafetyConfig(deps.env?.() ?? process.env); return NextResponse.json({ ...disabled, instructions: ["Internal operator workflow", "One approved review item only", "Public persistence is disabled", "Production ingest writes are disabled", "Execution requires typed confirmation: APPEND MEMORY", "No model calls, embeddings, or semantic retrieval", "Audit verification is required"], gates: runtime.gates }, { status: 200 }); },
  async POST(request: NextRequest) { const body = await request.json().catch(() => ({})); const rejected = await assertNoClientUserIdOverride(request, body); if (rejected) return NextResponse.json({ ...disabled, blockers: ["client_user_id_rejected"] }, { status: 400 });
    const runtime = resolvePandoraRuntimeSafetyConfig(deps.env?.() ?? process.env); if (!deps.enabled) return NextResponse.json({ ...disabled, gates: runtime.gates }, { status: 501 });
    const blockers: string[] = []; const session = await deps.resolveSession?.(request); const caps = session?.ok ? session.session : null;
    if (!caps?.authenticated) blockers.push("missing_authenticated_server_user"); if (!caps?.isInternalOperator && !caps?.isPersistenceOperator && !caps?.adminCapabilities.includes("memory:manual-workflow")) blockers.push("operator_capability_required");
    if (!body.namespace) blockers.push("missing_namespace"); if (!body.reviewItemId) blockers.push("missing_review_item_id"); if (!body.decisionId) blockers.push("missing_decision_id"); if (!body.idempotencyKey) blockers.push("missing_idempotency_key"); if (body.typedConfirmation !== "APPEND MEMORY") blockers.push("typed_confirmation_mismatch");
    if (request.headers.get("x-pandora-internal-persistence-mode") !== "approved-review-executor") blockers.push("missing_internal_header");
    if (!runtime.config.approvedReviewPersistenceEnabled) blockers.push("approved_review_persistence_gate_disabled"); if (!runtime.config.adminPersistenceConsoleEnabled) blockers.push("admin_persistence_gate_disabled"); if (runtime.config.publicMemoryPersistenceEnabled || runtime.config.ingestProductionWriteEnabled || runtime.config.publicMemoryReadEnabled) blockers.push("unsafe_public_or_ingest_gate_enabled");
    if (blockers.length) return NextResponse.json({ ...disabled, blockers, gates: runtime.gates }, { status: 403 });
    if (!deps.workflowRunner || !deps.reviewRepository || !deps.previewService || !deps.approvedReviewPersistenceExecutor || !deps.persistedMemoryReadRepository || !deps.browserLoader || !deps.auditVerifier) return NextResponse.json({ ...disabled, blockers: ["missing_internal_dependencies"] }, { status: 501 });
    const result = await deps.workflowRunner({ context: { userId: caps!.userId, namespace: body.namespace }, sessionResult: session, runtime, namespace: body.namespace, allowedNamespaces: caps!.allowedNamespaces as never, reviewItemId: body.reviewItemId, decisionId: body.decisionId, idempotencyKey: body.idempotencyKey, typedConfirmation: body.typedConfirmation, internalHeaderMode: request.headers.get("x-pandora-internal-persistence-mode"), operatorCapability: true, reviewRepository: deps.reviewRepository as never, previewService: deps.previewService as never, approvedReviewPersistenceExecutor: deps.approvedReviewPersistenceExecutor as never, persistedMemoryReadRepository: deps.persistedMemoryReadRepository as never, browserLoader: deps.browserLoader as never, auditVerifier: deps.auditVerifier as never });
    return NextResponse.json(toLiveOneReviewedItemWorkflowSafeDto(result), { status: result.ok ? 200 : 403 });
  }
}; }
