import { NextResponse, type NextRequest } from "next/server";
import { resolvePandoraRuntimeSafetyConfig } from "@/lib/config/pandora-runtime-safety-config";
import { assertNoClientUserIdOverride } from "@/lib/auth/pandora-server-session-resolver";
import { runOperatorManualMemoryWorkflow } from "@/lib/services/operator-manual-memory-workflow-runner";
import { toOperatorManualMemoryWorkflowSafeDto } from "@/lib/api/operator-manual-memory-workflow-dto";
import type { PandoraServerSessionResult } from "@/lib/auth/pandora-server-session-contract";
export type OperatorManualMemoryWorkflowRouteDependencies = { enabled?: boolean; env?: () => NodeJS.ProcessEnv; resolveSession?: (request: NextRequest) => Promise<PandoraServerSessionResult>; workflowRunner?: typeof runOperatorManualMemoryWorkflow; readinessRunner?: unknown; liveDryRunRunner?: unknown; reviewRepository?: unknown; previewService?: unknown; approvedReviewPersistenceExecutor?: unknown; persistedMemoryReadRepository?: unknown; browserLoader?: unknown };
const disabled = { ok: false, executed: false, internalOnly: true, publicPersistenceEnabled: false, productionIngestEnabled: false, publicReadEnabled: false, message: "Manual memory workflow is disabled by default and requires internal operator wiring.", blockers: ["manual_workflow_disabled", "internal_admin_gate_required"] };
export function createOperatorManualMemoryWorkflowRouteHandler(deps: OperatorManualMemoryWorkflowRouteDependencies = {}) { return {
  GET() { const runtime = resolvePandoraRuntimeSafetyConfig(deps.env?.() ?? process.env); return NextResponse.json({ ...disabled, instructions: ["Internal operator workflow", "Public persistence is disabled", "Production ingest writes are disabled", "Execution requires typed confirmation: APPEND MEMORY"], gates: runtime.gates }, { status: 200 }); },
  async POST(request: NextRequest) { const body = await request.json().catch(() => ({})); const rejected = await assertNoClientUserIdOverride(request, body); if (rejected) return NextResponse.json({ ...disabled, blockers: ["client_user_id_rejected"] }, { status: 400 });
    const runtime = resolvePandoraRuntimeSafetyConfig(deps.env?.() ?? process.env); if (!deps.enabled) return NextResponse.json({ ...disabled, gates: runtime.gates }, { status: 501 });
    const session = await deps.resolveSession?.(request); const caps = session?.ok ? session.session : null; const blockers = [] as string[];
    if (!caps?.authenticated) blockers.push("missing_authenticated_server_user"); if (!caps?.isInternalOperator && !caps?.isPersistenceOperator && !caps?.adminCapabilities.includes("memory:manual-workflow")) blockers.push("operator_capability_required");
    if (!body.namespace) blockers.push("missing_namespace"); if (!body.reviewItemId) blockers.push("missing_review_item_id"); if (!body.decisionId) blockers.push("missing_decision_id"); if (!body.idempotencyKey) blockers.push("missing_idempotency_key"); if (!body.typedConfirmation) blockers.push("missing_typed_confirmation");
    if (!runtime.config.adminPersistenceConsoleEnabled || !runtime.config.approvedReviewPersistenceEnabled) blockers.push("internal_runtime_gates_disabled"); if (request.headers.get("x-pandora-internal-persistence-mode") !== "approved-review-executor") blockers.push("missing_internal_header");
    if (blockers.length) return NextResponse.json({ ...disabled, blockers, gates: runtime.gates }, { status: 403 });
    if (!deps.workflowRunner || !deps.reviewRepository || !deps.previewService || !deps.approvedReviewPersistenceExecutor || !deps.persistedMemoryReadRepository || !deps.browserLoader) return NextResponse.json(disabled, { status: 501 });
    const result = await deps.workflowRunner({ context: { userId: caps!.userId, namespace: body.namespace }, sessionResult: session, runtime, readinessResult: { ok: true }, liveDryRunResult: { ok: true }, namespace: body.namespace, allowedNamespaces: caps!.allowedNamespaces as never, reviewItemId: body.reviewItemId, decisionId: body.decisionId, idempotencyKey: body.idempotencyKey, typedConfirmation: body.typedConfirmation, internalExecutionGate: true, internalHeaderMode: request.headers.get("x-pandora-internal-persistence-mode"), adminCapability: true, reviewRepository: deps.reviewRepository as never, previewService: deps.previewService as never, approvedReviewPersistenceExecutor: deps.approvedReviewPersistenceExecutor as never, persistedMemoryReadRepository: deps.persistedMemoryReadRepository as never, browserLoader: deps.browserLoader as never });
    return NextResponse.json(toOperatorManualMemoryWorkflowSafeDto(result), { status: result.ok ? 200 : 403 });
  }
}; }
