import { persistedMemoryReadSafety, type PersistedMemoryAuditDto, type PersistedMemoryDetailResult, type PersistedMemoryItemDto, type PersistedMemoryListResult, type PersistedMemoryNamespace, type PersistedMemoryPatchDto, type PersistedMemoryReadContext, type PersistedMemorySourceDto } from "@/lib/services/persisted-memory-read-contract";

const PREVIEW = 240;
type AnyRow = Record<string, unknown>;
function text(v: unknown) { return typeof v === "string" ? v : undefined; }
function id(v: unknown) { return typeof v === "string" ? v : ""; }
function preview(v: unknown, max = PREVIEW) { const s = text(v); if (!s) return s ?? null; return s.length > max ? `${s.slice(0, max)}…` : s; }
function meta(row: AnyRow) { return row.metadata && typeof row.metadata === "object" && !Array.isArray(row.metadata) ? row.metadata as AnyRow : {}; }
function ref(row: AnyRow, key: string) { const m = meta(row); return text(row[key]) ?? text(m[key]); }

export function toPersistedMemoryItemDto(row: AnyRow, context: Pick<PersistedMemoryReadContext, "includeFullText"> = {}): PersistedMemoryItemDto {
  const body = text(row.body) ?? text(row.memory_text) ?? text(row.text) ?? "";
  return { ...persistedMemoryReadSafety, id: id(row.id), namespace: (row.namespace as PersistedMemoryNamespace), memoryType: text(row.memory_type), category: ref(row, "category") ?? null, title: text(row.title), textPreview: preview(body) ?? "", ...(context.includeFullText === true ? { fullText: body } : {}), strength: text(row.strength), confidence: typeof row.confidence === "number" ? row.confidence : undefined, canonStatus: text(row.canon_status), sourceSummary: preview(row.source_summary) ?? null, createdAt: text(row.created_at), updatedAt: text(row.updated_at), reviewItemId: ref(row, "review_item_id") ?? null, decisionId: ref(row, "decision_id") ?? null, auditSummary: null, sensitiveEvidenceRedacted: true, auStoryMemoryIsNotRealLifeEvidence: true };
}
export function toPersistedMemorySourceDto(row: AnyRow): PersistedMemorySourceDto { return { ...persistedMemoryReadSafety, id: id(row.id), namespace: (row.namespace as PersistedMemoryNamespace | null), itemId: text(row.memory_item_id) ?? null, sourceType: text(row.source_type) ?? null, sourceRef: preview(row.source_ref, 96), excerptPreview: preview(row.excerpt), confidence: typeof row.confidence === "number" ? row.confidence : null, createdAt: text(row.created_at), reviewItemId: ref(row, "review_item_id") ?? null, decisionId: ref(row, "decision_id") ?? null, sensitiveEvidenceRedacted: true }; }
export function toPersistedMemoryPatchDto(row: AnyRow): PersistedMemoryPatchDto { return { ...persistedMemoryReadSafety, id: id(row.id), namespace: (row.namespace as PersistedMemoryNamespace), itemId: id(row.memory_item_id), patchType: text(row.patch_type), reason: preview(row.reason), beforePreview: preview(JSON.stringify(row.before_snapshot ?? null)), afterPreview: preview(JSON.stringify(row.after_snapshot ?? null)), createdAt: text(row.created_at), sensitiveEvidenceRedacted: true }; }
export function toPersistedMemoryAuditDto(row: AnyRow): PersistedMemoryAuditDto { return { ...persistedMemoryReadSafety, id: id(row.id), namespace: (row.namespace as PersistedMemoryNamespace | null), action: text(row.action) ?? "unknown", tableName: text(row.table_name), recordId: text(row.record_id) ?? null, summary: preview(`${text(row.action) ?? "audit"} ${text(row.table_name) ?? "record"} ${text(row.record_id) ?? ""}`) ?? undefined, createdAt: text(row.created_at), sensitiveEvidenceRedacted: true }; }
export function toPersistedMemoryListResponseDto<T>(items: T[], page: number, pageSize: number, total?: number): PersistedMemoryListResult<T> { return { ok: true, ...persistedMemoryReadSafety, items, page, pageSize, total }; }
export function toPersistedMemoryDetailResponseDto<T>(item: T): PersistedMemoryDetailResult<T> { return { ok: true, ...persistedMemoryReadSafety, item }; }
export function readError(code: "auth_required" | "namespace_required" | "client_user_id_rejected" | "namespace_mismatch" | "not_found" | "read_error", message: string): { ok: false; blocker: { code: typeof code; message: string } } { return { ok: false, blocker: { code, message } }; }
