import type { PersistedMemoryAuditDto, PersistedMemoryItemDto, PersistedMemoryNamespace, PersistedMemoryPatchDto, PersistedMemoryReadBlocker, PersistedMemorySourceDto } from "@/lib/services/persisted-memory-read-contract";

const LIMIT = 140;
const redact = (value?: string | null, limit = LIMIT) => {
  if (!value) return "";
  return value.length > limit ? `${value.slice(0, limit)}… [redacted preview]` : value;
};
export type PersistedMemoryBrowserSafetyView = { readOnly: true; wouldWrite: false; wouldCallModel: false; wouldEmbed: false; semanticRetrievalEnabled: false; publicMemoryRead: false; sensitiveEvidenceRedacted: true; auStoryMemoryIsNotRealLifeEvidence: true };
export const browserSafety: PersistedMemoryBrowserSafetyView = { readOnly: true, wouldWrite: false, wouldCallModel: false, wouldEmbed: false, semanticRetrievalEnabled: false, publicMemoryRead: false, sensitiveEvidenceRedacted: true, auStoryMemoryIsNotRealLifeEvidence: true };
export type PersistedMemoryBrowserItemView = PersistedMemoryBrowserSafetyView & { id: string; namespace: PersistedMemoryNamespace; title?: string; memoryKind?: string; category?: string | null; textPreview: string; sourceId?: string | null; reviewItemId?: string | null; decisionId?: string | null; patchCount: number; auditCount: number; createdAt?: string; updatedAt?: string };
export type PersistedMemoryBrowserDetailView = PersistedMemoryBrowserItemView & { provenanceReferences: string[]; fullTextRedacted: true };
export type PersistedMemoryBrowserSourceView = PersistedMemoryBrowserSafetyView & { id: string; namespace: PersistedMemoryNamespace | null; itemId?: string | null; sourceType?: string | null; sourceRef?: string | null; excerptPreview: string; reviewItemId?: string | null; decisionId?: string | null; createdAt?: string };
export type PersistedMemoryBrowserPatchView = PersistedMemoryBrowserSafetyView & { id: string; namespace: PersistedMemoryNamespace; itemId: string; patchType?: string; reason?: string | null; beforePreview?: string | null; afterPreview?: string | null; createdAt?: string };
export type PersistedMemoryBrowserAuditView = PersistedMemoryBrowserSafetyView & { id: string; namespace: PersistedMemoryNamespace | null; action: string; tableName?: string; recordId?: string | null; summary?: string; createdAt?: string };
export type PersistedMemoryBrowserViewModel = PersistedMemoryBrowserSafetyView & { namespace?: PersistedMemoryNamespace; selectedItemId?: string; filters: { namespace?: string; keyword?: string; sourceId?: string; memoryKind?: string; createdFrom?: string; createdTo?: string }; items: PersistedMemoryBrowserItemView[]; detail?: PersistedMemoryBrowserDetailView | null; sources: PersistedMemoryBrowserSourceView[]; patches: PersistedMemoryBrowserPatchView[]; auditEvents: PersistedMemoryBrowserAuditView[]; blockers: PersistedMemoryReadBlocker[]; empty: boolean; errorMessage?: string; gateStatuses?: unknown };
export function toBrowserItemView(item: PersistedMemoryItemDto, counts: { patchCount?: number; auditCount?: number } = {}): PersistedMemoryBrowserItemView { return { ...browserSafety, id: item.id, namespace: item.namespace, title: item.title, memoryKind: item.memoryType, category: item.category, textPreview: redact(item.textPreview), sourceId: item.sources?.[0]?.id ?? null, reviewItemId: item.reviewItemId ?? null, decisionId: item.decisionId ?? null, patchCount: counts.patchCount ?? 0, auditCount: counts.auditCount ?? 0, createdAt: item.createdAt, updatedAt: item.updatedAt }; }
export function toBrowserDetailView(item: PersistedMemoryItemDto, sources: PersistedMemoryBrowserSourceView[], counts: { patchCount?: number; auditCount?: number } = {}): PersistedMemoryBrowserDetailView { return { ...toBrowserItemView(item, counts), provenanceReferences: sources.map((s) => s.sourceRef || s.id).filter(Boolean), fullTextRedacted: true }; }
export function toBrowserSourceView(source: PersistedMemorySourceDto): PersistedMemoryBrowserSourceView { return { ...browserSafety, id: source.id, namespace: source.namespace, itemId: source.itemId ?? null, sourceType: source.sourceType ?? null, sourceRef: redact(source.sourceRef, 96), excerptPreview: redact(source.excerptPreview), reviewItemId: source.reviewItemId ?? null, decisionId: source.decisionId ?? null, createdAt: source.createdAt }; }
export function toBrowserPatchView(patch: PersistedMemoryPatchDto): PersistedMemoryBrowserPatchView { return { ...browserSafety, id: patch.id, namespace: patch.namespace, itemId: patch.itemId, patchType: patch.patchType, reason: redact(patch.reason), beforePreview: redact(patch.beforePreview), afterPreview: redact(patch.afterPreview), createdAt: patch.createdAt }; }
export function toBrowserAuditView(audit: PersistedMemoryAuditDto): PersistedMemoryBrowserAuditView { return { ...browserSafety, id: audit.id, namespace: audit.namespace, action: audit.action, tableName: audit.tableName, recordId: audit.recordId ?? null, summary: redact(audit.summary), createdAt: audit.createdAt }; }
