import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/ui/page-header";
import { SectionCard } from "@/components/ui/section-card";
import { resolvePandoraRuntimeSafetyConfig } from "@/lib/config/pandora-runtime-safety-config";
import { resolvePandoraServerSession } from "@/lib/auth/pandora-server-session-resolver";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getMemoryProposal } from "@/lib/services/memory-proposal-service";
import { approveProposalAction, persistProposalAction, rejectProposalAction, reviseProposalAction } from "../actions";
export const dynamic="force-dynamic";
type Props={params:Promise<{id:string}>};
export default async function Page({params}:Props){const {id}=await params; const runtime=resolvePandoraRuntimeSafetyConfig(); const session=await resolvePandoraServerSession(); const supabase=await createSupabaseServerClient() as never; const result=await getMemoryProposal(supabase,id,session,runtime); const p=result.ok?result.data:null; const gate=runtime.config.approvedReviewPersistenceEnabled; return <AppShell><PageHeader eyebrow="Internal admin" title="Memory proposal detail" description="Proposal review is admin-only, namespace-scoped, POST/server-action based, audited, and gated. Public writes remain disabled."/><SectionCard title="Safety copy" description="This does not write active memory until approved."><p>Approval is audited.</p><p>Public writes remain disabled.</p><p>Model calls, embeddings, retrieval, GPT Actions, and MCP remain disabled.</p><p>Reviewed write gate enabled: {String(gate)}</p></SectionCard>{!p?<SectionCard title="Unavailable" description={result.ok?"No proposal found.":result.error}><p>No proposal rows are exposed.</p></SectionCard>:<><SectionCard title={p.title??p.id} description={`Status: ${p.status}`}><dl><dt>Proposal id</dt><dd>{p.id}</dd><dt>Namespace</dt><dd>{p.namespace}</dd><dt>Memory text</dt><dd>{p.memory_text}</dd><dt>Source</dt><dd>{p.source_type} {p.source_ref}</dd><dt>Proposed by</dt><dd>{p.proposed_by}</dd><dt>Reviewed by</dt><dd>{p.reviewed_by??"—"}</dd><dt>Reviewed at</dt><dd>{p.reviewed_at??"—"}</dd><dt>Persisted memory id</dt><dd>{p.persisted_memory_id??"—"}</dd></dl></SectionCard><SectionCard title="Review actions" description="All actions are blocked while the reviewed persistence gate is disabled."><form action={approveProposalAction}><input type="hidden" name="id" value={p.id}/><button disabled={!gate||p.status!=="pending"}>Approve</button></form><form action={rejectProposalAction}><input type="hidden" name="id" value={p.id}/><input name="reason" placeholder="Rejection reason"/><button disabled={!gate||p.status!=="pending"}>Reject</button></form><form action={reviseProposalAction}><input type="hidden" name="id" value={p.id}/><input name="note" placeholder="Revision note"/><button disabled={!gate||p.status!=="pending"}>Request revision</button></form><form action={persistProposalAction}><input type="hidden" name="id" value={p.id}/><button disabled={!gate||p.status!=="approved"}>Persist approved proposal</button></form></SectionCard><SectionCard title="Audit timeline" description="Audit events are stored in audit_logs for proposal_created, proposal_approved, proposal_rejected, proposal_needs_revision, and proposal_persisted."><p>Use /admin/memory/audit with namespace {p.namespace} to inspect append-only audit proof.</p></SectionCard></>}</AppShell>}
