import { firstReviewedMemoryFixtureSafetySummary, type FirstReviewedMemoryFixture, type FirstReviewedMemoryFixtureScenario } from "@/lib/services/first-reviewed-memory-fixture-contract";
import type { MemoryNamespace } from "@/lib/services/memory-extraction-contract";

const at = "2026-01-15T12:00:00.000Z";
const userId = "fixture-server-user-001";
const scenarios: FirstReviewedMemoryFixtureScenario[] = ["real_life_fact_append", "au_story_only_append", "blocked_au_to_real_life_contamination", "blocked_missing_audit", "blocked_non_append_decision"];
const text: Record<FirstReviewedMemoryFixtureScenario, string> = { real_life_fact_append: "User prefers quiet morning writing sessions.", au_story_only_append: "In the AU, Mara carries a silver compass.", blocked_au_to_real_life_contamination: "In the AU, Mara is allergic to starlight.", blocked_missing_audit: "User keeps travel notes in a blue notebook.", blocked_non_append_decision: "User likes green tea after lunch." };
const fp = (s: string) => `fixture-fingerprint-${s}`;
export function buildFirstReviewedMemoryFixture(input: { scenario: FirstReviewedMemoryFixtureScenario }): FirstReviewedMemoryFixture { const i = scenarios.indexOf(input.scenario) + 1; const ns: MemoryNamespace = input.scenario.includes("au_") ? "au" : "real_life"; const targetNamespace: MemoryNamespace = input.scenario === "blocked_au_to_real_life_contamination" ? "real_life" : ns; const id = `first-reviewed-memory-fixture-${String(i).padStart(2,"0")}`; const reviewItemId = `${id}-review-item`; const decisionId = `${id}-decision`; const memoryItemId = `${id}-memory-item`; const sourceId = `${id}-source`; const nonAppend = input.scenario === "blocked_non_append_decision"; const missingAudit = input.scenario === "blocked_missing_audit"; const contamination = input.scenario === "blocked_au_to_real_life_contamination"; const blocked = nonAppend || missingAudit || contamination; const decisionAction = nonAppend ? "reject" : "approve_append"; const blockerCodes = contamination ? ["au_to_real_life_contamination", "invalid_preview_plan"] : missingAudit ? ["missing_append_decision"] : nonAppend ? ["non_append_decision"] : []; const reviewItem = { id: reviewItemId, status: "approved_for_append" as const, userId, namespace: ns, extractedCandidateId: `${id}-candidate`, candidateType: "preference" as const, normalizedText: text[input.scenario], evidence: { spans: [{ text: text[input.scenario], span: { start: 0, end: text[input.scenario].length } }], spanRanges: [{ start: 0, end: text[input.scenario].length }], hasEvidence: true }, sensitivity: { level: "low" as const, requiresSensitiveReview: false, resolved: true }, requiresReview: true, appendOnly: !nonAppend, proposedOperation: nonAppend ? "update" as const : "append" as const, sourceMetadata: { source: "contract_test" as const, sourceType: "manual_fixture", capturedAt: at }, sourceRef: `${id}-source-ref`, namespaceIsolation: { namespace: ns, classification: ns, auOnly: ns === "au", realLifeOnly: ns === "real_life", explicitlyFictionalized: ns === "au", mixedContent: false, realLifeCannotConsumeAuEvidence: true as const, auContentCannotBecomeRealLifeEvidence: true as const }, blockers: nonAppend ? ["non_append_only_operation" as const] : [], warnings: ns === "au" ? ["au_story_scope_only" as const] : ["real_life_scope_only" as const], createdAt: at, updatedAt: at, audit: { createdByUserId: userId, updatedByUserId: userId, createdFrom: "contract_test" as const, requestHash: `${id}-request-hash`, fingerprint: fp(input.scenario), decisionTrail: missingAudit ? [{ action: "created" as const, at, reviewerUserId: userId }] : [{ action: "created" as const, at, reviewerUserId: userId }, { action: decisionAction as typeof decisionAction, at, reviewerUserId: userId, reason: "fixture decision" }] } };
 const decision = missingAudit ? undefined : { id: decisionId, itemId: reviewItemId, userId, namespace: ns, action: decisionAction as typeof decisionAction, reason: "fixture decision", createdAt: at, audit: { testOnly: true } };
 return { id, scenario: input.scenario, title: input.scenario.replaceAll("_", " "), description: "TEST-ONLY deterministic reviewed-memory fixture; not production seed data.", namespace: ns, targetNamespace, timestamp: at, fingerprint: fp(input.scenario), idempotencyKey: `${id}-idempotency`, typedConfirmation: "APPEND MEMORY", reviewItem, decision, decisionAction, expectedPreview: { ok: !blocked, fingerprint: fp(input.scenario), plannedSources: blocked ? 0 : 1, plannedItems: blocked ? 0 : 1, plannedPatches: blocked ? 0 : 1, plannedAuditLogs: blocked ? 0 : 1, blockers: blockerCodes }, expectedExecution: { shouldExecute: !blocked, memoryItemId: blocked ? undefined : memoryItemId, sourceId: blocked ? undefined : sourceId, patchIdsCount: blocked ? 0 : 1, auditEventIdsCount: blocked ? 0 : 1 }, expectedReadback: { shouldVerify: !blocked, memoryItemId: blocked ? undefined : memoryItemId, browserVisible: !blocked, auditVerified: !blocked }, expectedReceipt: { namespace: targetNamespace, reviewItemId, decisionId, memoryItemId: blocked ? undefined : memoryItemId, sourceId: blocked ? undefined : sourceId, patchIdsCount: blocked ? 0 : 1, auditEventIdsCount: blocked ? 0 : 1, readbackStatus: blocked ? "blocked" : "verified", browserVisibilityStatus: blocked ? "blocked" : "verified", auditVerificationStatus: blocked ? "blocked" : "verified" }, expectedBlocked: blocked, expectedBlockerCodes: blockerCodes, blockedExplanation: blocked ? "Fixture is intentionally blocked before production persistence." : undefined, safety: firstReviewedMemoryFixtureSafetySummary } }
export function buildAllFirstReviewedMemoryFixtures() { return scenarios.map((scenario) => buildFirstReviewedMemoryFixture({ scenario })); }
