import type { FirstControlledLiveAppendPacket, FirstControlledLiveAppendPacketInput } from "@/lib/services/first-controlled-live-append-packet-contract";
import { fingerprintFirstControlledLiveAppendPacketValue } from "@/lib/services/first-controlled-live-append-packet-export";
import { validateFirstControlledLiveAppendPacket } from "@/lib/services/first-controlled-live-append-packet-validator";
export const firstControlledLiveAppendFinalStopCondition = "After one approved memory append, stop. Capture receipt and proof report. Do not batch. Do not proceed to retrieval.";
const receiptFields = ["workflowId","namespace","serverUserFingerprint","reviewItemId","decisionId","memoryItemId","sourceId","patchCount","auditEventCount","idempotencyFingerprint","previewFingerprint","executionTimestamp","readbackStatus","browserVisibilityStatus","auditVerificationStatus"];
const proofFields = ["proofReportId","namespace","memoryItemId","receiptFingerprint","readbackVerification","browserVerification","auditVerification","operatorFingerprint","generatedAt","redacted"];
export function buildFirstControlledLiveAppendPacket(input: FirstControlledLiveAppendPacketInput): FirstControlledLiveAppendPacket {
  const validation = validateFirstControlledLiveAppendPacket(input); const s = input.sessionResult?.ok ? input.sessionResult.session : null; const generatedAt = input.generatedAt ?? "2026-01-01T00:00:00.000Z"; const operatorFingerprint = fingerprintFirstControlledLiveAppendPacketValue({ user: s?.userId ?? "missing", cap: s?.adminCapabilities ?? [] });
  const base = { namespace: input.namespace ?? "", reviewItemId: input.reviewItemId ?? "", decisionId: input.decisionId ?? "", previewFingerprint: input.preview?.fingerprint ?? "", idempotencyFingerprint: input.idempotencyFingerprint ?? "" };
  const ready = validation.ok && input.readinessLock?.ready === true && input.readinessLock.emergencyStop.enabled === false;
  const safetySummary = { internalOnly: true, packetOnly: true, oneItemOnly: true, performsPersistence: false, publicPersistenceEnabled: false, productionIngestEnabled: false, publicReadEnabled: false, wouldCallModel: false, wouldEmbed: false, semanticRetrievalEnabled: false, appendOnly: true, emergencyStopSupported: true, emergencyStopOverridesReadiness: true, requiresTypedConfirmation: true, requiresIdempotencyKey: true, requiresReceiptCapture: true, requiresProofReport: true, readyForOperatorExecution: ready } as const;
  const packetId = `first-live-append-packet-${fingerprintFirstControlledLiveAppendPacketValue(base)}`;
  const artifacts = ["preview","readiness_lock","runbook_validation","workflow_receipt","proof_report","readback_verifier","browser_verifier","audit_verifier"].map((id) => ({ id, label: id.replaceAll("_", " "), required: true as const, available: !validation.blockers.some((x) => x.code.includes(id.split("_")[0])), redacted: true as const }));
  const runbookStatus = input.runbookValidation ? (input.runbookValidation.ok === false || input.runbookValidation.status === "failed" ? "failed" : "passed") : "missing";
  return { packetId, generatedAt, operatorFingerprint, ...base, readinessLockStatus: input.readinessLock?.ready ? "ready" : "blocked", emergencyStopStatus: input.readinessLock?.emergencyStop.enabled ? "on" : "off", runbookValidationStatus: runbookStatus, manualWorkflowAvailability: input.manualWorkflowAvailable === true, liveOneItemWorkflowAvailability: input.liveOneItemWorkflowAvailable === true, proofPackAvailability: input.proofPackAvailable === true, readbackVerifierAvailability: input.readbackVerifierAvailable === true, browserVerifierAvailability: input.browserVerifierAvailable === true, auditVerifierAvailability: input.auditVerifierAvailable === true, exactOneItemStopCondition: firstControlledLiveAppendFinalStopCondition, requiredReceiptFields: receiptFields, requiredProofReportFields: proofFields, finalOperatorNextStep: "Manually perform exactly one internal append only after reviewing this packet.", safetySummary, preflightSnapshot: { readinessStatus: input.readinessLock?.ready ? "ready" : "blocked", emergencyStop: input.readinessLock?.emergencyStop ?? { enabled: false, source: "off", redacted: true }, runbookStatus, manualWorkflowAvailable: input.manualWorkflowAvailable === true, liveOneItemWorkflowAvailable: input.liveOneItemWorkflowAvailable === true, proofPackAvailable: input.proofPackAvailable === true, readbackVerifierAvailable: input.readbackVerifierAvailable === true, browserVerifierAvailable: input.browserVerifierAvailable === true, auditVerifierAvailable: input.auditVerifierAvailable === true }, executionPlan: { ...base, steps: ["validate packet","perform one append manually","capture receipt","capture proof report","stop before retrieval"].map((label, i) => ({ id: `step_${i+1}`, label, status: ready ? "passed" : "pending", required: true as const })), finalStopCondition: firstControlledLiveAppendFinalStopCondition, finalOperatorNextStep: "Stop after receipt and proof capture.", disabledExecutionButton: true }, proofPlan: { requiredReceiptFields: receiptFields, requiredProofReportFields: proofFields, artifacts }, blockers: validation.blockers, warnings: validation.warnings };
}
