import type { PandoraServerSessionResult } from "@/lib/auth/pandora-server-session-contract";
import type { FirstLiveAppendEmergencyStopState, FirstLiveAppendReadinessLockResult } from "@/lib/services/first-live-append-readiness-lock-contract";
import type { ControlledOperatorExecutionRunbook } from "@/lib/services/controlled-operator-execution-runbook-contract";

export type FirstControlledLiveAppendPacketStep = { id: string; label: string; status: "passed" | "blocked" | "pending"; required: true };
export type FirstControlledLiveAppendPacketBlocker = { code: string; message: string; redacted: true };
export type FirstControlledLiveAppendPacketWarning = { code: string; message: string; redacted: true };
export type FirstControlledLiveAppendPacketArtifact = { id: string; label: string; required: true; available: boolean; redacted: true };
export type FirstControlledLiveAppendPacketSafetySummary = { internalOnly: true; packetOnly: true; oneItemOnly: true; performsPersistence: false; publicPersistenceEnabled: false; productionIngestEnabled: false; publicReadEnabled: false; wouldCallModel: false; wouldEmbed: false; semanticRetrievalEnabled: false; appendOnly: true; emergencyStopSupported: true; emergencyStopOverridesReadiness: true; requiresTypedConfirmation: true; requiresIdempotencyKey: true; requiresReceiptCapture: true; requiresProofReport: true; readyForOperatorExecution: boolean };
export type FirstControlledLiveAppendPacketPreflightSnapshot = { readinessStatus: "ready" | "blocked"; emergencyStop: FirstLiveAppendEmergencyStopState; runbookStatus: "passed" | "failed" | "missing"; manualWorkflowAvailable: boolean; liveOneItemWorkflowAvailable: boolean; proofPackAvailable: boolean; readbackVerifierAvailable: boolean; browserVerifierAvailable: boolean; auditVerifierAvailable: boolean };
export type FirstControlledLiveAppendPacketExecutionPlan = { namespace: string; reviewItemId: string; decisionId: string; previewFingerprint: string; idempotencyFingerprint: string; steps: FirstControlledLiveAppendPacketStep[]; finalStopCondition: string; finalOperatorNextStep: string; disabledExecutionButton: true };
export type FirstControlledLiveAppendPacketProofPlan = { requiredReceiptFields: string[]; requiredProofReportFields: string[]; artifacts: FirstControlledLiveAppendPacketArtifact[] };
export type FirstControlledLiveAppendPacket = { packetId: string; generatedAt: string; operatorFingerprint: string; namespace: string; reviewItemId: string; decisionId: string; previewFingerprint: string; idempotencyFingerprint: string; readinessLockStatus: "ready" | "blocked"; emergencyStopStatus: "on" | "off"; runbookValidationStatus: "passed" | "failed" | "missing"; manualWorkflowAvailability: boolean; liveOneItemWorkflowAvailability: boolean; proofPackAvailability: boolean; readbackVerifierAvailability: boolean; browserVerifierAvailability: boolean; auditVerifierAvailability: boolean; exactOneItemStopCondition: string; requiredReceiptFields: string[]; requiredProofReportFields: string[]; finalOperatorNextStep: string; safetySummary: FirstControlledLiveAppendPacketSafetySummary; preflightSnapshot: FirstControlledLiveAppendPacketPreflightSnapshot; executionPlan: FirstControlledLiveAppendPacketExecutionPlan; proofPlan: FirstControlledLiveAppendPacketProofPlan; blockers: FirstControlledLiveAppendPacketBlocker[]; warnings: FirstControlledLiveAppendPacketWarning[] };
export type FirstControlledLiveAppendPacketResult = { ok: boolean; blockers: FirstControlledLiveAppendPacketBlocker[]; warnings: FirstControlledLiveAppendPacketWarning[] };
export type FirstControlledLiveAppendPacketExport = Pick<FirstControlledLiveAppendPacket, "packetId" | "namespace" | "operatorFingerprint" | "reviewItemId" | "decisionId" | "previewFingerprint" | "idempotencyFingerprint" | "requiredReceiptFields" | "requiredProofReportFields" | "generatedAt" | "safetySummary"> & { readinessStatus: "ready" | "blocked"; emergencyStopStatus: "on" | "off"; runbookStatus: "passed" | "failed" | "missing"; finalStopCondition: string };
export type FirstControlledLiveAppendPacketInput = { sessionResult?: PandoraServerSessionResult; namespace?: string; allowedNamespaces?: string[]; reviewItemId?: string; reviewItemIds?: string[]; reviewItemStatus?: string; reviewItemApprovedForAppend?: boolean; decisionId?: string; decisionIds?: string[]; decisionType?: string; decisionReviewItemId?: string; preview?: { eligible?: boolean; fingerprint?: string; memoryText?: string; evidenceText?: string } | null; idempotencyKey?: string; idempotencyFingerprint?: string; typedConfirmation?: string; readinessLock?: FirstLiveAppendReadinessLockResult; runbookValidation?: { ok?: boolean; status?: "passed" | "failed" } | null; runbook?: ControlledOperatorExecutionRunbook; manualWorkflowAvailable?: boolean; liveOneItemWorkflowAvailable?: boolean; proofPackAvailable?: boolean; proofCaptureAvailable?: boolean; readbackVerifierAvailable?: boolean; browserVerifierAvailable?: boolean; auditVerifierAvailable?: boolean; publicPersistenceEnabled?: boolean; productionIngestEnabled?: boolean; publicReadEnabled?: boolean; modelCallsEnabled?: boolean; embeddingsEnabled?: boolean; semanticRetrievalEnabled?: boolean; gptActionsEnabled?: boolean; mcpEnabled?: boolean; serviceRoleExposureDetected?: boolean; packetContent?: unknown; rawErrors?: unknown; user_id?: unknown; userId?: unknown; generatedAt?: string };
