import type { PandoraServerSessionResult } from "@/lib/auth/pandora-server-session-contract";
import type { PandoraRuntimeSafetyConfigResult } from "@/lib/config/pandora-runtime-safety-config";

export type FirstLiveAppendReadinessLockStatus = "passed" | "blocked" | "warning";
export type FirstLiveAppendReadinessCheckName = "server_session_resolved" | "authenticated_operator_verified" | "operator_capability_verified" | "namespace_selected" | "namespace_allowed" | "review_item_selected" | "exactly_one_review_item_selected" | "review_item_approved_for_append" | "append_decision_selected" | "exactly_one_append_decision_selected" | "decision_belongs_to_review_item" | "preview_generated" | "preview_eligible" | "idempotency_key_present" | "typed_confirmation_matches" | "manual_workflow_available" | "live_one_item_workflow_available" | "proof_pack_available" | "controlled_runbook_available" | "proof_capture_available" | "readback_verification_available" | "browser_visibility_verification_available" | "audit_verification_available" | "public_persistence_disabled" | "production_ingest_disabled" | "public_read_disabled" | "model_calls_disabled" | "embeddings_disabled" | "semantic_retrieval_disabled" | "gpt_actions_disabled" | "mcp_disabled" | "emergency_stop_off";
export type FirstLiveAppendReadinessLockCheck = { id: FirstLiveAppendReadinessCheckName; label: string; required: true; status: FirstLiveAppendReadinessLockStatus; blockerCode?: string };
export type FirstLiveAppendReadinessLockBlocker = { code: string; check: FirstLiveAppendReadinessCheckName; message: string; priority?: "emergency" | "required" };
export type FirstLiveAppendReadinessLockWarning = { code: string; message: string };
export type FirstLiveAppendEmergencyStopState = { enabled: boolean; source: "runtime_config" | "operator_flag" | "provider" | "off"; redacted: true; reason?: string };
export type FirstLiveAppendRequiredArtifact = { id: string; label: string; required: true; available: boolean; redacted: true };
export type FirstLiveAppendReadinessSafetySummary = { internalOnly: true; oneItemOnly: true; emergencyStopSupported: true; emergencyStopOverridesExecution: true; publicPersistenceEnabled: false; productionIngestEnabled: false; publicReadEnabled: false; wouldCallModel: false; wouldEmbed: false; semanticRetrievalEnabled: false; appendOnly: true; requiresTypedConfirmation: true; requiresIdempotencyKey: true; requiresReceiptCapture: true; requiresProofReport: true; readyForFirstLiveAppend: boolean };
export type FirstLiveAppendReadinessLockInput = { sessionResult?: PandoraServerSessionResult; runtime?: PandoraRuntimeSafetyConfigResult; namespace?: string; allowedNamespaces?: string[]; reviewItemId?: string; reviewItemIds?: string[]; reviewItemStatus?: string; reviewItemApprovedForAppend?: boolean; decisionId?: string; decisionIds?: string[]; decisionReviewItemId?: string; appendDecisionSelected?: boolean; preview?: { eligible?: boolean } | null; idempotencyKey?: string; typedConfirmation?: string; manualWorkflowAvailable?: boolean; liveOneItemWorkflowAvailable?: boolean; proofPackAvailable?: boolean; controlledRunbookAvailable?: boolean; proofCaptureAvailable?: boolean; readbackVerificationAvailable?: boolean; browserVisibilityVerificationAvailable?: boolean; auditVerificationAvailable?: boolean; publicPersistenceEnabled?: boolean; productionIngestEnabled?: boolean; publicReadEnabled?: boolean; modelCallsEnabled?: boolean; embeddingsEnabled?: boolean; semanticRetrievalEnabled?: boolean; gptActionsEnabled?: boolean; mcpEnabled?: boolean; emergencyStop?: FirstLiveAppendEmergencyStopState; user_id?: unknown; userId?: unknown };
export type FirstLiveAppendReadinessLockResult = { ready: boolean; status: "ready" | "blocked"; checks: FirstLiveAppendReadinessLockCheck[]; blockers: FirstLiveAppendReadinessLockBlocker[]; warnings: FirstLiveAppendReadinessLockWarning[]; emergencyStop: FirstLiveAppendEmergencyStopState; requiredArtifacts: FirstLiveAppendRequiredArtifact[]; safetySummary: FirstLiveAppendReadinessSafetySummary };
export const firstLiveAppendRequiredArtifacts = ["preview", "idempotency_key", "typed_confirmation", "workflow_receipt", "proof_report", "readback_verification", "browser_visibility_verification", "audit_verification"].map((id) => ({ id, label: id.replaceAll("_", " "), required: true as const, available: false, redacted: true as const }));
export function buildFirstLiveAppendSafetySummary(readyForFirstLiveAppend: boolean): FirstLiveAppendReadinessSafetySummary { return { internalOnly: true, oneItemOnly: true, emergencyStopSupported: true, emergencyStopOverridesExecution: true, publicPersistenceEnabled: false, productionIngestEnabled: false, publicReadEnabled: false, wouldCallModel: false, wouldEmbed: false, semanticRetrievalEnabled: false, appendOnly: true, requiresTypedConfirmation: true, requiresIdempotencyKey: true, requiresReceiptCapture: true, requiresProofReport: true, readyForFirstLiveAppend }; }
