import type { PandoraRuntimeSafetyConfigResult } from "@/lib/config/pandora-runtime-safety-config";
import type { PandoraServerSessionResult } from "@/lib/auth/pandora-server-session-contract";
import type { RepositoryContext } from "@/lib/db/repository-context";
import type { MemoryNamespace } from "@/lib/services/memory-extraction-contract";
import type { ApprovedReviewMemoryPersistenceExecutorResult } from "@/lib/services/approved-review-memory-persistence-executor-contract";
import type { ApprovedReviewPersistencePreviewResult } from "@/lib/services/approved-review-memory-persistence-preview-contract";

export type LiveOneReviewedItemWorkflowStepName = "server_session_resolved" | "runtime_gates_resolved" | "internal_operator_capability_verified" | "namespace_verified" | "review_item_loaded" | "review_item_approved_for_append" | "append_decision_loaded" | "preview_built" | "idempotency_verified" | "typed_confirmation_verified" | "approved_review_executor_selected" | "persistence_executed" | "readback_verified" | "browser_visibility_verified" | "audit_verified" | "receipt_produced";
export const liveOneReviewedItemWorkflowStepNames: LiveOneReviewedItemWorkflowStepName[] = ["server_session_resolved", "runtime_gates_resolved", "internal_operator_capability_verified", "namespace_verified", "review_item_loaded", "review_item_approved_for_append", "append_decision_loaded", "preview_built", "idempotency_verified", "typed_confirmation_verified", "approved_review_executor_selected", "persistence_executed", "readback_verified", "browser_visibility_verified", "audit_verified", "receipt_produced"];
export type LiveOneReviewedItemWorkflowStep = { name: LiveOneReviewedItemWorkflowStepName; status: "pending" | "passed" | "blocked"; message?: string };
export type LiveOneReviewedItemWorkflowBlocker = { code: string; step?: LiveOneReviewedItemWorkflowStepName; message: string };
export type LiveOneReviewedItemWorkflowWarning = { code: string; step?: LiveOneReviewedItemWorkflowStepName; message: string };
export type LiveOneReviewedItemWorkflowSafetySummary = { internalOnly: true; oneItemOnly: true; publicPersistenceEnabled: false; productionIngestEnabled: false; publicReadEnabled: false; wouldCallModel: false; wouldEmbed: false; semanticRetrievalEnabled: false; appendOnly: true; requiresTypedConfirmation: true; requiresIdempotencyKey: true; requiresAuditVerification: true };
export const liveOneReviewedItemWorkflowSafetySummary: LiveOneReviewedItemWorkflowSafetySummary = { internalOnly: true, oneItemOnly: true, publicPersistenceEnabled: false, productionIngestEnabled: false, publicReadEnabled: false, wouldCallModel: false, wouldEmbed: false, semanticRetrievalEnabled: false, appendOnly: true, requiresTypedConfirmation: true, requiresIdempotencyKey: true, requiresAuditVerification: true };
export type LiveOneReviewedItemWorkflowReadiness = { ok: boolean; gatesAvailable: boolean; disabledByDefault: true; blockers: string[] };
export type LiveOneReviewedItemWorkflowReceipt = { workflowId: string; namespace: MemoryNamespace; serverUserFingerprint: string; reviewItemId: string; decisionId: string; memoryItemId?: string; sourceId?: string; patchCount: number; auditEventCount: number; idempotencyFingerprint: string; previewFingerprint: string; executionTimestamp: string; readbackStatus: "verified" | "blocked"; browserVisibilityStatus: "verified" | "blocked"; auditVerificationStatus: "verified" | "blocked"; safety: LiveOneReviewedItemWorkflowSafetySummary };
export type LiveOneReviewedItemWorkflowInput = { requestId?: string; context?: RepositoryContext; sessionResult?: PandoraServerSessionResult; runtime?: PandoraRuntimeSafetyConfigResult; namespace?: MemoryNamespace; allowedNamespaces?: MemoryNamespace[]; reviewItemId?: string; decisionId?: string; idempotencyKey?: string; typedConfirmation?: string; internalHeaderMode?: string | null; operatorCapability?: boolean; clientUserId?: string; client_user_id?: string; userId?: string; user_id?: string; preview?: ApprovedReviewPersistencePreviewResult; execution?: ApprovedReviewMemoryPersistenceExecutorResult };
export type LiveOneReviewedItemWorkflowResult = { ok: boolean; executed: boolean; safety: LiveOneReviewedItemWorkflowSafetySummary; steps: LiveOneReviewedItemWorkflowStep[]; blockers: LiveOneReviewedItemWorkflowBlocker[]; warnings: LiveOneReviewedItemWorkflowWarning[]; readiness?: LiveOneReviewedItemWorkflowReadiness; receipt?: LiveOneReviewedItemWorkflowReceipt; previewFingerprint?: string };
