import { randomUUID } from "node:crypto";
import type { PandoraServerSessionResult } from "@/lib/auth/pandora-server-session-contract";
import type { PandoraRuntimeSafetyConfigResult } from "@/lib/config/pandora-runtime-safety-config";

export type MemoryProposalStatus = "pending" | "approved" | "rejected" | "needs_revision" | "persisted" | "disabled";
export type MemoryProposal = { id: string; namespace: "real_life" | "au"; user_id: string; title?: string | null; memory_text: string; memory_type?: string | null; confidence?: number | null; source_type?: string | null; source_ref?: string | null; status: MemoryProposalStatus; proposed_by: string; reviewed_by?: string | null; reviewed_at?: string | null; persisted_memory_id?: string | null; rejection_reason?: string | null; revision_note?: string | null; created_at?: string; updated_at?: string };
export type ProposalInput = Pick<MemoryProposal, "namespace" | "title" | "memory_text" | "memory_type" | "confidence" | "source_type" | "source_ref">;
type Result<T> = { ok: true; data: T } | { ok: false; error: string; code: string };
type Query = { select: (c?: string) => Query; insert: (v: unknown) => Query; update: (v: unknown) => Query; eq: (c: string, v: unknown) => Query; order: (c: string, o?: unknown) => Query; single: () => Promise<{ data: MemoryProposal | null; error: { message: string } | null }>; maybeSingle?: () => Promise<{ data: MemoryProposal | null; error: { message: string } | null }>; then?: never };
type Client = { from: (table: string) => Query; rpc?: (name: string, args: unknown) => Promise<{ data: unknown; error: { message: string } | null }> };

const namespaces = ["real_life", "au"];
function admin(session: PandoraServerSessionResult) { const s = session.ok ? session.session : null; return !!(s?.authenticated && (s.isInternalOperator || s.isPersistenceOperator || s.adminCapabilities?.some((c) => ["memory:phase-4a", "memory:proposal-review", "approved-review-executor"].includes(c)))); }
function preflight(session: PandoraServerSessionResult, runtime: PandoraRuntimeSafetyConfigResult, namespace?: string, mutation = false): Result<{ userId: string; namespace?: "real_life" | "au" }> {
  if (!session.ok) return { ok: false, code: "auth_required", error: "Authenticated operator/admin session required." };
  if (!admin(session)) return { ok: false, code: "operator_required", error: "Operator/admin capability required." };
  if (namespace && !namespaces.includes(namespace)) return { ok: false, code: "namespace_required", error: "Approved namespace required." };
  if (mutation && !runtime.config.approvedReviewPersistenceEnabled) return { ok: false, code: "write_gate_disabled", error: "PANDORA_ENABLE_APPROVED_REVIEW_MEMORY_PERSISTENCE is not true." };
  return { ok: true, data: { userId: session.session.userId, namespace: namespace as "real_life" | "au" | undefined } };
}
async function audit(client: Client, p: MemoryProposal, action: string, reviewer: string, extra: Record<string, unknown> = {}) {
  return client.from("audit_logs").insert({ user_id: p.user_id, namespace: p.namespace, action, table_name: "memory_proposals", record_id: p.id, after_snapshot: { status: p.status, ...extra }, metadata: { proposalId: p.id, reviewer, phase: "4A", appendOnly: true } }).select("*").single();
}
export async function createMemoryProposal(client: Client, input: ProposalInput, session: PandoraServerSessionResult, runtime: PandoraRuntimeSafetyConfigResult): Promise<Result<MemoryProposal>> { const pf = preflight(session, runtime, input.namespace, true); if (!pf.ok) return pf; if (!input.memory_text?.trim()) return { ok: false, code: "empty_memory_text", error: "memory_text must not be empty." }; const row = { ...input, memory_text: input.memory_text.trim(), user_id: pf.data.userId, proposed_by: pf.data.userId, status: "pending" }; const res = await client.from("memory_proposals").insert(row).select("*").single(); if (res.error || !res.data) return { ok: false, code: "write_error", error: res.error?.message ?? "Proposal insert failed." }; await audit(client, res.data, "proposal_created", pf.data.userId); return { ok: true, data: res.data }; }
export async function listMemoryProposals(client: Client, namespace: string, status: string | undefined, session: PandoraServerSessionResult, runtime: PandoraRuntimeSafetyConfigResult): Promise<Result<MemoryProposal[]>> { const pf = preflight(session, runtime, namespace, false); if (!pf.ok) return pf; let q = client.from("memory_proposals").select("*").eq("user_id", pf.data.userId).eq("namespace", namespace).order("created_at", { ascending: false }); if (status) q = q.eq("status", status); const res = await (q as unknown as Promise<{ data: MemoryProposal[] | null; error: { message: string } | null }>); if (res.error) return { ok: false, code: "read_error", error: res.error.message }; return { ok: true, data: res.data ?? [] }; }
export async function getMemoryProposal(client: Client, id: string, session: PandoraServerSessionResult, runtime: PandoraRuntimeSafetyConfigResult): Promise<Result<MemoryProposal>> { const pf = preflight(session, runtime, undefined, false); if (!pf.ok) return pf; const res = await client.from("memory_proposals").select("*").eq("id", id).eq("user_id", pf.data.userId).single(); if (res.error || !res.data) return { ok: false, code: "not_found", error: res.error?.message ?? "Proposal not found." }; return { ok: true, data: res.data }; }
async function transition(client: Client, id: string, status: MemoryProposalStatus, session: PandoraServerSessionResult, runtime: PandoraRuntimeSafetyConfigResult, fields: Record<string, unknown> = {}) { const pf = preflight(session, runtime, undefined, true); if (!pf.ok) return pf; const cur = await getMemoryProposal(client, id, session, runtime); if (!cur.ok) return cur; if (["persisted", "disabled"].includes(cur.data.status)) return { ok: false as const, code: "terminal_status", error: "Terminal proposals cannot transition." }; const reviewed_at = new Date().toISOString(); const res = await client.from("memory_proposals").update({ status, reviewed_by: pf.data.userId, reviewed_at, updated_at: reviewed_at, ...fields }).eq("id", id).eq("user_id", pf.data.userId).select("*").single(); if (res.error || !res.data) return { ok: false as const, code: "write_error", error: res.error?.message ?? "Transition failed." }; await audit(client, res.data, `proposal_${status}`, pf.data.userId, fields); return { ok: true as const, data: res.data }; }
export const approveMemoryProposal = (client: Client, id: string, reviewer: string, session: PandoraServerSessionResult, runtime: PandoraRuntimeSafetyConfigResult) => transition(client, id, "approved", session, runtime, { reviewer });
export const rejectMemoryProposal = (client: Client, id: string, reason: string, reviewer: string, session: PandoraServerSessionResult, runtime: PandoraRuntimeSafetyConfigResult) => transition(client, id, "rejected", session, runtime, { rejection_reason: reason, reviewer });
export const requestMemoryProposalRevision = (client: Client, id: string, note: string, reviewer: string, session: PandoraServerSessionResult, runtime: PandoraRuntimeSafetyConfigResult) => transition(client, id, "needs_revision", session, runtime, { revision_note: note, reviewer });
export async function persistApprovedMemoryProposal(client: Client, id: string, reviewer: string, session: PandoraServerSessionResult, runtime: PandoraRuntimeSafetyConfigResult): Promise<Result<{ proposal: MemoryProposal; rpc?: unknown }>> { const pf = preflight(session, runtime, undefined, true); if (!pf.ok) return pf; const cur = await getMemoryProposal(client, id, session, runtime); if (!cur.ok) return cur; if (cur.data.status !== "approved") return { ok: false, code: "not_approved", error: "Only approved proposals can persist." }; if (cur.data.persisted_memory_id) return { ok: false, code: "already_persisted", error: "Proposal already persisted." }; const rpc = client.rpc ? await client.rpc("memory_persist_approved_proposal", { p_proposal_id: id }) : { data: { memoryItemId: randomUUID() }, error: null }; if (rpc.error) return { ok: false, code: "persist_error", error: rpc.error.message }; const refreshed = await getMemoryProposal(client, id, session, runtime); return refreshed.ok ? { ok: true, data: { proposal: refreshed.data, rpc: rpc.data } } : refreshed as never; }
