import { classifyMemoryCandidatesDeterministic, type ClassificationInput, memoryCandidateSchema } from "@/lib/services/memory-classification-service";
import { detectSecrets, redactSecrets, assertNoSecretsForModel } from "@/lib/services/memory-redaction-service";
export type MemoryModelTask = "classification"|"summarization"|"profile_extraction"|"distillation";
export function modelCallsEnabled(env: Partial<NodeJS.ProcessEnv> = process.env) { return env.PANDORA_ENABLE_MODEL_CALLS === "true"; }
export function prepareModelInput(text:string, env: Partial<NodeJS.ProcessEnv> = process.env) { const truncated = text.slice(0, Number(env.PANDORA_MODEL_MAX_INPUT_CHARS ?? 12000)); const redacted = env.PANDORA_REDACT_BEFORE_MODEL_CALL !== "false" ? redactSecrets(truncated) : truncated; assertNoSecretsForModel(redacted); return { text: redacted, redacted: redacted !== truncated, input_char_count: redacted.length }; }
export async function classifyMemoryCandidatesWithProvider(input: ClassificationInput, env: Partial<NodeJS.ProcessEnv> = process.env) { if (!modelCallsEnabled(env)) return { candidates: classifyMemoryCandidatesDeterministic(input), usedModel: false, metadata: { provider:"deterministic", redacted:false } }; if (detectSecrets(input.text).detected) return { candidates: classifyMemoryCandidatesDeterministic(input).map(c=>memoryCandidateSchema.parse(c)), usedModel:false, metadata:{ provider:"deterministic", redacted:true, fallback:"deterministic_pre_redaction" } }; const prepared=prepareModelInput(input.text, env); return { candidates: classifyMemoryCandidatesDeterministic({ ...input, text: prepared.text }).map(c=>memoryCandidateSchema.parse(c)), usedModel: false, metadata: { provider: env.PANDORA_MODEL_PROVIDER ?? "openai-compatible", model: env.PANDORA_MEMORY_ANALYSIS_MODEL, redacted: prepared.redacted, fallback:"deterministic_until_provider_configured" } }; }
export async function summarizeSession(input:{text:string}, env:Partial<NodeJS.ProcessEnv>=process.env){ const prepared=prepareModelInput(input.text,env); return { title:"Session digest", summary: prepared.text.replace(/\s+/g," ").slice(0,1000), model_used:false, redacted:prepared.redacted }; }
export async function extractAdaptiveProfile(input:{text:string}, env:Partial<NodeJS.ProcessEnv>=process.env){ const s=await summarizeSession(input,env); return { profile_type:"operating_profile", subject_key:"global", summary:s.summary, evidence_refs:[] }; }
export async function distillContextPack(input:{text:string}, env:Partial<NodeJS.ProcessEnv>=process.env){ return summarizeSession(input,env); }
