/* eslint-disable @typescript-eslint/no-explicit-any */
import type { MemoryBridgeDbClient, MemoryBridgeNamespace } from "@/lib/services/memory-bridge-service";
import { summarizeSession } from "@/lib/services/memory-model-provider";
import { createCandidatesFromSession } from "@/lib/services/memory-candidate-service";
import { runDailyMemoryCompaction } from "@/lib/services/memory-compaction-service";
import { buildMasterContextPack } from "@/lib/services/memory-distillation-service";
export async function createSessionDigest(client:MemoryBridgeDbClient,input:{user_id:string;namespace:MemoryBridgeNamespace;source:string;source_ref?:string;transcript_or_summary:string;auto_capture?:boolean;update_profiles?:boolean;distill?:boolean}){ const s=await summarizeSession({text:input.transcript_or_summary}); const c=await createCandidatesFromSession(client,{user_id:input.user_id,namespace:input.namespace,source:input.source,source_ref:input.source_ref,text:input.transcript_or_summary}); const row={user_id:input.user_id,namespace:input.namespace,source:input.source,source_ref:input.source_ref,title:s.title,summary:s.summary,durable_updates:c.candidates,decisions:[],open_loops:[],risks:[],people:[],projects:[],style_updates:[],candidate_ids:(c.candidates as any[]).map(x=>x.id).filter(Boolean),captured_event_ids:[],profile_ids:[]}; const r=await client.from("memory_session_digests").insert(row).select("*").single(); return {digest:r.data??row,warnings:[...(c.warnings??[]),...(r.error?[r.error.message]:[])]}; }
export const digestSessionTranscript=createSessionDigest;
export const digestSessionSummary=createSessionDigest;
export async function compoundSessionIntoProfiles(client:MemoryBridgeDbClient,input:{user_id:string;namespace:MemoryBridgeNamespace;since?:string;dry_run?:boolean}){ const r=await runDailyMemoryCompaction(client,input); return {ok:r.ok,data:{updated_profiles:r.updated_profiles,opened_or_updated_loops:r.opened_or_updated_loops},blockers:r.blockers,warnings:r.warnings}; }
export async function createDailyPackFromSessionDigests(client:MemoryBridgeDbClient,input:{user_id:string;namespace:MemoryBridgeNamespace;since?:string;dry_run?:boolean}){ const r=await runDailyMemoryCompaction(client,input); return {ok:r.ok,data:r.daily_pack,blockers:r.blockers,warnings:r.warnings}; }
export async function createMasterPackFromProfiles(client:MemoryBridgeDbClient,input:{user_id:string;namespace:MemoryBridgeNamespace;dry_run?:boolean}){ const events=await (client.from("memory_events").select("*").eq("user_id",input.user_id).eq("namespace",input.namespace).order("created_at",{ascending:false}).limit(50) as any as Promise<{data:any[]|null;error:{message:string}|null}>); if(events.error)return {ok:false,data:null,blockers:["event_read_failed"],warnings:[events.error.message]}; const pack=buildMasterContextPack(input.namespace,input.user_id,events.data??[]); if(input.dry_run)return {ok:true,data:pack,blockers:[],warnings:[]}; const ins=await client.from("memory_context_packs").insert({...pack,status:"active"}).select("*").single(); return {ok:!ins.error,data:ins.data??pack,blockers:ins.error?["master_pack_write_failed"]:[],warnings:ins.error?[ins.error.message]:[]}; }
