import { resolvePandoraMemoryAutopilotMode, resolvePandoraRuntimeSafetyConfig } from "@/lib/config/pandora-runtime-safety-config";
import { buildAdaptiveChatGptContext } from "@/lib/services/adaptive-chatgpt-context-service";
import { createCandidatesFromSession } from "@/lib/services/memory-candidate-service";
import type { MemoryBridgeDbClient, MemoryBridgeNamespace } from "@/lib/services/memory-bridge-service";
import { redactSecrets } from "@/lib/services/memory-redaction-service";
import { shouldAutoCreateMemoryCandidate, shouldAutoRetrieveMemory, type AutoCandidateDecision, type AutoRetrieveDecision } from "@/lib/services/memory-autopilot-policy-service";

export type AdaptiveTurnInput = { namespace: MemoryBridgeNamespace; user_message: string; assistant_draft?: string; current_task?: string; conversation_type?: string; mode: "pre_answer" | "post_answer"; source?: string };
export function autopilotSafety(env: Partial<NodeJS.ProcessEnv> = process.env) { const r=resolvePandoraRuntimeSafetyConfig(env).config; return { public_read:false, public_persistence:false, model_calls:r.modelCallsEnabled, embeddings:r.embeddingsEnabled, semantic_retrieval:r.semanticRetrievalEnabled, auto_capture_low_risk:r.autoCaptureLowRiskEnabled }; }
export function disabledPreAnswer(input: AdaptiveTurnInput, env: Partial<NodeJS.ProcessEnv> = process.env) { const mode=resolvePandoraMemoryAutopilotMode(env); const decision=shouldAutoRetrieveMemory({userMessage:input.user_message,namespace:input.namespace,currentTask:input.current_task,conversationType:input.conversation_type}); const r=resolvePandoraRuntimeSafetyConfig(env).config; const enabled=r.memoryAutopilotEnabled&&r.autoRetrieveEnabled&&mode!=="off"; return {ok:true,mode:"pre_answer" as const,autopilot_mode:mode,namespace:input.namespace,should_retrieve:enabled&&decision.shouldRetrieve,retrieve_decision:decision,context:null,warnings:enabled?[]:["autopilot_or_auto_retrieve_disabled"],safety:autopilotSafety(env)}; }
export async function runPreAnswerTurn(client: MemoryBridgeDbClient, userId: string, input: AdaptiveTurnInput, env: Partial<NodeJS.ProcessEnv> = process.env) { const base=disabledPreAnswer(input,env); if(!base.should_retrieve)return base; const context=await buildAdaptiveChatGptContext(client,{user_id:userId,namespace:input.namespace,query:redactSecrets(input.user_message),current_task:redactSecrets(input.current_task??""),max_items:8}); return {...base,context,warnings:[...base.warnings,...(context.warnings??[])]}; }
export function disabledPostAnswer(input: AdaptiveTurnInput, env: Partial<NodeJS.ProcessEnv> = process.env) { const mode=resolvePandoraMemoryAutopilotMode(env); const decision=shouldAutoCreateMemoryCandidate({userMessage:input.user_message,assistantResponse:input.assistant_draft,namespace:input.namespace,currentTask:input.current_task,source:input.source}); const r=resolvePandoraRuntimeSafetyConfig(env).config; const enabled=r.memoryAutopilotEnabled&&r.autoCandidateQueueEnabled&&(mode==="queue"||mode==="capture_low_risk"); return {ok:true,mode:"post_answer" as const,autopilot_mode:mode,namespace:decision.namespace,should_create_candidate:enabled&&decision.shouldCreateCandidate,candidate_decision:decision,candidates:[],warnings:enabled?[]:["autopilot_or_auto_candidate_queue_disabled"],safety:autopilotSafety(env)}; }
export async function runPostAnswerTurn(client: MemoryBridgeDbClient, userId: string, input: AdaptiveTurnInput, env: Partial<NodeJS.ProcessEnv> = process.env) { const base=disabledPostAnswer(input,env); if(!base.should_create_candidate)return base; const candidateText=[`User: ${input.user_message}`,input.assistant_draft?`Assistant: ${input.assistant_draft}`:null].filter(Boolean).join("\n\n"); const data=await createCandidatesFromSession(client,{user_id:userId,namespace:base.namespace,source:input.source??"adaptive_turn",text:candidateText,mode:"candidate_only"},env); const warnings=[...base.warnings,...(data.warnings??[])]; if(base.autopilot_mode==="capture_low_risk") warnings.push("auto_capture_not_implemented"); return {...base,candidates:data.candidates,warnings}; }
export type { AutoRetrieveDecision, AutoCandidateDecision };
