import { createHash } from "crypto";
import { oneItemExecutionProofSafetySummary, type OneItemExecutionProofInput, type OneItemExecutionProofReport } from "@/lib/services/one-item-execution-proof-contract";

export function fingerprintOneItemExecutionProofValue(input: unknown): string { return createHash("sha256").update(JSON.stringify(input ?? "")).digest("hex").slice(0, 24); }
export function buildOneItemExecutionProofReport(input: OneItemExecutionProofInput & { readbackStatus?: "verified" | "blocked"; browserVisibilityStatus?: "verified" | "blocked"; auditVerificationStatus?: "verified" | "blocked"; appendOnlyVerificationStatus?: "verified" | "blocked"; auditEventCount?: number; patchCount?: number }): OneItemExecutionProofReport {
  const r = input.liveWorkflowReceipt!;
  return redactOneItemExecutionProofReport({ proofId: `proof_${fingerprintOneItemExecutionProofValue([r.workflowId, r.memoryItemId, r.executionTimestamp])}`, namespace: r.namespace, serverUserFingerprint: r.serverUserFingerprint, workflowReceiptFingerprint: fingerprintOneItemExecutionProofValue(r), reviewItemId: r.reviewItemId, decisionId: r.decisionId, memoryItemId: r.memoryItemId!, sourceId: r.sourceId, patchCount: input.patchCount ?? r.patchCount ?? 0, auditEventCount: input.auditEventCount ?? r.auditEventCount ?? 0, previewFingerprint: r.previewFingerprint, idempotencyFingerprint: r.idempotencyFingerprint, readbackStatus: input.readbackStatus ?? "verified", browserVisibilityStatus: input.browserVisibilityStatus ?? "verified", auditVerificationStatus: input.auditVerificationStatus ?? "verified", appendOnlyVerificationStatus: input.appendOnlyVerificationStatus ?? "verified", proofTimestamp: new Date().toISOString(), safety: oneItemExecutionProofSafetySummary });
}
export function redactOneItemExecutionProofReport(input: OneItemExecutionProofReport): OneItemExecutionProofReport { return JSON.parse(JSON.stringify(input, (key, value) => /userId|user_id|idempotencyKey|memoryText|evidence|rawSource|env|secret|serviceRole|service-role|error/i.test(key) ? undefined : value)); }
