import type { PandoraRuntimeSafetyConfigResult } from "@/lib/config/pandora-runtime-safety-config";
import type { PandoraServerSessionResult } from "@/lib/auth/pandora-server-session-contract";
import type { MemoryNamespace } from "@/lib/services/memory-extraction-contract";
import type { LiveOneReviewedItemWorkflowReceipt } from "@/lib/services/live-one-reviewed-item-workflow-contract";

export type OneItemExecutionProofStepName = "server_session_resolved" | "operator_capability_verified" | "namespace_verified" | "live_workflow_receipt_loaded" | "receipt_safety_verified" | "memory_item_id_verified" | "source_id_verified" | "idempotency_fingerprint_verified" | "preview_fingerprint_verified" | "readback_verified" | "browser_visibility_verified" | "audit_trail_verified" | "append_only_proof_verified" | "redaction_verified" | "final_proof_report_produced" | "proof_export_prepared";
export const oneItemExecutionProofStepNames: OneItemExecutionProofStepName[] = ["server_session_resolved", "operator_capability_verified", "namespace_verified", "live_workflow_receipt_loaded", "receipt_safety_verified", "memory_item_id_verified", "source_id_verified", "idempotency_fingerprint_verified", "preview_fingerprint_verified", "readback_verified", "browser_visibility_verified", "audit_trail_verified", "append_only_proof_verified", "redaction_verified", "final_proof_report_produced", "proof_export_prepared"];
export type OneItemExecutionProofStep = { name: OneItemExecutionProofStepName; status: "pending" | "passed" | "blocked"; message?: string };
export type OneItemExecutionProofBlocker = { code: string; step?: OneItemExecutionProofStepName; message: string };
export type OneItemExecutionProofWarning = { code: string; step?: OneItemExecutionProofStepName; message: string };
export type OneItemExecutionProofSafetySummary = { internalOnly: true; proofOnly: true; oneItemOnly: true; publicPersistenceEnabled: false; productionIngestEnabled: false; publicReadEnabled: false; wouldCallModel: false; wouldEmbed: false; semanticRetrievalEnabled: false; appendOnly: true; rawUserIdExposed: false; rawIdempotencyKeyExposed: false; memoryTextExposed: false; evidenceExposed: false; serviceRoleExposed: false; rawErrorsExposed: false };
export const oneItemExecutionProofSafetySummary: OneItemExecutionProofSafetySummary = { internalOnly: true, proofOnly: true, oneItemOnly: true, publicPersistenceEnabled: false, productionIngestEnabled: false, publicReadEnabled: false, wouldCallModel: false, wouldEmbed: false, semanticRetrievalEnabled: false, appendOnly: true, rawUserIdExposed: false, rawIdempotencyKeyExposed: false, memoryTextExposed: false, evidenceExposed: false, serviceRoleExposed: false, rawErrorsExposed: false };
export type OneItemExecutionProofReadbackSummary = { status: "verified" | "blocked"; memoryItemId?: string; sourceId?: string; patchCount: number };
export type OneItemExecutionProofAuditSummary = { status: "verified" | "blocked"; auditEventCount: number; appendOnly: boolean };
export type OneItemExecutionProofBrowserSummary = { status: "visible" | "blocked"; memoryItemVisible: boolean; sourceVisible: boolean; patchVisible: boolean };
export type OneItemExecutionProofReceipt = { proofId: string; namespace: MemoryNamespace; workflowReceiptFingerprint: string; memoryItemId: string; sourceId?: string; proofTimestamp: string; safety: OneItemExecutionProofSafetySummary };
export type OneItemExecutionProofReport = { proofId: string; namespace: MemoryNamespace; serverUserFingerprint: string; workflowReceiptFingerprint: string; reviewItemId: string; decisionId: string; memoryItemId: string; sourceId?: string; patchCount: number; auditEventCount: number; previewFingerprint: string; idempotencyFingerprint: string; readbackStatus: "verified" | "blocked"; browserVisibilityStatus: "verified" | "blocked"; auditVerificationStatus: "verified" | "blocked"; appendOnlyVerificationStatus: "verified" | "blocked"; proofTimestamp: string; safety: OneItemExecutionProofSafetySummary };
export type OneItemExecutionProofInput = { sessionResult?: PandoraServerSessionResult; runtime?: PandoraRuntimeSafetyConfigResult; namespace?: MemoryNamespace; allowedNamespaces?: MemoryNamespace[]; operatorCapability?: boolean; clientUserId?: string; client_user_id?: string; userId?: string; user_id?: string; liveWorkflowReceipt?: LiveOneReviewedItemWorkflowReceipt & { executed?: boolean }; receiptId?: string; expectSource?: boolean; persistedMemoryReadRepository?: { getMemoryItemDetail?: (id: string) => Promise<unknown>; getMemorySource?: (id: string) => Promise<unknown>; listMemoryPatches?: (id: string) => Promise<unknown> }; auditRepository?: { listAuditEvents?: (id: string) => Promise<unknown> }; browserLoader?: (input: { namespace: MemoryNamespace; memoryItemId: string; sourceId?: string }) => Promise<unknown> };
export type OneItemExecutionProofResult = { ok: boolean; proofOnly: true; safety: OneItemExecutionProofSafetySummary; steps: OneItemExecutionProofStep[]; blockers: OneItemExecutionProofBlocker[]; warnings: OneItemExecutionProofWarning[]; receipt?: OneItemExecutionProofReceipt; report?: OneItemExecutionProofReport };
