import type { PandoraRuntimeSafetyConfigResult } from "@/lib/config/pandora-runtime-safety-config";
import type { PersistedMemoryNamespace } from "@/lib/services/persisted-memory-read-contract";

export type OperatorLiveDryRunStepName = "server_session_resolved" | "runtime_gates_resolved" | "environment_safety_snapshot_built" | "namespace_validated" | "persisted_read_api_readiness_checked" | "memory_browser_readiness_checked" | "admin_persistence_console_gate_checked" | "operator_qa_flow_gate_checked" | "audit_idempotency_requirements_checked" | "final_dry_run_report_produced";
export const operatorLiveDryRunStepNames: OperatorLiveDryRunStepName[] = ["server_session_resolved", "runtime_gates_resolved", "environment_safety_snapshot_built", "namespace_validated", "persisted_read_api_readiness_checked", "memory_browser_readiness_checked", "admin_persistence_console_gate_checked", "operator_qa_flow_gate_checked", "audit_idempotency_requirements_checked", "final_dry_run_report_produced"];
export type OperatorLiveDryRunStep = { name: OperatorLiveDryRunStepName; status: "passed" | "blocked" | "warning" | "pending"; message?: string };
export type OperatorLiveDryRunBlocker = { code: string; step?: OperatorLiveDryRunStepName; message: string };
export type OperatorLiveDryRunWarning = { code: string; step?: OperatorLiveDryRunStepName; message: string };
export type OperatorLiveDryRunSafetySummary = { dryRunOnly: true; wouldWriteMemory: false; wouldPersistMemory: false; wouldCallModel: false; wouldEmbed: false; semanticRetrievalEnabled: false; publicPersistenceEnabled: false; publicIngestEnabled: false; publicReadEnabled: false; serviceRoleExposed: false };
export const operatorLiveDryRunSafety: OperatorLiveDryRunSafetySummary = { dryRunOnly: true, wouldWriteMemory: false, wouldPersistMemory: false, wouldCallModel: false, wouldEmbed: false, semanticRetrievalEnabled: false, publicPersistenceEnabled: false, publicIngestEnabled: false, publicReadEnabled: false, serviceRoleExposed: false };
export type OperatorLiveDryRunGateSummary = { runtime?: PandoraRuntimeSafetyConfigResult["gates"]; persistedMemoryReadEnabled: boolean; adminPersistenceConsoleEnabled: boolean; approvedReviewPersistenceEnabled: boolean; operatorQaFlowEnabled: boolean; dangerousGatesDisabled: boolean };
export type OperatorLiveDryRunNamespaceSummary = { namespace?: PersistedMemoryNamespace; validated: boolean; allowed: boolean; requiresExplicitNamespace: true; auStoryMemoryIsNotRealLifeEvidence: true; realLifeMemoryRequiresFictionalizedReviewForAu: true };
export type OperatorLiveDryRunReadApiSummary = { status: "not_checked" | "ready_empty" | "ready_with_data" | "blocked"; itemCount: number; detailChecked: boolean; sourcesChecked: boolean; patchesChecked: boolean; auditChecked: boolean; readOnly: true };
export type OperatorLiveDryRunBrowserSummary = { status: "not_checked" | "ready_empty" | "ready_with_data" | "blocked"; itemCount: number; readOnly: true };
export type OperatorLiveDryRunQaSummary = { adminPersistenceConsoleGateVisible: boolean; operatorQaFlowGateEnabled: boolean; executionDisabledByDefault: true; persistenceExecutorCalled: false; previewExecutorCalled: false; ingestCalled: false };
export type OperatorLiveDryRunInput = { namespace?: string | null; requestId?: string; user_id?: string; userId?: string; client_user_id?: string; clientUserId?: string };
export type OperatorLiveDryRunResult = { ok: boolean; readyForFirstManualUse: boolean; namespace?: PersistedMemoryNamespace; steps: OperatorLiveDryRunStep[]; blockers: OperatorLiveDryRunBlocker[]; warnings: OperatorLiveDryRunWarning[]; safety: OperatorLiveDryRunSafetySummary; gates: OperatorLiveDryRunGateSummary; namespaceSummary: OperatorLiveDryRunNamespaceSummary; readApi: OperatorLiveDryRunReadApiSummary; browser: OperatorLiveDryRunBrowserSummary; qa: OperatorLiveDryRunQaSummary; auditIdempotency: { auditRequired: true; idempotencyRequired: true; appendOnly: true; checked: boolean }; environment?: unknown; checklist?: unknown; secretsRedacted: true };
