import type { MemoryReviewQueueRepository, ReviewQueueDecisionRecord } from "@/lib/db/memory-review-queue-repository-contract";
import type { ApprovedReviewMemoryPersistenceExecutorResult } from "@/lib/services/approved-review-memory-persistence-executor-contract";
import type { ApprovedReviewPersistencePreviewResult } from "@/lib/services/approved-review-memory-persistence-preview-contract";
import type { PersistedMemoryReadRepository } from "@/lib/db/persisted-memory-read-repository-contract";
import type { PersistedMemoryBrowserViewModel } from "@/lib/api/persisted-memory-browser-dto";
import { operatorMemoryQaSafety, operatorMemoryQaStepNames, type OperatorMemoryQaFlowInput, type OperatorMemoryQaFlowResult, type OperatorMemoryQaFlowStepName } from "@/lib/services/operator-memory-qa-flow-contract";
import { verifyOperatorMemoryReadback } from "@/lib/services/operator-memory-readback-verifier";

export type OperatorMemoryQaFlowRunnerInput = OperatorMemoryQaFlowInput & { reviewRepository: MemoryReviewQueueRepository & { readReviewDecisionById?: (context: NonNullable<OperatorMemoryQaFlowInput["context"]>, id: string) => Promise<{ ok: true; data: ReviewQueueDecisionRecord } | { ok: false; error?: unknown }> }; previewService: (input: { context: NonNullable<OperatorMemoryQaFlowInput["context"]>; items: unknown[] }) => ApprovedReviewPersistencePreviewResult; persistenceExecutor: (input: Record<string, unknown>) => Promise<ApprovedReviewMemoryPersistenceExecutorResult>; persistedMemoryReadRepository: PersistedMemoryReadRepository; browserLoader: (input: Record<string, unknown>) => Promise<PersistedMemoryBrowserViewModel> };
const fp = (v: string) => `${v.slice(0, 8)}:${v.length}`;
function blocked(input: OperatorMemoryQaFlowInput, step: OperatorMemoryQaFlowStepName, code: string, message: string, previous: OperatorMemoryQaFlowStepName[] = []): OperatorMemoryQaFlowResult { return { ...operatorMemoryQaSafety, ok: false, executed: false, namespace: input.namespace, reviewItemId: input.reviewItemId, decisionId: input.decisionId, idempotencyKeyFingerprint: input.idempotencyKey ? fp(input.idempotencyKey) : undefined, steps: operatorMemoryQaStepNames.map((name) => ({ name, status: previous.includes(name) ? "passed" : name === step ? "blocked" : "pending", message: name === step ? message : undefined })), blockers: [{ code, step, message }], warnings: [] }; }
export async function runOperatorMemoryQaFlow(input: OperatorMemoryQaFlowRunnerInput): Promise<OperatorMemoryQaFlowResult> {
  const passed: OperatorMemoryQaFlowStepName[] = [];
  if (!input.context?.userId) return blocked(input, "review_item_loaded", "missing_auth_context", "Server auth context is required.");
  if (!input.namespace || input.context.namespace !== input.namespace) return blocked(input, "review_item_loaded", "missing_or_mismatched_namespace", "Namespace must match repository context.");
  if (input.clientUserId || input.client_user_id || input.userId || input.user_id) return blocked(input, "review_item_loaded", "client_user_id_rejected", "Client-supplied user_id/userId is rejected.");
  if (!input.reviewItemId) return blocked(input, "review_item_loaded", "missing_review_item_id", "Review item id is required.");
  if (!input.decisionId) return blocked(input, "decision_verified", "missing_decision_id", "Decision id is required.");
  if (!input.idempotencyKey) return blocked(input, "persistence_executed", "missing_idempotency_key", "Idempotency key is required.");
  const itemResult = await input.reviewRepository.readReviewQueueItemById(input.context, input.reviewItemId);
  if (!itemResult.ok) return blocked(input, "review_item_loaded", "review_item_not_found", "Review item could not be loaded.");
  const item = itemResult.data; if (item.status !== "approved_for_append") return blocked(input, "review_item_loaded", "review_item_not_approved", "Review item must be approved_for_append."); passed.push("review_item_loaded");
  let decision: ReviewQueueDecisionRecord | undefined; if (input.reviewRepository.readReviewDecisionById) { const d = await input.reviewRepository.readReviewDecisionById(input.context, input.decisionId); if (d.ok) decision = d.data; }
  decision ??= (item.audit.decisionTrail.some((d) => d.action === "approve_append") ? { id: input.decisionId, itemId: item.id, userId: input.context.userId, namespace: input.namespace, action: "approve_append", createdAt: item.updatedAt, audit: {} } : undefined);
  if (!decision) return blocked(input, "decision_verified", "decision_not_found", "Append-only review decision is required.", passed);
  if (decision.action !== "approve_append" || decision.itemId !== item.id) return blocked(input, "decision_verified", "non_append_decision", "Decision must be append-only approve_append for this review item.", passed); passed.push("decision_verified");
  const preview = input.previewService({ context: input.context, items: [item] }); const plan = preview.plans.find((p) => p.itemId === item.id);
  if (!preview.ok || !plan?.eligible) return blocked(input, "preview_plan_built", "preview_blocked", "Persistence preview plan was not eligible.", passed); passed.push("preview_plan_built", "internal_gate_checked");
  const exec = await input.persistenceExecutor({ context: input.context, item, preview, plan, idempotencyKey: input.idempotencyKey, fingerprint: input.previewFingerprint ?? item.audit.fingerprint ?? item.updatedAt });
  if (!exec.executed) return blocked(input, "persistence_executed", "persistence_not_executed", "Injected persistence executor did not execute.", passed); passed.push("persistence_executed");
  const readCtx = { userId: input.context.userId, namespace: input.namespace };
  const detail = await input.persistedMemoryReadRepository.getMemoryItemDetail(readCtx, { namespace: input.namespace, id: exec.item?.id ?? "" });
  if (!detail.ok) return blocked(input, "memory_item_read_back", "memory_item_readback_failed", "Persisted memory item readback failed.", passed); passed.push("memory_item_read_back");
  const [sources, patches, auditEvents] = await Promise.all([input.persistedMemoryReadRepository.listMemorySources(readCtx, { namespace: input.namespace, filter: { itemId: detail.item.id } }), input.persistedMemoryReadRepository.listMemoryPatches(readCtx, { namespace: input.namespace, filter: { itemId: detail.item.id } }), input.persistedMemoryReadRepository.listMemoryAuditEvents(readCtx, { namespace: input.namespace, filter: { itemId: detail.item.id } })]);
  const verify = verifyOperatorMemoryReadback({ userId: input.context.userId, namespace: input.namespace, reviewItemId: input.reviewItemId, decisionId: input.decisionId, idempotencyKey: input.idempotencyKey, previewFingerprint: exec.fingerprint ?? input.previewFingerprint ?? item.updatedAt, item: detail.item, sources: sources.ok ? sources.items : [], patches: patches.ok ? patches.items : [], auditEvents: auditEvents.ok ? auditEvents.items : [], plannedPatch: true });
  if (!verify.ok) return { ...blocked(input, "source_patch_audit_read_back", verify.blockers[0].code, verify.blockers[0].message, passed), blockers: verify.blockers, warnings: verify.warnings }; passed.push("source_patch_audit_read_back");
  const browser = await input.browserLoader({ context: readCtx, repository: input.persistedMemoryReadRepository, selectedItemId: detail.item.id, filters: { namespace: input.namespace } });
  if (!browser.items.some((i) => i.id === detail.item.id)) return blocked(input, "browser_view_model_verified", "browser_item_not_visible", "Browser view model could not see the persisted item.", passed); passed.push("browser_view_model_verified");
  return { ...operatorMemoryQaSafety, ok: true, executed: true, namespace: input.namespace, reviewItemId: input.reviewItemId, decisionId: input.decisionId, idempotencyKeyFingerprint: fp(input.idempotencyKey), steps: operatorMemoryQaStepNames.map((name) => ({ name, status: "passed" })), blockers: [], warnings: verify.warnings, readback: { itemId: detail.item.id, sourceId: sources.ok ? sources.items[0]?.id : undefined, patchId: patches.ok ? patches.items[0]?.id : undefined, auditEventId: auditEvents.ok ? auditEvents.items[0]?.id : undefined, auditSummaryExists: true, browserVisible: true, namespace: input.namespace, reviewItemId: input.reviewItemId, decisionId: input.decisionId, idempotencyKeyFingerprint: fp(input.idempotencyKey), previewFingerprint: exec.fingerprint ?? input.previewFingerprint ?? item.updatedAt } };
}
