import type { MemoryReviewQueueRepository, ReviewQueueDecisionRecord } from "@/lib/db/memory-review-queue-repository-contract";
import type { PersistedMemoryReadRepository } from "@/lib/db/persisted-memory-read-repository-contract";
import type { ApprovedReviewMemoryPersistenceExecutorResult } from "@/lib/services/approved-review-memory-persistence-executor-contract";
import type { ApprovedReviewPersistencePreviewResult } from "@/lib/services/approved-review-memory-persistence-preview-contract";
import { operatorManualMemoryWorkflowSafetySummary, operatorManualMemoryWorkflowStepNames, type OperatorManualMemoryWorkflowInput, type OperatorManualMemoryWorkflowResult } from "@/lib/services/operator-manual-memory-workflow-contract";
import { validateOperatorManualMemoryWorkflowPreflight } from "@/lib/services/operator-manual-memory-workflow-preflight";
import { buildOperatorManualMemoryWorkflowReceipt, fingerprintOperatorManualValue } from "@/lib/services/operator-manual-memory-workflow-receipt";
import { verifyOperatorMemoryReadback } from "@/lib/services/operator-memory-readback-verifier";

export type OperatorManualMemoryWorkflowRunnerInput = OperatorManualMemoryWorkflowInput & { reviewRepository: MemoryReviewQueueRepository & { readReviewDecisionById?: (context: NonNullable<OperatorManualMemoryWorkflowInput["context"]>, id: string) => Promise<{ ok: true; data: ReviewQueueDecisionRecord } | { ok: false; error?: unknown }> }; previewService: (input: Record<string, unknown>) => ApprovedReviewPersistencePreviewResult; approvedReviewPersistenceExecutor: (input: Record<string, unknown>) => Promise<ApprovedReviewMemoryPersistenceExecutorResult>; persistedMemoryReadRepository: PersistedMemoryReadRepository; browserLoader: (input: Record<string, unknown>) => Promise<{ items: { id: string }[] }>; readbackVerifier?: typeof verifyOperatorMemoryReadback; receiptBuilder?: typeof buildOperatorManualMemoryWorkflowReceipt };
const blocked = (r: OperatorManualMemoryWorkflowResult): OperatorManualMemoryWorkflowResult => ({ ...r, steps: operatorManualMemoryWorkflowStepNames.map((name) => ({ name, status: r.blockers.some((b) => b.step === name) ? "blocked" : "pending", message: r.blockers.find((b) => b.step === name)?.message })) });
export async function runOperatorManualMemoryWorkflow(input: OperatorManualMemoryWorkflowRunnerInput): Promise<OperatorManualMemoryWorkflowResult> {
  if (!input.context?.userId || !input.namespace) return blocked(validateOperatorManualMemoryWorkflowPreflight(input));
  const itemResult = input.reviewItemId ? await input.reviewRepository.readReviewQueueItemById(input.context, input.reviewItemId) : { ok: false } as const;
  const item = itemResult.ok ? itemResult.data : null;
  let decision: ReviewQueueDecisionRecord | null = null;
  if (input.decisionId && input.reviewRepository.readReviewDecisionById) { const d = await input.reviewRepository.readReviewDecisionById(input.context, input.decisionId); if (d.ok) decision = d.data; }
  decision ??= item && item.audit.decisionTrail.some((d) => d.action === "approve_append") && input.decisionId ? { id: input.decisionId, itemId: item.id, userId: input.context.userId, namespace: input.namespace, action: "approve_append", createdAt: item.updatedAt, audit: {} } : null;
  const preview = item ? input.previewService({ context: input.context, items: [item] }) : undefined;
  const preflight = validateOperatorManualMemoryWorkflowPreflight({ ...input, reviewItem: item, decision, preview });
  if (!preflight.ok || !item || !preview) return blocked(preflight);
  const plan = preview.plans.find((p) => p.itemId === item.id);
  const exec = await input.approvedReviewPersistenceExecutor({ context: input.context, item, preview, plan, idempotencyKey: input.idempotencyKey, fingerprint: input.preview?.plans?.[0]?.itemId ?? item.audit.fingerprint ?? item.updatedAt });
  if (!exec.executed || !exec.item?.id) return blocked({ ...preflight, blockers: [{ code: "persistence_not_executed", step: "persistence_executed_through_approved_review_executor", message: "Injected approved-review executor did not execute." }] });
  const readCtx = { userId: input.context.userId, namespace: input.namespace };
  const [detail, sources, patches, auditEvents] = await Promise.all([input.persistedMemoryReadRepository.getMemoryItemDetail(readCtx, { namespace: input.namespace, id: exec.item.id }), input.persistedMemoryReadRepository.listMemorySources(readCtx, { namespace: input.namespace, filter: { itemId: exec.item.id } }), input.persistedMemoryReadRepository.listMemoryPatches(readCtx, { namespace: input.namespace, filter: { itemId: exec.item.id } }), input.persistedMemoryReadRepository.listMemoryAuditEvents(readCtx, { namespace: input.namespace, filter: { itemId: exec.item.id } })]);
  const previewFingerprint = exec.fingerprint ?? item.audit.fingerprint ?? item.updatedAt;
  const verify = (input.readbackVerifier ?? verifyOperatorMemoryReadback)({ userId: input.context.userId, namespace: input.namespace, reviewItemId: item.id, decisionId: input.decisionId!, idempotencyKey: input.idempotencyKey!, previewFingerprint, item: detail.ok ? detail.item : null, sources: sources.ok ? sources.items : [], patches: patches.ok ? patches.items : [], auditEvents: auditEvents.ok ? auditEvents.items : [], plannedPatch: true });
  if (!verify.ok || !detail.ok) return blocked({ ...preflight, blockers: verify.blockers.length ? verify.blockers as never : [{ code: "memory_readback_failed", step: "memory_readback_verified", message: "Memory readback failed." }] });
  const browser = await input.browserLoader({ context: readCtx, repository: input.persistedMemoryReadRepository, selectedItemId: exec.item.id, filters: { namespace: input.namespace } });
  if (!browser.items.some((i) => i.id === exec.item!.id)) return blocked({ ...preflight, blockers: [{ code: "browser_visibility_failed", step: "browser_visibility_verified", message: "Browser visibility verification failed." }] });
  const receipt = (input.receiptBuilder ?? buildOperatorManualMemoryWorkflowReceipt)({ namespace: input.namespace, serverUserId: input.context.userId, reviewItemId: item.id, decisionId: input.decisionId!, memoryItemId: exec.item.id, sourceId: exec.source?.id, patchIdsCount: exec.patch ? 1 : 0, auditEventIdsCount: exec.auditLog ? 1 : 0, idempotencyKey: input.idempotencyKey!, previewFingerprint, readbackStatus: "verified", browserVisibilityStatus: "verified", auditVerificationStatus: "verified" });
  return { ok: true, executed: true, safety: operatorManualMemoryWorkflowSafetySummary, steps: operatorManualMemoryWorkflowStepNames.map((name) => ({ name, status: "passed" })), blockers: [], warnings: verify.warnings.map((w) => ({ code: w.code, message: w.message })), preview: { ok: true, previewFingerprint: fingerprintOperatorManualValue(previewFingerprint), plannedSources: preview.summary.plannedSources, plannedItems: preview.summary.plannedItems, plannedPatches: preview.summary.plannedPatches, plannedAuditLogs: preview.summary.plannedAuditLogs }, execution: { executed: true, memoryItemId: exec.item.id, sourceId: exec.source?.id, patchIdsCount: exec.patch ? 1 : 0, auditEventIdsCount: exec.auditLog ? 1 : 0, executedAt: receipt.executionTimestamp }, readback: { ok: true, memoryItemId: exec.item.id, readbackStatus: "verified", browserVisibilityStatus: "verified", auditVerificationStatus: "verified" }, receipt };
}
