import type { PersistedMemoryReadRepository } from "@/lib/db/persisted-memory-read-repository-contract";
import type { PandoraServerSessionResult } from "@/lib/auth/pandora-server-session-contract";
import { createRepositoryContextFromPandoraSession } from "@/lib/auth/pandora-server-session-resolver";
import { resolvePandoraRuntimeSafetyConfig, type PandoraRuntimeSafetyConfigResult } from "@/lib/config/pandora-runtime-safety-config";
import { buildPandoraEnvironmentSafetySnapshot } from "@/lib/config/pandora-environment-safety-snapshot";
import { buildOperatorReadinessResult } from "@/lib/services/operator-readiness-contract";
import { probePersistedMemoryReadApis } from "@/lib/services/operator-read-api-probe";
import { operatorLiveDryRunSafety, operatorLiveDryRunStepNames, type OperatorLiveDryRunInput, type OperatorLiveDryRunResult, type OperatorLiveDryRunBlocker, type OperatorLiveDryRunWarning, type OperatorLiveDryRunReadApiSummary, type OperatorLiveDryRunBrowserSummary } from "@/lib/services/operator-live-dry-run-contract";
import type { PersistedMemoryBrowserViewModel } from "@/lib/api/persisted-memory-browser-dto";

export type OperatorLiveDryRunRunnerDependencies = { serverSessionResolver: () => Promise<PandoraServerSessionResult>; runtimeSafetyConfigResolver?: () => PandoraRuntimeSafetyConfigResult; environmentSafetySnapshotBuilder?: () => unknown; operatorReadinessBuilder?: (input: { runtime: PandoraRuntimeSafetyConfigResult; sessionResult?: PandoraServerSessionResult }) => unknown; readRepository?: PersistedMemoryReadRepository; readApiProbe?: typeof probePersistedMemoryReadApis; browserLoader?: (input: Record<string, unknown>) => Promise<PersistedMemoryBrowserViewModel>; deploymentChecklistGenerator?: () => unknown; persistenceExecutor?: never; previewExecutor?: never; ingest?: never };
const isNs = (v?: string | null): v is "real_life" | "au" => v === "real_life" || v === "au";
export async function runOperatorLiveDryRun(input: OperatorLiveDryRunInput & OperatorLiveDryRunRunnerDependencies): Promise<OperatorLiveDryRunResult> {
  const blockers: OperatorLiveDryRunBlocker[] = []; const warnings: OperatorLiveDryRunWarning[] = []; const passed = new Set<string>();
  const addBlock = (code: string, message: string, step?: OperatorLiveDryRunBlocker["step"]) => blockers.push({ code, message, step });
  if (input.user_id || input.userId || input.client_user_id || input.clientUserId) addBlock("client_user_id_rejected", "Client-supplied user_id/userId is rejected.", "server_session_resolved");
  let sessionResult: PandoraServerSessionResult | undefined; try { sessionResult = await input.serverSessionResolver(); } catch { addBlock("session_resolver_failed", "Server session resolver failed safely.", "server_session_resolved"); }
  if (sessionResult?.ok) passed.add("server_session_resolved"); else addBlock("auth_required", "Authenticated server session is required.", "server_session_resolved");
  const runtime = input.runtimeSafetyConfigResolver?.() ?? resolvePandoraRuntimeSafetyConfig(); passed.add("runtime_gates_resolved");
  const env = input.environmentSafetySnapshotBuilder?.() ?? buildPandoraEnvironmentSafetySnapshot(process.env); passed.add("environment_safety_snapshot_built");
  if (!isNs(input.namespace)) addBlock("namespace_required", "Explicit namespace is required.", "namespace_validated");
  const ctx = sessionResult ? createRepositoryContextFromPandoraSession({ sessionResult, namespace: input.namespace }) : null;
  if (ctx?.ok) passed.add("namespace_validated"); else if (sessionResult?.ok) addBlock("namespace_not_allowed", "Namespace is unavailable for this server session.", "namespace_validated");
  if (runtime.config.ingestProductionWriteEnabled) addBlock("public_ingest_enabled", "Production ingest writes must remain disabled.", "runtime_gates_resolved");
  if (runtime.config.publicMemoryPersistenceEnabled) addBlock("public_persistence_enabled", "Public memory persistence must remain disabled.", "runtime_gates_resolved");
  if (runtime.config.publicMemoryReadEnabled) addBlock("public_read_enabled", "Public unauthenticated memory reads must remain disabled.", "runtime_gates_resolved");
  if (runtime.config.modelCallsEnabled || runtime.config.embeddingsEnabled || runtime.config.semanticRetrievalEnabled || runtime.config.gptActionsEnabled || runtime.config.mcpEnabled) addBlock("dangerous_feature_enabled", "Model/retrieval/vector/GPT Action/MCP gates must remain disabled.", "runtime_gates_resolved");
  let readApi: OperatorLiveDryRunReadApiSummary = { status: "not_checked", itemCount: 0, detailChecked: false, sourcesChecked: false, patchesChecked: false, auditChecked: false, readOnly: true };
  if (ctx?.ok) { const probe = await (input.readApiProbe ?? probePersistedMemoryReadApis)({ context: ctx.context, namespace: input.namespace, repository: input.readRepository }); readApi = probe.summary; blockers.push(...probe.blockers); warnings.push(...probe.warnings); if (probe.ok) passed.add("persisted_read_api_readiness_checked"); }
  let browser: OperatorLiveDryRunBrowserSummary = { status: "not_checked", itemCount: 0, readOnly: true };
  if (ctx?.ok && input.browserLoader) try { const b = await input.browserLoader({ context: ctx.context, authenticated: true, repository: input.readRepository, filters: { namespace: input.namespace }, readOnly: true }); browser = { status: b.blockers.length ? "blocked" : b.items.length ? "ready_with_data" : "ready_empty", itemCount: b.items.length, readOnly: true }; if (!b.blockers.length) passed.add("memory_browser_readiness_checked"); } catch { addBlock("browser_loader_failed", "Read-only browser loader failed safely.", "memory_browser_readiness_checked"); browser = { status: "blocked", itemCount: 0, readOnly: true }; }
  passed.add("admin_persistence_console_gate_checked"); passed.add("operator_qa_flow_gate_checked"); passed.add("audit_idempotency_requirements_checked"); passed.add("final_dry_run_report_produced");
  const checklist = input.deploymentChecklistGenerator?.(); const readiness = input.operatorReadinessBuilder?.({ runtime, sessionResult }) ?? buildOperatorReadinessResult({ runtime, sessionResult });
  const dangerousGatesDisabled = !runtime.config.ingestProductionWriteEnabled && !runtime.config.publicMemoryReadEnabled && !runtime.config.publicMemoryPersistenceEnabled && !runtime.config.modelCallsEnabled && !runtime.config.embeddingsEnabled && !runtime.config.semanticRetrievalEnabled && !runtime.config.gptActionsEnabled && !runtime.config.mcpEnabled;
  return { ok: blockers.length === 0, readyForFirstManualUse: blockers.length === 0 && (readApi.status === "ready_empty" || readApi.status === "ready_with_data"), namespace: isNs(input.namespace) ? input.namespace : undefined, steps: operatorLiveDryRunStepNames.map((name) => ({ name, status: blockers.some((b) => b.step === name) ? "blocked" : passed.has(name) ? "passed" : "pending" })), blockers, warnings, safety: operatorLiveDryRunSafety, gates: { runtime: runtime.gates, persistedMemoryReadEnabled: runtime.config.persistedMemoryReadEnabled, adminPersistenceConsoleEnabled: runtime.config.adminPersistenceConsoleEnabled, approvedReviewPersistenceEnabled: runtime.config.approvedReviewPersistenceEnabled, operatorQaFlowEnabled: runtime.config.operatorQaFlowEnabled, dangerousGatesDisabled }, namespaceSummary: { namespace: isNs(input.namespace) ? input.namespace : undefined, validated: !!ctx?.ok, allowed: !!ctx?.ok, requiresExplicitNamespace: true, auStoryMemoryIsNotRealLifeEvidence: true, realLifeMemoryRequiresFictionalizedReviewForAu: true }, readApi, browser, qa: { adminPersistenceConsoleGateVisible: runtime.config.adminPersistenceConsoleEnabled, operatorQaFlowGateEnabled: runtime.config.operatorQaFlowEnabled, executionDisabledByDefault: true, persistenceExecutorCalled: false, previewExecutorCalled: false, ingestCalled: false }, auditIdempotency: { auditRequired: true, idempotencyRequired: true, appendOnly: true, checked: true }, environment: env, checklist: checklist ?? readiness, secretsRedacted: true };
}
