import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { MemoryBridgeDbClient } from "@/lib/services/memory-bridge-service";
import type { PandoraMcpPrincipal } from "@/lib/services/mcp-auth";
import { adaptiveTurnTool, analyzeMemoryCandidatesTool, captureAdaptiveMemoryTool, captureMemoryEventTool, createSessionDigestTool, distillContextPackTool, getAdaptiveContextTool, getLatestContextPackTool, getMemoryContextTool, getOpenLoopsTool, refreshAdaptiveProfilesTool, semanticMemorySearchTool } from "@/lib/services/pandora-mcp-tools";
import { runMcpAction } from "@/lib/services/pandora-mcp-action-envelope";

export function createPandoraMcpServer(input: { client: MemoryBridgeDbClient; principal: Extract<PandoraMcpPrincipal, { ok: true }>; env?: Partial<NodeJS.ProcessEnv> }) {
  const { client, principal, env } = input;
  const server = new McpServer({ name: "pandora-memory", version: "4.0.0" });
  // Context reads fall back to the latest active context pack if the primary path fails, so the
  // action returns a controlled envelope (fallback_used=true) instead of stream-breaking.
  const latestPackFallback = (args: unknown) => () => getLatestContextPackTool(client, principal, args);

  server.registerTool("get_latest_context_pack", { title: "Get latest context pack", description: "Return the latest active Pandora context pack for a namespace and optional pack type.", inputSchema: { namespace: z.enum(["real_life", "au"]), pack_type: z.enum(["daily", "master"]).optional() } }, async (args: unknown) => runMcpAction(() => getLatestContextPackTool(client, principal, args)));
  server.registerTool("get_memory_context", { title: "Get memory context", description: "Return compact Pandora memory context for a current ChatGPT task.", inputSchema: { namespace: z.enum(["real_life", "au"]), query: z.string().optional(), current_task: z.string().optional(), max_items: z.number().int().positive().optional(), include_risks: z.boolean().optional(), include_people: z.boolean().optional(), include_projects: z.boolean().optional() } }, async (args: unknown) => runMcpAction(() => getMemoryContextTool(client, principal, args), { fallback: latestPackFallback(args) }));
  server.registerTool("capture_memory_event", { title: "Capture memory event", description: "Capture a reviewable Pandora memory event from ChatGPT/MCP. Disabled unless PANDORA_ENABLE_MCP_CAPTURE=true.", inputSchema: { namespace: z.enum(["real_life", "au"]), raw_text: z.string().min(1).max(8000), source: z.string().optional(), source_ref: z.string().optional(), importance: z.number().int().min(1).max(10).optional(), sensitivity: z.enum(["low", "medium", "high", "private"]).optional() } }, async (args: unknown) => runMcpAction(() => captureMemoryEventTool(client, principal, args, env)));
  server.registerTool("distill_context_pack", { title: "Distill context pack", description: "Generate deterministic Pandora context pack without model calls or embeddings. Disabled unless PANDORA_ENABLE_MCP_DISTILLATION=true.", inputSchema: { namespace: z.enum(["real_life", "au"]), pack_type: z.enum(["daily", "master"]) } }, async (args: unknown) => runMcpAction(() => distillContextPackTool(client, principal, args, env)));

  server.registerTool("adaptive_turn", { title: "Adaptive turn", description: "Phase 5A autopilot: pre-answer auto-retrieval and post-answer candidate queueing with gated writes.", inputSchema: { namespace: z.enum(["real_life", "au"]).optional(), user_message: z.string(), assistant_draft: z.string().optional(), current_task: z.string().optional(), conversation_type: z.string().optional(), mode: z.enum(["pre_answer", "post_answer"]) } }, async (args: unknown) => runMcpAction(() => adaptiveTurnTool(client, principal, args, env)));
  server.registerTool("get_adaptive_context", { title: "Get adaptive context", description: "Return the best adaptive context for ChatGPT before answering Joven.", inputSchema: { namespace: z.enum(["real_life", "au"]), query: z.string().optional(), current_task: z.string().optional(), max_items: z.number().int().positive().optional() } }, async (args: unknown) => runMcpAction(() => getAdaptiveContextTool(client, principal, args), { fallback: latestPackFallback(args) }));
  server.registerTool("analyze_memory_candidates", { title: "Analyze memory candidates", description: "Identify what should be saved, reviewed, ignored, or blocked.", inputSchema: { namespace: z.enum(["real_life", "au"]), text: z.string(), source: z.string().optional(), source_ref: z.string().optional(), mode: z.enum(["candidate_only","auto_capture_allowed"]).optional() } }, async (args: unknown) => runMcpAction(() => analyzeMemoryCandidatesTool(client, principal, args, env)));
  server.registerTool("capture_adaptive_memory", { title: "Capture adaptive memory", description: "Capture high-signal durable memory using adaptive policy.", inputSchema: { namespace: z.enum(["real_life", "au"]), text: z.string(), source: z.string().optional(), source_ref: z.string().optional(), mode: z.enum(["candidate_only","auto_capture_allowed"]).optional() } }, async (args: unknown) => runMcpAction(() => captureAdaptiveMemoryTool(client, principal, args, env)));
  server.registerTool("semantic_memory_search", { title: "Semantic memory search", description: "Hybrid retrieval with semantic matches when enabled.", inputSchema: { namespace: z.enum(["real_life", "au"]), query: z.string().optional(), current_task: z.string().optional(), max_items: z.number().int().positive().optional() } }, async (args: unknown) => runMcpAction(() => semanticMemorySearchTool(client, principal, args)));
  server.registerTool("create_session_digest", { title: "Create session digest", description: "Digest a session into candidates, events, profiles, and open loops.", inputSchema: { namespace: z.enum(["real_life", "au"]), source: z.string().optional(), source_ref: z.string().optional(), transcript_or_summary: z.string(), auto_capture: z.boolean().optional(), update_profiles: z.boolean().optional(), distill: z.boolean().optional() } }, async (args: unknown) => runMcpAction(() => createSessionDigestTool(client, principal, args, env)));
  server.registerTool("refresh_adaptive_profiles", { title: "Refresh adaptive profiles", description: "Update adaptive profiles from existing memory.", inputSchema: { namespace: z.enum(["real_life", "au"]), profile_types: z.array(z.string()).optional(), subject_keys: z.array(z.string()).optional(), dry_run: z.boolean().optional() } }, async (args: unknown) => runMcpAction(() => refreshAdaptiveProfilesTool(client, principal, args, env)));
  server.registerTool("get_open_loops", { title: "Get open loops", description: "Return unresolved risks, blockers, decisions, and loops.", inputSchema: { namespace: z.enum(["real_life", "au"]) } }, async (args: unknown) => runMcpAction(() => getOpenLoopsTool(client, principal, args)));
  return server;
}
