/* eslint-disable @typescript-eslint/no-explicit-any */
import { randomUUID } from "node:crypto";
import type { PandoraNamespace, ShadowContextPackStatus } from "@/components/pandora/types";

export type ShadowContextPackDbClient = { from: (table: string) => any };
export type ShadowContextPackRow = { id: string; user_id: string; request_id: string; operator_action_id?: string | null; namespace: PandoraNamespace; pack_type: string; status: ShadowContextPackStatus; title: string; summary: string; source_window: Record<string, unknown>; candidate_payload: Record<string, unknown>; evidence: Record<string, unknown>; warnings: string[]; created_at: string; updated_at: string; reviewed_at?: string | null; rejected_at?: string | null; archived_at?: string | null };
export type ShadowContextPackEventRow = { id: string; shadow_pack_id: string; user_id: string; event_type: string; message: string; metadata: Record<string, unknown>; created_at: string };
const NAMESPACES = new Set(["real_life", "au"]); const STATUSES = new Set(["draft", "ready_for_review", "reviewed", "rejected", "archived"]);
function assertNamespace(namespace: string): asserts namespace is PandoraNamespace { if (!NAMESPACES.has(namespace)) throw new Error(`Unsupported Pandora namespace: ${namespace}`); }
function assertStatus(status: string): asserts status is ShadowContextPackStatus { if (!STATUSES.has(status)) throw new Error(`Unsupported shadow context pack status: ${status}`); }
async function safeRows(client: ShadowContextPackDbClient, table: string, userId: string, namespace: PandoraNamespace, limit: number, warnings: string[]) { try { const r = await client.from(table).select("*").eq("user_id", userId).eq("namespace", namespace).order("created_at", { ascending: false }).limit(limit); if (r.error) { warnings.push(`${table} unavailable for ${namespace}`); return []; } return Array.isArray(r.data) ? r.data : []; } catch { warnings.push(`${table} unavailable for ${namespace}`); return []; } }
function short(value: unknown) { return String(value ?? "").replace(/\s+/g, " ").trim().slice(0, 160); }
function eventSummary(row: any) { return short(row.extracted_summary || row.summary || row.raw_text || row.title || row.id); }
async function single(query: any) { const res = await query; if (res.error) return null; return Array.isArray(res.data) ? res.data[0] ?? null : res.data ?? null; }

export async function listShadowContextPacks(client: ShadowContextPackDbClient, input: { userId: string; namespace?: string; status?: string; limit?: number }): Promise<ShadowContextPackRow[]> { if (input.namespace) assertNamespace(input.namespace); if (input.status) assertStatus(input.status); let q = client.from("pandora_shadow_context_packs").select("*").eq("user_id", input.userId).order("created_at", { ascending: false }).limit(input.limit ?? 20); if (input.namespace) q = q.eq("namespace", input.namespace); if (input.status) q = q.eq("status", input.status); const r = await q; if (r.error) return []; return Array.isArray(r.data) ? r.data : []; }
export async function getShadowContextPack(client: ShadowContextPackDbClient, input: { userId: string; shadowPackId: string }): Promise<ShadowContextPackRow> { const row = await single(client.from("pandora_shadow_context_packs").select("*").eq("user_id", input.userId).eq("id", input.shadowPackId).limit(1)); if (!row) throw new Error("Shadow context pack not found for current user"); return row; }

export async function dryRunShadowContextPackCandidate(client: ShadowContextPackDbClient, input: { userId: string; namespace: string; sourceWindow?: Record<string, unknown> }) { assertNamespace(input.namespace); const warnings: string[] = []; const events = await safeRows(client, "memory_events", input.userId, input.namespace, 50, warnings); const packs = await safeRows(client, "memory_context_packs", input.userId, input.namespace, 10, warnings); const loops = await safeRows(client, "memory_open_loops", input.userId, input.namespace, 100, warnings); const review = await safeRows(client, "memory_review_queue_items", input.userId, input.namespace, 100, warnings); const active = packs.find((p:any)=>p.pack_type === "master" && p.status === "active"); const reviewed = events.filter((e:any)=>e.status === "reviewed").length; const promoted = events.filter((e:any)=>e.status === "promoted").length; const openLoopCount = loops.filter((l:any)=>["open","acknowledged"].includes(String(l.status ?? ""))).length; const needsReviewCount = review.filter((r:any)=>["pending_review","needs_clarification","pending"].includes(String(r.status ?? ""))).length; if (!active) warnings.push(`No active master context pack found for ${input.namespace}; readiness is not fabricated.`); if (events.length === 0) warnings.push(`No memory_events found for ${input.namespace}; candidate remains draft.`); const latest = events[0]?.created_at ?? null; const payload = { namespace: input.namespace, source_event_count: events.length, active_master_pack_id: active?.id ?? null, active_master_created_at: active?.created_at ?? null, latest_event_at: latest, reviewed_event_count: reviewed, promoted_event_count: promoted, open_loop_count: openLoopCount, needs_review_count: needsReviewCount, top_recent_summaries: events.slice(0,5).map(eventSummary), evidence_summary: `${events.length} namespace-scoped memory_events, ${openLoopCount} open loops, ${needsReviewCount} review items; no semantic retrieval or model scoring.` };
  const status: ShadowContextPackStatus = warnings.length || !active || events.length === 0 ? "draft" : "ready_for_review";
  return { status, title: `Shadow ${input.namespace} master candidate`, summary: `Shadow candidate for ${input.namespace}: ${events.length} events considered, ${openLoopCount} open loops, ${needsReviewCount} review items. Promotion is gated.`, source_window: input.sourceWindow ?? {}, candidate_payload: payload, evidence: { namespace: input.namespace, source_tables: ["memory_events", "memory_context_packs", "memory_open_loops", "memory_review_queue_items"], no_model_call: true, no_embeddings: true, no_promotion_performed: true }, warnings };
}
export async function createShadowContextPackEvent(client: ShadowContextPackDbClient, input: { userId: string; shadowPackId: string; eventType: string; message: string; metadata?: Record<string, unknown> }): Promise<ShadowContextPackEventRow | null> { const row = { id: randomUUID(), shadow_pack_id: input.shadowPackId, user_id: input.userId, event_type: input.eventType, message: input.message, metadata: input.metadata ?? {}, created_at: new Date().toISOString() }; return single(client.from("pandora_shadow_context_pack_events").insert(row).select("*").single()); }
export async function createShadowContextPackCandidate(client: ShadowContextPackDbClient, input: { userId: string; namespace: string; operatorActionId?: string | null; requestId: string; sourceWindow?: Record<string, unknown> }): Promise<ShadowContextPackRow> { const c = await dryRunShadowContextPackCandidate(client, { userId: input.userId, namespace: input.namespace, sourceWindow: input.sourceWindow }); const now = new Date().toISOString(); const row = { id: randomUUID(), user_id: input.userId, request_id: input.requestId, operator_action_id: input.operatorActionId ?? null, namespace: input.namespace, pack_type: "master_candidate", status: c.status, title: c.title, summary: c.summary, source_window: c.source_window, candidate_payload: c.candidate_payload, evidence: c.evidence, warnings: c.warnings, created_at: now, updated_at: now, reviewed_at: null, rejected_at: null, archived_at: null }; const created = await single(client.from("pandora_shadow_context_packs").insert(row).select("*").single()); if (!created) throw new Error("Unable to create shadow context pack candidate"); await createShadowContextPackEvent(client, { userId: input.userId, shadowPackId: created.id, eventType: "shadow_candidate_created", message: "Shadow context-pack candidate created. No production memory mutation or promotion performed.", metadata: { request_id: input.requestId, operator_action_id: input.operatorActionId ?? null, no_core_memory_mutation_performed: true, no_promotion_performed: true } }); return created; }
export async function updateShadowContextPackStatus(client: ShadowContextPackDbClient, input: { userId: string; shadowPackId: string; status: string; reason?: string }): Promise<ShadowContextPackRow> { assertStatus(input.status); await getShadowContextPack(client, input); const now = new Date().toISOString(); const patch: Record<string, unknown> = { status: input.status, updated_at: now }; if (input.status === "reviewed") patch.reviewed_at = now; if (input.status === "rejected") patch.rejected_at = now; if (input.status === "archived") patch.archived_at = now; const updated = await single(client.from("pandora_shadow_context_packs").update(patch).eq("user_id", input.userId).eq("id", input.shadowPackId).select("*").single()); if (!updated) throw new Error("Unable to update shadow context pack for current user"); await createShadowContextPackEvent(client, { userId: input.userId, shadowPackId: input.shadowPackId, eventType: `shadow_candidate_${input.status}`, message: input.reason ? `Shadow candidate marked ${input.status}: ${input.reason}` : `Shadow candidate marked ${input.status}. No promotion performed.`, metadata: { no_core_memory_mutation_performed: true, no_promotion_performed: true } }); return updated; }
