import type { PandoraNamespace } from "@/lib/supabase/database.types";

export type PersistedMemoryNamespace = PandoraNamespace;
export type PersistedMemoryReadContext = { userId: string; namespace: PersistedMemoryNamespace; includeFullText?: boolean; requestId?: string; clientUserId?: never; user_id?: never; userIdOverride?: never };
export type PersistedMemoryReadFilter = { sourceId?: string; itemId?: string; reviewItemId?: string; decisionId?: string; createdFrom?: string; createdTo?: string; memoryKind?: string; category?: string; keyword?: string; sourceType?: string; proofStatus?: string; clientUserId?: string; user_id?: string; userId?: string };
export type PersistedMemoryListRequest = { namespace: PersistedMemoryNamespace; page?: number; pageSize?: number; filter?: PersistedMemoryReadFilter; userId?: never; user_id?: never };
export type PersistedMemoryDetailRequest = { namespace: PersistedMemoryNamespace; id: string; itemId?: string; userId?: never; user_id?: never };
export type PersistedMemoryReadBlocker = { code: "auth_required" | "namespace_required" | "client_user_id_rejected" | "namespace_mismatch" | "not_found" | "read_error"; message: string };
export type PersistedMemoryReadWarning = { code: string; message: string };
export type PersistedMemorySafety = { readOnly: true; wouldWrite: false; wouldCallModel: false; wouldEmbed: false; semanticRetrievalEnabled: false; requiresAuth: true; namespaceScoped: true };
export const persistedMemoryReadSafety: PersistedMemorySafety = { readOnly: true, wouldWrite: false, wouldCallModel: false, wouldEmbed: false, semanticRetrievalEnabled: false, requiresAuth: true, namespaceScoped: true };
export type PersistedMemorySourceDto = PersistedMemorySafety & { id: string; userId?: never; namespace: PersistedMemoryNamespace | null; itemId?: string | null; sourceType?: string | null; sourceRef?: string | null; excerptPreview?: string | null; confidence?: number | null; createdAt?: string; reviewItemId?: string | null; decisionId?: string | null; sensitiveEvidenceRedacted: true };
export type PersistedMemoryItemDto = PersistedMemorySafety & { id: string; userId?: never; namespace: PersistedMemoryNamespace; memoryType?: string; category?: string | null; title?: string; textPreview?: string; fullText?: string; strength?: string; confidence?: number; canonStatus?: string; sourceSummary?: string | null; createdAt?: string; updatedAt?: string; reviewItemId?: string | null; decisionId?: string | null; sources?: PersistedMemorySourceDto[]; auditSummary?: string | null; sensitiveEvidenceRedacted: true; auStoryMemoryIsNotRealLifeEvidence: true };
export type PersistedMemoryPatchDto = PersistedMemorySafety & { id: string; namespace: PersistedMemoryNamespace; itemId: string; patchType?: string; reason?: string | null; beforePreview?: string | null; afterPreview?: string | null; createdAt?: string; sensitiveEvidenceRedacted: true };
export type PersistedMemoryAuditDto = PersistedMemorySafety & { id: string; namespace: PersistedMemoryNamespace | null; action: string; tableName?: string; recordId?: string | null; summary?: string; actorUserId?: string | null; sourceRef?: string | null; proofRef?: string | null; createdAt?: string; sensitiveEvidenceRedacted: true };
export type PersistedMemoryListResult<T = PersistedMemoryItemDto> = PersistedMemorySafety & { ok: true; items: T[]; page: number; pageSize: number; total?: number; warnings?: PersistedMemoryReadWarning[] } | { ok: false; blocker: PersistedMemoryReadBlocker };
export type PersistedMemoryDetailResult<T = PersistedMemoryItemDto> = PersistedMemorySafety & { ok: true; item: T; warnings?: PersistedMemoryReadWarning[] } | { ok: false; blocker: PersistedMemoryReadBlocker };
