/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, expect, it, vi } from "vitest";
import { runDailyMemoryCompaction } from "../lib/services/memory-compaction-service";
import { upsertVersionedMemoryProfile } from "../lib/services/memory-profile-service";
import { upsertOpenLoop } from "../lib/services/memory-open-loop-service";
function client(seed:Partial<Record<string,any[]>>={}){const rows:Record<string,any[]>={memory_events:[],memory_capture_candidates:[],memory_feedback_events:[],memory_profiles:[],memory_open_loops:[],memory_context_packs:[],...seed}; return {rows,from(table:string){let selected=[...(rows[table]??[])];let patch:any;let insertValue:any;const api:any={select:()=>api,eq:(k:string,v:any)=>{selected=selected.filter(r=>r[k]===v);return api;},order:(k:string,opt:any)=>{selected.sort((a,b)=>opt?.ascending?String(a[k]??"").localeCompare(String(b[k]??"")):String(b[k]??"").localeCompare(String(a[k]??"")));return api;},limit:(n:number)=>{selected=selected.slice(0,n);return api;},update:(v:any)=>{patch=v;return api;},insert:(v:any)=>{insertValue=v;return api;},single:async()=>{if(insertValue){const row={id:`${table}-${rows[table].length+1}`,...insertValue};rows[table].push(row);return {data:row,error:null};} if(patch){for(const r of selected)Object.assign(r,patch);return {data:selected[0]??null,error:selected[0]?null:{message:"not found"}};} return {data:selected[0]??null,error:selected[0]?null:{message:"not found"}};},then:(resolve:any)=>resolve({data:selected,error:null})};return api;}} as any;}
const ev=(id:string,raw_text:string,namespace="real_life",over:any={})=>({id,user_id:"u1",namespace,source:"project_update",raw_text,extracted_summary:raw_text,importance:7,sensitivity:"medium",status:"captured",created_at:"2026-06-28T00:00:00.000Z",...over});

describe("Phase 5C deterministic compaction",()=>{
 it("creates project, operating, style, risk, relationship, and daily pack outputs",async()=>{const c=client({memory_events:[ev("e1","Pandora Memory PR pending review in GitHub; Vercel deployment blocked"),ev("e2","I prefer be concise and don't overpraise; use direct tone"),ev("e3","money risk and reputation risk detected"),ev("e4","Patty relationship loop unresolved")],memory_capture_candidates:[{id:"c1",user_id:"u1",namespace:"real_life",status:"approved",summary:"Supabase migration pending",created_at:"2026-06-28T00:00:00.000Z"}],memory_feedback_events:[{id:"f1",user_id:"u1",namespace:"real_life",action:"approve",created_at:"2026-06-28T00:00:00.000Z"}]}); const r=await runDailyMemoryCompaction(c,{user_id:"u1",namespace:"real_life",since:"2026-06-27T00:00:00.000Z"}); expect(r.ok).toBe(true); expect(c.rows.memory_profiles.map((p:any)=>p.profile_type)).toEqual(expect.arrayContaining(["project_profile","operating_profile","style_profile","risk_profile","relationship_loop_profile"])); expect(c.rows.memory_open_loops.length).toBeGreaterThan(0); expect(c.rows.memory_context_packs[0].pack_type).toBe("daily"); expect(JSON.stringify(r.daily_pack)).not.toContain("password"); });
 it("keeps AU canon out of real_life but creates writing canon in au",async()=>{const au=client({memory_events:[ev("e1","AU canon chapter with Melodee fictional continuity","au")]}); await runDailyMemoryCompaction(au,{user_id:"u1",namespace:"au",since:"2026-06-27T00:00:00.000Z"}); expect(au.rows.memory_profiles.some((p:any)=>p.profile_type==="writing_canon_profile")).toBe(true); const real=client({memory_events:[ev("e1","AU canon chapter with Melodee fictional continuity","real_life")]}); await runDailyMemoryCompaction(real,{user_id:"u1",namespace:"real_life",since:"2026-06-27T00:00:00.000Z"}); expect(real.rows.memory_profiles.some((p:any)=>p.profile_type==="writing_canon_profile")).toBe(false); });
 it("versions active profiles and dry_run does not write",async()=>{const c=client({memory_profiles:[{id:"p1",user_id:"u1",namespace:"real_life",profile_type:"operating_profile",subject_key:"global",status:"active",version:1,evidence_refs:[{id:"old"}]}]}); const r=await upsertVersionedMemoryProfile(c,{user_id:"u1",namespace:"real_life",profile_type:"operating_profile",subject_key:"global",title:"t",summary:"s",evidence_refs:[{id:"new"}]}); expect(r.ok).toBe(true); expect(c.rows.memory_profiles[0].status).toBe("superseded"); expect(c.rows.memory_profiles[1].version).toBe(2); const d=client(); await runDailyMemoryCompaction(d,{user_id:"u1",namespace:"real_life",dry_run:true}); expect(d.rows.memory_profiles).toHaveLength(0); });
 it("updates open loops, merges evidence, and does not downgrade severity",async()=>{const c=client({memory_open_loops:[{id:"l1",user_id:"u1",namespace:"real_life",loop_type:"deployment",subject_key:"pandora",status:"open",severity:8,evidence_refs:[{id:"a"}]}]}); await upsertOpenLoop(c,{user_id:"u1",namespace:"real_life",loop_type:"deployment",subject_key:"pandora",title:"Deployment",description:"CI pending",severity:5,evidence_refs:[{id:"b"}]}); expect(c.rows.memory_open_loops).toHaveLength(1); expect(c.rows.memory_open_loops[0].severity).toBe(8); expect(c.rows.memory_open_loops[0].evidence_refs).toHaveLength(2); });
});

describe("Phase 5C job endpoint",()=>{
 it("requires token and distillation gate",async()=>{vi.resetModules(); process.env.PANDORA_INTERNAL_JOB_TOKEN="secret"; process.env.PANDORA_ENABLE_MEMORY_DISTILLATION="false"; const route=await import("../app/api/memory/jobs/daily-digest/route"); let res=await route.POST(new Request("http://x",{method:"POST",body:"{}"}) as any); expect(res.status).toBe(401); res=await route.POST(new Request("http://x",{method:"POST",headers:{authorization:"Bearer wrong"},body:"{}"}) as any); expect(res.status).toBe(401); res=await route.POST(new Request("http://x",{method:"POST",headers:{authorization:"Bearer secret"},body:JSON.stringify({namespace:"real_life",dry_run:true,user_id:"u1"})}) as any); expect(res.status).toBe(403); });
});
