import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/ui/page-header";
import { SectionCard } from "@/components/ui/section-card";
import { resolvePandoraRuntimeSafetyConfig, resolvePandoraMemoryAutopilotMode } from "@/lib/config/pandora-runtime-safety-config";
import { resolvePandoraServerSession } from "@/lib/auth/pandora-server-session-resolver";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { listMemoryCandidatesForAdmin, type CandidateListFilters } from "@/lib/services/admin-memory-candidate-loader";
import type { MemoryBridgeDbClient } from "@/lib/services/memory-bridge-service";
import { approveCandidateAction, captureCandidateAction, duplicateCandidateAction, editCandidateAction, rejectCandidateAction } from "./actions";
export const dynamic = "force-dynamic";
const statuses = ["pending","blocked_secret","approved","rejected","captured","duplicate","all"];
const sensitivities = ["all","low","medium","high","private"];
const sorts = ["newest","importance","confidence","sensitivity"];
export default async function Page({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const sp = await searchParams; const runtime = resolvePandoraRuntimeSafetyConfig(); const session = await resolvePandoraServerSession();
  const filters: CandidateListFilters = { namespace: sp.namespace === "au" || sp.namespace === "real_life" ? sp.namespace : undefined, status: statuses.includes(sp.status ?? "") ? sp.status as CandidateListFilters["status"] : "pending", sensitivity: sensitivities.includes(sp.sensitivity ?? "") ? sp.sensitivity as CandidateListFilters["sensitivity"] : "all", sort: sorts.includes(sp.sort ?? "") ? sp.sort as CandidateListFilters["sort"] : "newest", limit: Number(sp.limit ?? 50) };
  const client = (await createSupabaseServerClient()) as unknown as MemoryBridgeDbClient;
  const data = session.ok ? await listMemoryCandidatesForAdmin(client, { userId: session.session.userId, filters }) : { candidates: [], counts: { pending:0, blocked_secret:0, approved:0, rejected:0, captured:0, duplicate:0, total:0 }, warnings:["auth_required"] };
  return <AppShell><PageHeader eyebrow="Internal admin" title="Pandora Memory Candidates" description="Phase 5B review console: auto-queued candidates become teachable, reviewed, duplicate-aware, and capture-gated memory." />
    <SectionCard title="Safety status" description="Dangerous capabilities remain gated; candidate review does not require model calls, embeddings, semantic retrieval, GPT Actions, or MCP."><ul><li>Public read: {runtime.config.publicMemoryReadEnabled ? "WARNING enabled" : "disabled"}</li><li>Public persistence: {runtime.config.publicMemoryPersistenceEnabled ? "WARNING enabled" : "disabled"}</li><li>Model calls: {runtime.config.modelCallsEnabled ? "enabled" : "disabled"}</li><li>Embeddings: {runtime.config.embeddingsEnabled ? "enabled" : "disabled"}</li><li>Semantic retrieval: {runtime.config.semanticRetrievalEnabled ? "enabled" : "disabled"}</li><li>Auto-capture: {runtime.config.autoCaptureLowRiskEnabled ? "WARNING enabled" : "disabled"}</li><li>Autopilot mode: {resolvePandoraMemoryAutopilotMode()}</li><li>Capture API gate: {String(runtime.config.memoryCaptureApiEnabled)}</li></ul></SectionCard>
    <SectionCard title="Filters" description="All database reads are server-side and scoped to the authenticated user."><form className="memory-browser-filter-form"><label>Namespace<select name="namespace" defaultValue={filters.namespace ?? ""}><option value="">all</option><option value="real_life">real_life</option><option value="au">au</option></select></label><label>Status<select name="status" defaultValue={filters.status}>{statuses.map(s=><option key={s} value={s}>{s}</option>)}</select></label><label>Sensitivity<select name="sensitivity" defaultValue={filters.sensitivity}>{sensitivities.map(s=><option key={s} value={s}>{s}</option>)}</select></label><label>Sort<select name="sort" defaultValue={filters.sort}>{sorts.map(s=><option key={s} value={s}>{s}</option>)}</select></label><button>Apply</button></form><p>{Object.entries(data.counts).map(([k,v]) => `${k}: ${v}`).join(" · ")}</p>{data.warnings.map(w=><p key={w}><strong>Warning:</strong> {w}</p>)}</SectionCard>
    <SectionCard title="Candidate queue" description="Blocked secrets never display raw excerpt. High/private candidates are visibly marked for careful review.">{data.candidates.length === 0 ? <p>No candidates for current filters.</p> : data.candidates.map(c => <article key={c.id} style={{border:"1px solid #444", borderRadius:12, padding:16, marginBottom:16}}><h2>{c.title || "Untitled candidate"}</h2><p>{c.summary}</p>{(c.sensitivity === "high" || c.sensitivity === "private") && <p><strong>Careful review required: {c.sensitivity}</strong></p>}<dl><dt>type/status</dt><dd>{c.memory_type} / {c.status}</dd><dt>namespace/source</dt><dd>{c.namespace} / {c.source} {c.source_ref}</dd><dt>scores</dt><dd>importance {c.importance} · confidence {c.confidence} · sensitivity {c.sensitivity}</dd><dt>usefulness</dt><dd>{c.score.labels.join(" · ")} · weight {c.score.retrieval_weight.toFixed(2)} · {c.score.stale_status}</dd><dt>review flags</dt><dd>requires_review {String(c.requires_review)} · should_capture {String(c.should_capture)}</dd><dt>reason</dt><dd>{c.reason}</dd><dt>tags/risks</dt><dd>{JSON.stringify(c.tags ?? [])} / {JSON.stringify(c.risks ?? [])}</dd><dt>created/reviewed</dt><dd>{c.created_at} / {c.reviewed_at ?? "not reviewed"}</dd>{c.captured_event_id && <><dt>captured event</dt><dd>{c.captured_event_id}</dd></>}<dt>excerpt</dt><dd>{c.status === "blocked_secret" ? "[REDACTED_SECRET]" : (c.redacted_excerpt ?? c.summary)}</dd></dl>
      {(c.status === "pending" || c.status === "approved") && <form action={editCandidateAction}><input type="hidden" name="id" value={c.id}/><input type="hidden" name="namespace" value={c.namespace}/><label>Title<input name="title" defaultValue={c.title ?? ""}/></label><label>Summary<textarea name="summary" defaultValue={c.summary ?? ""}/></label><label>Type<input name="memory_type" defaultValue={c.memory_type ?? "note"}/></label><label>Sensitivity<select name="sensitivity" defaultValue={String(c.sensitivity ?? "medium")}>{["low","medium","high","private"].map(s=><option key={s}>{s}</option>)}</select></label><label>Importance<input type="number" min="1" max="10" name="importance" defaultValue={c.importance ?? 5}/></label><label>Tags<input name="tags" defaultValue={(c.tags ?? []).join(", ")}/></label><label>Risks<input name="risks" defaultValue={(c.risks ?? []).join(", ")}/></label><button>Edit candidate</button></form>}
      <div>{c.status !== "blocked_secret" && c.status === "pending" && <form action={approveCandidateAction}><input type="hidden" name="id" value={c.id}/><input type="hidden" name="namespace" value={c.namespace}/><input name="review_note" placeholder="approval note"/><button>Approve</button></form>}{c.status === "approved" && <form action={captureCandidateAction}><input type="hidden" name="id" value={c.id}/><input type="hidden" name="namespace" value={c.namespace}/><button>Capture approved</button></form>}{["pending","approved","blocked_secret"].includes(c.status) && <form action={rejectCandidateAction}><input type="hidden" name="id" value={c.id}/><input type="hidden" name="namespace" value={c.namespace}/><select name="reason"><option>noise</option><option>wrong</option><option>duplicate</option><option>too_sensitive</option><option>not_durable</option><option>wrong_namespace</option><option>other</option></select><input name="review_note" placeholder="reject note"/><button>Reject</button></form>}{["pending","blocked_secret"].includes(c.status) && <form action={duplicateCandidateAction}><input type="hidden" name="id" value={c.id}/><input type="hidden" name="namespace" value={c.namespace}/><input name="duplicate_of_candidate_id" placeholder="duplicate candidate id"/><button>Mark duplicate</button></form>}</div>
    </article>)}</SectionCard></AppShell>;
}
