import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import Page from "@/app/admin/memory/fixture-dry-run/page";
import { buildAllFirstReviewedMemoryFixtures, buildFirstReviewedMemoryFixture } from "@/lib/services/first-reviewed-memory-fixture-builder";
import { createInMemoryFirstReviewedMemoryFixtureRepository } from "@/lib/db/first-reviewed-memory-fixture-repository";
import { runManualWorkflowFixtureHarness } from "@/lib/services/operator-manual-workflow-fixture-harness";

const root = process.cwd();

describe("first reviewed-memory fixture dry-run pack", () => {
  it("builder creates deterministic IDs, timestamps, and fingerprints", () => { const a = buildFirstReviewedMemoryFixture({ scenario: "real_life_fact_append" }); const b = buildFirstReviewedMemoryFixture({ scenario: "real_life_fact_append" }); expect(a.id).toBe(b.id); expect(a.timestamp).toBe("2026-01-15T12:00:00.000Z"); expect(a.fingerprint).toBe(b.fingerprint); expect(JSON.stringify(a)).toBe(JSON.stringify(b)); });
  it("passes real-life and AU append scenarios with namespace isolation", async () => { const real = await runManualWorkflowFixtureHarness({ fixture: buildFirstReviewedMemoryFixture({ scenario: "real_life_fact_append" }) }); const au = await runManualWorkflowFixtureHarness({ fixture: buildFirstReviewedMemoryFixture({ scenario: "au_story_only_append" }) }); expect(real.ok).toBe(true); expect(au.ok).toBe(true); expect(buildFirstReviewedMemoryFixture({ scenario: "au_story_only_append" }).targetNamespace).toBe("au"); });
  it("blocks contamination, missing audit, and non-append decisions", async () => { for (const scenario of ["blocked_au_to_real_life_contamination", "blocked_missing_audit", "blocked_non_append_decision"] as const) { const result = await runManualWorkflowFixtureHarness({ fixture: buildFirstReviewedMemoryFixture({ scenario }) }); expect(result.ok).toBe(true); expect(result.expectedBlocked).toBe(true); } });
  it("repository is in-memory only and never writes actual memory tables", async () => { const repo = createInMemoryFirstReviewedMemoryFixtureRepository(buildAllFirstReviewedMemoryFixtures()); expect(repo.testOnly).toBe(true); expect(repo.productionSeed).toBe(false); await expect(repo.createReviewQueueItem({ userId: "u", namespace: "real_life" }, {} as never)).resolves.toMatchObject({ ok: false }); });
  it("harness verifies preview ordering, injected executor, readback, browser, audit, and receipt", async () => { const result = await runManualWorkflowFixtureHarness({ fixture: buildFirstReviewedMemoryFixture({ scenario: "real_life_fact_append" }) }); expect(result).toMatchObject({ ok: true, previewBeforeExecutor: true, executorInjectedOnly: true, readbackVerified: true, browserVerified: true, auditVerified: true, receiptVerified: true }); });
  it("CLI prints safe output only", () => { const out = execFileSync("npm", ["run", "verify:first-reviewed-memory-fixture"], { cwd: root, encoding: "utf8" }); expect(out).toContain("TEST-ONLY FIXTURE HARNESS"); expect(out).toContain("NO PRODUCTION WRITES"); expect(out).toContain("NO MODEL CALLS"); expect(out).toContain("NO SEMANTIC RETRIEVAL"); expect(out).not.toMatch(/SUPABASE_SERVICE_ROLE|sk-|secret/i); });
  it("UI renders test-only safety copy", () => { const html = renderToStaticMarkup(<Page />); expect(html).toContain("First reviewed-memory fixture dry-run"); expect(html).toContain("Test-only fixture harness"); expect(html).toContain("No production writes"); expect(html).toContain("No public persistence"); expect(html).toContain("No production ingest writes"); expect(html).toContain("No model calls, embeddings, or semantic retrieval"); expect(html).toContain("AU/story memory cannot become real-life evidence"); });
  it("fixture files avoid Supabase service-role, model, retrieval, vector, pgvector, GPT Actions, and MCP imports", () => { const files = ["lib/services/first-reviewed-memory-fixture-contract.ts", "lib/services/first-reviewed-memory-fixture-builder.ts", "lib/db/first-reviewed-memory-fixture-repository.ts", "lib/services/operator-manual-workflow-fixture-harness.ts", "scripts/verify-first-reviewed-memory-fixture.ts", "app/admin/memory/fixture-dry-run/page.tsx"]; const text = files.map((f) => readFileSync(join(root, f), "utf8")).join("\n"); expect(text).not.toMatch(/service-role|SUPABASE_SERVICE_ROLE|from ["'].*(supabase|openai|anthropic|retrieval|pgvector|vector|embedding|gpt-actions|mcp)/i); });
  it("critical production boundaries remain disabled or read-only", () => { expect(readFileSync(join(root, "lib/api/memory-ingest-route-handler.ts"), "utf8")).toMatch(/intentionally disabled|production/i); expect(readFileSync(join(root, "app/api/memory/review/[id]/persist/route.ts"), "utf8")).toMatch(/disabled/i); expect(readFileSync(join(root, "lib/services/persisted-memory-browser-loader.ts"), "utf8")).not.toMatch(/executeApproved|appendReviewDecision|deleteMemory|updateMemory/); expect(readFileSync(join(root, "app/api/admin/memory/qa-flow/route.ts"), "utf8")).toMatch(/enabled: false/); expect(readFileSync(join(root, "lib/api/operator-manual-memory-workflow-route-handler.ts"), "utf8")).toMatch(/manual_workflow_disabled|disabled/i); });
});
