import { describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
import { renderToStaticMarkup } from "react-dom/server";
import { readFileSync } from "fs";
import { join } from "path";
import { validateLiveOneReviewedItemWorkflowPreflight } from "@/lib/services/live-one-reviewed-item-workflow-preflight";
import { runLiveOneReviewedItemWorkflow } from "@/lib/services/live-one-reviewed-item-workflow-runner";
import { createLiveOneReviewedItemWorkflowRouteHandler } from "@/lib/api/live-one-reviewed-item-workflow-route-handler";
import Page from "@/app/admin/memory/live-one-item/page";

const runtime = { config: { persistedMemoryReadEnabled: true, adminPersistenceConsoleEnabled: true, approvedReviewPersistenceEnabled: true, operatorQaFlowEnabled: false, ingestProductionWriteEnabled: false, publicMemoryReadEnabled: false, publicMemoryPersistenceEnabled: false, modelCallsEnabled: false, embeddingsEnabled: false, semanticRetrievalEnabled: false, gptActionsEnabled: false, mcpEnabled: false }, gates: {} } as never;
const sessionResult = { ok: true, session: { userId: "u1", authenticated: true, allowedNamespaces: ["real_life"], adminCapabilities: ["memory:manual-workflow"], isInternalOperator: true, isPersistenceOperator: true } } as never;
const item = { id: "r1", status: "approved_for_append", userId: "u1", namespace: "real_life", candidateType: "fact", normalizedText: "secret", evidence: { hasEvidence: true, spans: [], spanRanges: [] }, sensitivity: { level: "low", resolved: true }, proposedOperation: "append", appendOnly: true, sourceMetadata: {}, namespaceIsolation: { namespace: "real_life", classification: "real_life", auOnly: false, realLifeOnly: true, explicitlyFictionalized: false, mixedContent: false, realLifeCannotConsumeAuEvidence: true, auContentCannotBecomeRealLifeEvidence: true }, blockers: [], warnings: [], createdAt: "t", updatedAt: "pf", audit: { fingerprint: "pf", decisionTrail: [{ action: "approve_append" }] } } as never;
const decision = { id: "d1", itemId: "r1", userId: "u1", namespace: "real_life", action: "approve_append", createdAt: "t", audit: {} } as never;
const preview = { ok: true, plans: [{ itemId: "r1", eligible: true }], summary: { plannedSources: 1, plannedItems: 1, plannedPatches: 1, plannedAuditLogs: 1 } } as never;
const base = { context: { userId: "u1", namespace: "real_life" as const }, sessionResult, runtime, namespace: "real_life" as const, allowedNamespaces: ["real_life" as const], reviewItemId: "r1", decisionId: "d1", idempotencyKey: "idem", typedConfirmation: "APPEND MEMORY", internalHeaderMode: "approved-review-executor", operatorCapability: true, reviewItem: item, decision, preview, approvedReviewPersistenceExecutor: vi.fn(), persistedMemoryReadRepository: {}, browserLoader: vi.fn(), auditVerifier: vi.fn() };
const codes = (over: Record<string, unknown>) => validateLiveOneReviewedItemWorkflowPreflight({ ...base, ...over } as never).blockers.map((b) => b.code);
function deps() { const calls: string[] = []; return { ...base, reviewRepository: { readReviewQueueItemById: vi.fn(async () => ({ ok: true, data: item })), readReviewDecisionById: vi.fn(async () => ({ ok: true, data: decision })) }, previewService: vi.fn(() => { calls.push("preview"); return preview; }), approvedReviewPersistenceExecutor: vi.fn(async () => { calls.push("executor"); return { executed: true, productionRouteEnabled: false, publicRouteEnabled: false, appendOnly: true, namespace: "real_life", userId: "u1", counts: {}, blockers: [], warnings: [], fingerprint: "pf", source: { id: "s1" }, item: { id: "m1" }, patch: { id: "p1" }, auditLog: { id: "a1" } }; }), persistedMemoryReadRepository: { getMemoryItemDetail: vi.fn(async () => ({ ok: true, item: { id: "m1" } })) }, browserLoader: vi.fn(async () => ({ items: [{ id: "m1" }] })), auditVerifier: vi.fn(async () => ({ ok: true, count: 1 })), calls } as never; }

describe("live one reviewed item workflow", () => {
  it("preflight blocks required safety failures", () => {
    expect(codes({ context: undefined, sessionResult: undefined })).toEqual(expect.arrayContaining(["missing_session", "missing_authenticated_user"]));
    expect(codes({ operatorCapability: false })).toContain("missing_operator_capability");
    expect(codes({ user_id: "evil" })).toContain("client_user_id_rejected");
    expect(codes({ userId: "evil" })).toContain("client_user_id_rejected");
    expect(codes({ namespace: undefined })).toContain("missing_namespace");
    expect(codes({ namespace: "au_story", reviewItem: { ...item, namespace: "real_life" } })).toEqual(expect.arrayContaining(["namespace_not_allowed", "namespace_mismatch"]));
    expect(codes({ runtime: undefined })).toContain("missing_runtime_gates");
    for (const [gate, code] of [["publicMemoryPersistenceEnabled", "public_persistence_enabled"], ["ingestProductionWriteEnabled", "production_ingest_enabled"], ["publicMemoryReadEnabled", "public_read_enabled"], ["modelCallsEnabled", "model_calls_enabled"], ["embeddingsEnabled", "embeddings_enabled"], ["semanticRetrievalEnabled", "semantic_retrieval_enabled"], ["gptActionsEnabled", "gpt_actions_enabled"], ["mcpEnabled", "mcp_enabled"], ["approvedReviewPersistenceEnabled", "approved_review_persistence_gate_disabled"], ["adminPersistenceConsoleEnabled", "admin_persistence_gate_disabled"]] as const) expect(codes({ runtime: { ...runtime, config: { ...runtime.config, [gate]: !runtime.config[gate] } } })).toContain(code);
    expect(codes({ reviewItem: undefined })).toContain("missing_review_item");
    expect(codes({ reviewItem: { ...item, status: "pending_review" } })).toContain("review_item_not_approved");
    expect(codes({ decision: undefined })).toContain("missing_append_decision");
    expect(codes({ decision: { ...decision, action: "reject" } })).toContain("non_append_decision");
    expect(codes({ decision: { ...decision, itemId: "other" } })).toContain("decision_item_mismatch");
    expect(codes({ preview: undefined })).toContain("missing_preview");
    expect(codes({ preview: { ok: true, plans: [{ itemId: "r1", eligible: false }] } })).toContain("ineligible_preview");
    expect(codes({ idempotencyKey: undefined })).toContain("missing_idempotency_key");
    expect(codes({ typedConfirmation: "append memory" })).toContain("typed_confirmation_mismatch");
    expect(codes({ internalHeaderMode: undefined })).toContain("missing_internal_header");
    expect(codes({ approvedReviewPersistenceExecutor: undefined })).toContain("missing_executor_dependency");
    expect(codes({ persistedMemoryReadRepository: undefined })).toContain("missing_readback_dependency");
    expect(codes({ browserLoader: undefined })).toContain("missing_browser_loader_dependency");
    expect(codes({ auditVerifier: undefined })).toContain("missing_audit_verification_dependency");
  });
  it("runner builds preview before injected executor and verifies readback/browser/audit", async () => { const d = deps(); const r = await runLiveOneReviewedItemWorkflow(d); expect(r.ok).toBe(true); expect(d.calls).toEqual(["preview", "executor"]); expect(d.approvedReviewPersistenceExecutor).toHaveBeenCalledTimes(1); expect(d.persistedMemoryReadRepository.getMemoryItemDetail).toHaveBeenCalled(); expect(d.browserLoader).toHaveBeenCalled(); expect(d.auditVerifier).toHaveBeenCalled(); expect(JSON.stringify(r.receipt)).not.toMatch(/"userId":"u1|"idempotencyKey":"idem|secret|evidence text|service-role|raw error/i); });
  it("route GET is safe and POST is disabled/rejects unsafe inputs", async () => { const h = createLiveOneReviewedItemWorkflowRouteHandler(); expect((await h.GET()).status).toBe(200); expect((await h.POST(new NextRequest("https://x", { method: "POST", body: "{}" }))).status).toBe(501); expect((await createLiveOneReviewedItemWorkflowRouteHandler({ enabled: true }).POST(new NextRequest("https://x", { method: "POST", body: JSON.stringify({ user_id: "evil" }) }))).status).toBe(400); const res = await createLiveOneReviewedItemWorkflowRouteHandler({ enabled: true, resolveSession: async () => sessionResult, env: () => ({ PANDORA_ENABLE_APPROVED_REVIEW_MEMORY_PERSISTENCE: "true", PANDORA_ENABLE_ADMIN_PERSISTENCE_CONSOLE: "true" }) as never }).POST(new NextRequest("https://x", { method: "POST", body: JSON.stringify({ namespace: "real_life", reviewItemId: "r1", decisionId: "d1", idempotencyKey: "i", typedConfirmation: "APPEND MEMORY" }) })); expect(res.status).toBe(403); expect((await res.json()).blockers).toContain("missing_internal_header"); });
  it("UI renders all safety copy", () => { const html = renderToStaticMarkup(<Page />); for (const text of ["Live one-item memory workflow", "Internal operator workflow", "One approved review item only", "Public persistence is disabled", "Production ingest writes are disabled", "Execution requires typed confirmation: APPEND MEMORY", "No model calls, embeddings, or semantic retrieval", "All memory persistence remains append-only", "Audit verification is required", "AU/story memory cannot become real-life evidence", "Real-life memory cannot enter AU unless explicitly fictionalized and reviewed", "Readiness panel", "Live dry-run panel", "Preview panel", "Execution gate panel", "Readback panel", "Browser visibility panel", "Audit verification panel", "Receipt panel"]) expect(html).toContain(text); expect(html).toContain("disabled"); });
  it("forbidden integrations remain absent and existing safety routes remain disabled/read-only/test-only", () => { const root = process.cwd(); const files = ["lib/services/live-one-reviewed-item-workflow-runner.ts", "lib/api/live-one-reviewed-item-workflow-route-handler.ts", "app/api/admin/memory/live-one-item/route.ts"]; const text = files.map((f) => readFileSync(join(root, f), "utf8")).join("\n"); expect(text).not.toMatch(/from [^;]*(openai|anthropic|embedding|vector|pgvector|mcp)|service-role|SUPABASE_SERVICE_ROLE|createClient/i); expect(readFileSync(join(root, "lib/api/memory-ingest-route-handler.ts"), "utf8")).toMatch(/intentionally disabled|disabled/i); expect(readFileSync(join(root, "app/api/memory/review/[id]/persist/route.ts"), "utf8")).toMatch(/disabled/i); expect(readFileSync(join(root, "lib/services/persisted-memory-browser-loader.ts"), "utf8")).not.toMatch(/append|update|delete|execute/i); expect(readFileSync(join(root, "lib/services/operator-manual-workflow-fixture-harness.ts"), "utf8")).toMatch(/fixture|test/i); });
});
