import { describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
import { renderToStaticMarkup } from "react-dom/server";
import { readFileSync } from "fs";
import { join } from "path";
import { runOperatorMemoryQaFlow } from "@/lib/services/operator-memory-qa-flow-runner";
import { verifyOperatorMemoryReadback } from "@/lib/services/operator-memory-readback-verifier";
import { createOperatorMemoryQaFlowRouteHandler } from "@/lib/api/operator-memory-qa-flow-route-handler";
import Page from "@/app/admin/memory/qa-flow/page";
import { POST } from "@/app/api/admin/memory/qa-flow/route";

const root = process.cwd(); const ctx = { userId: "u1", namespace: "real_life" as const };
const item = { id: "r1", status: "approved_for_append", userId: "u1", namespace: "real_life", extractedCandidateId: "e", candidateType: "fact", normalizedText: "coffee", evidence: { spans: [], spanRanges: [], hasEvidence: true }, sensitivity: { level: "low", requiresSensitiveReview: false, resolved: true }, requiresReview: true, appendOnly: true, proposedOperation: "append", sourceMetadata: { sourceType: "manual" }, sourceRef: "src", namespaceIsolation: { namespace: "real_life", classification: "real_life", auOnly: false, realLifeOnly: true, explicitlyFictionalized: false, mixedContent: false, realLifeCannotConsumeAuEvidence: true, auContentCannotBecomeRealLifeEvidence: true }, blockers: [], warnings: [], createdAt: "t", updatedAt: "pf", audit: { createdByUserId: "u1", updatedByUserId: "u1", createdFrom: "contract_test", fingerprint: "pf", decisionTrail: [{ action: "approve_append", at: "d1", reviewerUserId: "u1" }] } } as never;
function deps(over: Record<string, unknown> = {}) { const repo = { readReviewQueueItemById: vi.fn(async () => ({ ok: true, data: item })), readReviewDecisionById: vi.fn(async () => ({ ok: true, data: { id: "d1", itemId: "r1", userId: "u1", namespace: "real_life", action: "approve_append", createdAt: "t", audit: {} } })) }; const previewService = vi.fn(() => ({ ok: true, previewOnly: true, approvedReviewItemIsNotMemory: true, futureGatedPersistenceRequired: true, wouldPersist: false, wouldCallModel: false, wouldEmbed: false, productionWriteDisabled: true, requiresFutureInternalGate: true, plans: [{ itemId: "r1", eligible: true, blockers: [], warnings: [], namespaceSafety: {}, evidenceSafety: {}, source: {}, item: {}, patch: {}, auditLog: {}, wouldPersist: false, wouldCallModel: false, wouldEmbed: false }], blockers: [], warnings: [], summary: {} })); const persistenceExecutor = vi.fn(async () => ({ executed: true, productionRouteEnabled: false, publicRouteEnabled: false, appendOnly: true, namespace: "real_life", userId: "u1", counts: { sources: 1, items: 1, patches: 1, auditLogs: 1, markedReviewItems: 1, blocked: 0, failed: 0 }, blockers: [], warnings: [], fingerprint: "pf", idempotencyKey: "idem", source: { kind: "memory_source_append", id: "s1", appendOnly: true }, item: { kind: "memory_item_append", id: "m1", appendOnly: true }, patch: { kind: "memory_patch_append", id: "p1", appendOnly: true }, auditLog: { kind: "audit_log_append", id: "a1", appendOnly: true } })); const read = { getMemoryItemDetail: vi.fn(async () => ({ ok: true, item: { id: "m1", namespace: "real_life", textPreview: "redacted", reviewItemId: "r1", decisionId: "d1", auditSummary: "idem pf r1 d1", sensitiveEvidenceRedacted: true, auStoryMemoryIsNotRealLifeEvidence: true } })), listMemorySources: vi.fn(async () => ({ ok: true, items: [{ id: "s1", namespace: "real_life", itemId: "m1", reviewItemId: "r1", decisionId: "d1", excerptPreview: "idem pf r1 d1", sensitiveEvidenceRedacted: true }] })), listMemoryPatches: vi.fn(async () => ({ ok: true, items: [{ id: "p1", namespace: "real_life", itemId: "m1", patchType: "append", reason: "idem pf r1 d1", sensitiveEvidenceRedacted: true }] })), listMemoryAuditEvents: vi.fn(async () => ({ ok: true, items: [{ id: "a1", namespace: "real_life", action: "append", summary: "idem pf r1 d1", sensitiveEvidenceRedacted: true }] })), listMemoryItems: vi.fn(async () => ({ ok: true, items: [{ id: "m1", namespace: "real_life", textPreview: "", reviewItemId: "r1", decisionId: "d1", sensitiveEvidenceRedacted: true, auStoryMemoryIsNotRealLifeEvidence: true }] })) }; return { context: ctx, namespace: "real_life", reviewItemId: "r1", decisionId: "d1", idempotencyKey: "idem", reviewRepository: repo, previewService, persistenceExecutor, persistedMemoryReadRepository: read, browserLoader: vi.fn(async () => ({ items: [{ id: "m1" }], sources: [], patches: [], auditEvents: [], blockers: [], filters: {}, empty: false })) as never, ...over } as never; }

describe("operator memory QA flow", () => {
  it("rejects missing auth, namespace, client user override, non-approved review, missing/non-append decision, and missing idempotency", async () => { expect((await runOperatorMemoryQaFlow(deps({ context: undefined }))).blockers[0].code).toBe("missing_auth_context"); expect((await runOperatorMemoryQaFlow(deps({ namespace: undefined }))).blockers[0].code).toBe("missing_or_mismatched_namespace"); expect((await runOperatorMemoryQaFlow(deps({ user_id: "evil" }))).blockers[0].code).toBe("client_user_id_rejected"); expect((await runOperatorMemoryQaFlow(deps({ idempotencyKey: undefined }))).blockers[0].code).toBe("missing_idempotency_key"); expect((await runOperatorMemoryQaFlow(deps({ reviewRepository: { readReviewQueueItemById: vi.fn(async()=>({ ok:true, data:{...item, status:"pending_review"}})) } }))).blockers[0].code).toBe("review_item_not_approved"); expect((await runOperatorMemoryQaFlow(deps({ reviewRepository: { readReviewQueueItemById: vi.fn(async()=>({ ok:true, data:item})), readReviewDecisionById: vi.fn(async()=>({ ok:true, data:{ id:"d1", itemId:"r1", action:"reject" }})) } }))).blockers[0].code).toBe("non_append_decision"); });
  it("builds preview before execution, uses injected executor/read repository, and verifies browser visibility", async () => { const d = deps(); const result = await runOperatorMemoryQaFlow(d); expect(result.ok).toBe(true); expect(d.previewService).toHaveBeenCalled(); expect(d.persistenceExecutor).toHaveBeenCalled(); expect(d.persistedMemoryReadRepository.getMemoryItemDetail).toHaveBeenCalled(); expect(d.browserLoader).toHaveBeenCalled(); expect(result.readback?.browserVisible).toBe(true); });
  it("blocks namespace mismatch, AU-to-real-life, real-life-to-AU, missing audit, and non-append readback", () => { expect(verifyOperatorMemoryReadback({ userId:"u", namespace:"real_life", reviewItemId:"r", decisionId:"d", idempotencyKey:"i", previewFingerprint:"p", item:{ id:"m", namespace:"au_story" } as never, sources:[], patches:[], auditEvents:[] }).blockers.map(b=>b.code)).toContain("namespace_mismatch"); expect(verifyOperatorMemoryReadback({ userId:"u", namespace:"real_life", reviewItemId:"r", decisionId:"d", idempotencyKey:"i", previewFingerprint:"p", item:{ id:"m", namespace:"real_life", auditSummary:"au_story r d i p" } as never, sources:[{ id:"s", namespace:"real_life" } as never], patches:[{ id:"p", namespace:"real_life", itemId:"m" } as never], auditEvents:[{ id:"a", namespace:"real_life", summary:"au_story r d i p" } as never] }).blockers.map(b=>b.code)).toContain("au_to_real_life_contamination"); expect(verifyOperatorMemoryReadback({ userId:"u", namespace:"au_private", reviewItemId:"r", decisionId:"d", idempotencyKey:"i", previewFingerprint:"p", item:{ id:"m", namespace:"au_private", auditSummary:"real-life evidence r d i p" } as never, sources:[{ id:"s", namespace:"au_private" } as never], patches:[{ id:"p", namespace:"au_private", itemId:"m" } as never], auditEvents:[{ id:"a", namespace:"au_private", summary:"real-life evidence r d i p" } as never] }).blockers.map(b=>b.code)).toContain("real_life_to_au_contamination"); expect(verifyOperatorMemoryReadback({ userId:"u", namespace:"real_life", reviewItemId:"r", decisionId:"d", idempotencyKey:"i", previewFingerprint:"p", item:{ id:"m", namespace:"real_life", auditSummary:"delete r d i p" } as never, sources:[{ id:"s", namespace:"real_life" } as never], patches:[{ id:"p", namespace:"real_life", itemId:"m" } as never], auditEvents:[{ id:"a", namespace:"real_life", summary:"delete r d i p" } as never] }).blockers.map(b=>b.code)).toContain("non_append_operation"); });
  it("route factory is disabled by default, rejects user_id, requires env/header gates, and public stub does not execute", async () => { expect((await createOperatorMemoryQaFlowRouteHandler()(new NextRequest("https://x", { method:"POST", body:"{}" }))).status).toBe(501); expect((await createOperatorMemoryQaFlowRouteHandler({ enabled:true })(new NextRequest("https://x", { method:"POST", body:JSON.stringify({ user_id:"u" }) }))).status).toBe(400); const gated = await createOperatorMemoryQaFlowRouteHandler({ enabled:true, resolveAuth:async()=>({userId:"u"}) })(new NextRequest("https://x", { method:"POST", body:JSON.stringify({ namespace:"real_life", reviewItemId:"r", decisionId:"d", idempotencyKey:"i" }) })); expect(gated.status).toBe(403); expect((await POST(new NextRequest("https://x", { method:"POST", body:"{}" }))).status).toBe(501); });
  it("QA UI shows disabled/internal copy", () => { const html = renderToStaticMarkup(<Page />); expect(html).toContain("Internal operator QA flow"); expect(html).toContain("Disabled by default"); expect(html).toContain("No public persistence is enabled"); expect(html).toContain("No model calls, embeddings, or semantic retrieval are enabled"); expect(html).toContain("AU/story memory cannot become real-life evidence"); expect(html).toContain("disabled"); });
  it("safety files avoid service-role, provider, retrieval, vector, GPT Actions, MCP imports and critical routes remain disabled/read-only", () => { const files = ["app/api/admin/memory/qa-flow/route.ts", "lib/api/operator-memory-qa-flow-route-handler.ts", "lib/services/operator-memory-qa-flow-runner.ts", "lib/services/operator-memory-readback-verifier.ts", "app/admin/memory/qa-flow/page.tsx"]; const text = files.map(f=>readFileSync(join(root,f),"utf8")).join("\n"); expect(text).not.toMatch(/from [^;]*(service-role|SUPABASE_SERVICE_ROLE|openai|anthropic|model provider|retrieval-service|pgvector|embedding|GPT Actions|MCP)/i); expect(readFileSync(join(root,"lib/api/memory-ingest-route-handler.ts"),"utf8")).toMatch(/production|disabled|test-only/i); expect(readFileSync(join(root,"app/api/memory/review/[id]/persist/route.ts"),"utf8")).toMatch(/disabled/i); expect(readFileSync(join(root,"lib/services/persisted-memory-browser-loader.ts"),"utf8")).not.toMatch(/appendMemory|executeApproved|deleteMemory|updateMemory/i); });
});
