import { describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
import { renderToStaticMarkup } from "react-dom/server";
import { readFileSync } from "fs";
import { join } from "path";
import { validateOperatorManualMemoryWorkflowPreflight } from "@/lib/services/operator-manual-memory-workflow-preflight";
import { runOperatorManualMemoryWorkflow } from "@/lib/services/operator-manual-memory-workflow-runner";
import { toOperatorManualMemoryWorkflowSafeDto } from "@/lib/api/operator-manual-memory-workflow-dto";
import { createOperatorManualMemoryWorkflowRouteHandler } from "@/lib/api/operator-manual-memory-workflow-route-handler";
import Page from "@/app/admin/memory/manual-workflow/page";
import { GET, POST } from "@/app/api/admin/memory/manual-workflow/route";
const root = process.cwd();
const runtime = { config: { persistedMemoryReadEnabled: true, adminPersistenceConsoleEnabled: true, approvedReviewPersistenceEnabled: true, operatorQaFlowEnabled: false, ingestProductionWriteEnabled: false, publicMemoryReadEnabled: false, publicMemoryPersistenceEnabled: false, modelCallsEnabled: false, embeddingsEnabled: false, semanticRetrievalEnabled: false, gptActionsEnabled: false, mcpEnabled: false }, gates: {} } as never;
const sessionResult = { ok: true, session: { userId: "u1", authenticated: true, allowedNamespaces: ["real_life"], adminCapabilities: ["memory:manual-workflow"], isInternalOperator: true, isPersistenceOperator: true, serverDerivedOnly: true, clientUserIdAccepted: false, publicReadAllowed: false, publicPersistenceAllowed: false, serviceRoleUsed: false, sessionSource: "test" }, blockers: [] } as never;
const item = { id: "r1", status: "approved_for_append", userId: "u1", namespace: "real_life", candidateType: "fact", normalizedText: "secret memory text", evidence: { hasEvidence: true, spans: [], spanRanges: [] }, sensitivity: { level: "low", resolved: true }, proposedOperation: "append", appendOnly: true, sourceMetadata: {}, namespaceIsolation: { namespace: "real_life", classification: "real_life", auOnly: false, realLifeOnly: true, explicitlyFictionalized: false, mixedContent: false, realLifeCannotConsumeAuEvidence: true, auContentCannotBecomeRealLifeEvidence: true }, blockers: [], warnings: [], updatedAt: "pf", audit: { fingerprint: "pf", decisionTrail: [{ action: "approve_append" }] } } as never;
const decision = { id: "d1", itemId: "r1", userId: "u1", namespace: "real_life", action: "approve_append", createdAt: "t", audit: {} } as never;
const preview = { ok: true, previewOnly: true, approvedReviewItemIsNotMemory: true, futureGatedPersistenceRequired: true, wouldPersist: false, wouldCallModel: false, wouldEmbed: false, productionWriteDisabled: true, requiresFutureInternalGate: true, plans: [{ itemId: "r1", eligible: true, blockers: [], warnings: [], wouldPersist: false, wouldCallModel: false, wouldEmbed: false }], blockers: [], warnings: [], summary: { plannedSources: 1, plannedItems: 1, plannedPatches: 1, plannedAuditLogs: 1 } } as never;
const base = { context: { userId: "u1", namespace: "real_life" as const }, sessionResult, runtime, readinessResult: { ok: true }, liveDryRunResult: { ok: true }, namespace: "real_life" as const, allowedNamespaces: ["real_life" as const], reviewItemId: "r1", decisionId: "d1", idempotencyKey: "idem", typedConfirmation: "APPEND MEMORY", internalExecutionGate: true, internalHeaderMode: "approved-review-executor", adminCapability: true, reviewItem: item, decision, preview };
function deps(over: Record<string, unknown> = {}) { const calls: string[] = []; const reviewRepository = { readReviewQueueItemById: vi.fn(async () => ({ ok: true, data: item })), readReviewDecisionById: vi.fn(async () => ({ ok: true, data: decision })) }; const previewService = vi.fn(() => { calls.push("preview"); return preview; }); const approvedReviewPersistenceExecutor = vi.fn(async () => { calls.push("executor"); return { executed: true, productionRouteEnabled: false, publicRouteEnabled: false, appendOnly: true, namespace: "real_life", userId: "u1", counts: { sources: 1, items: 1, patches: 1, auditLogs: 1, markedReviewItems: 1, blocked: 0, failed: 0 }, blockers: [], warnings: [], fingerprint: "pf", idempotencyKey: "idem", source: { kind: "memory_source_append", id: "s1", appendOnly: true }, item: { kind: "memory_item_append", id: "m1", appendOnly: true }, patch: { kind: "memory_patch_append", id: "p1", appendOnly: true }, auditLog: { kind: "audit_log_append", id: "a1", appendOnly: true } }; }); const persistedMemoryReadRepository = { getMemoryItemDetail: vi.fn(async () => ({ ok: true, item: { id: "m1", namespace: "real_life", reviewItemId: "r1", decisionId: "d1", auditSummary: "r1 d1 idem pf" } })), listMemorySources: vi.fn(async () => ({ ok: true, items: [{ id: "s1", namespace: "real_life", itemId: "m1", reviewItemId: "r1", decisionId: "d1", excerptPreview: "r1 d1 idem pf" }] })), listMemoryPatches: vi.fn(async () => ({ ok: true, items: [{ id: "p1", namespace: "real_life", itemId: "m1", reason: "r1 d1 idem pf" }] })), listMemoryAuditEvents: vi.fn(async () => ({ ok: true, items: [{ id: "a1", namespace: "real_life", summary: "r1 d1 idem pf" }] })) }; return { ...base, reviewRepository, previewService, approvedReviewPersistenceExecutor, persistedMemoryReadRepository, browserLoader: vi.fn(async () => ({ items: [{ id: "m1" }] })), calls, ...over } as never; }
describe("manual operator memory workflow", () => {
  it("preflight rejects required blockers", () => { expect(validateOperatorManualMemoryWorkflowPreflight({ ...base, context: undefined, sessionResult: undefined } as never).blockers.map((b) => b.code)).toContain("auth_required"); for (const [key, code, value] of [["namespace", "namespace_required", undefined], ["user_id", "client_user_id_rejected", "evil"], ["reviewItem", "review_item_not_approved", { ...item, status: "pending_review" }], ["decision", "missing_append_decision", undefined], ["decision", "non_append_decision", { ...decision, action: "reject" }], ["idempotencyKey", "missing_idempotency_key", undefined], ["typedConfirmation", "typed_confirmation_mismatch", "NO"], ["readinessResult", "readiness_not_passed", { ok: false }], ["liveDryRunResult", "live_dry_run_not_passed", { ok: false }]] as const) expect(validateOperatorManualMemoryWorkflowPreflight({ ...base, [key]: value } as never).blockers.map((b) => b.code)).toContain(code); });
  it("preflight blocks public persistence, production ingest, and model/embedding/retrieval/GPT/MCP gates", () => { const bad = { ...runtime, config: { ...runtime.config, publicMemoryPersistenceEnabled: true, ingestProductionWriteEnabled: true, modelCallsEnabled: true, embeddingsEnabled: true, semanticRetrievalEnabled: true, gptActionsEnabled: true, mcpEnabled: true } }; const codes = validateOperatorManualMemoryWorkflowPreflight({ ...base, runtime: bad }).blockers.map((b) => b.code); expect(codes).toEqual(expect.arrayContaining(["public_persistence_enabled", "production_ingest_write_enabled", "model_calls_enabled", "embeddings_enabled", "semantic_retrieval_enabled", "gpt_actions_enabled", "mcp_enabled"])); });
  it("runner previews before injected executor and verifies readback, browser visibility, and audit", async () => { const d = deps(); const r = await runOperatorManualMemoryWorkflow(d); expect(r.ok).toBe(true); expect(d.calls).toEqual(["preview", "executor"]); expect(d.approvedReviewPersistenceExecutor).toHaveBeenCalledTimes(1); expect(d.persistedMemoryReadRepository.getMemoryItemDetail).toHaveBeenCalled(); expect(d.browserLoader).toHaveBeenCalled(); expect(r.receipt?.auditVerificationStatus).toBe("verified"); });
  it("runner never calls forbidden ingest/model/retrieval/vector collaborators", async () => { const forbidden = { ingest: vi.fn(), model: vi.fn(), retrieval: vi.fn(), vector: vi.fn() }; await runOperatorManualMemoryWorkflow(deps({ forbidden })); expect(Object.values(forbidden).every((f) => f.mock.calls.length === 0)).toBe(true); });
  it("receipt DTO redacts sensitive text, evidence, secrets, service-role, and raw errors", () => { const dto = toOperatorManualMemoryWorkflowSafeDto({ ok: false, executed: false, safety: base.preview ? { internalOnly: true, publicPersistenceEnabled: false, productionIngestEnabled: false, publicReadEnabled: false, wouldCallModel: false, wouldEmbed: false, semanticRetrievalEnabled: false, appendOnly: true, requiresTypedConfirmation: true, requiresAuditVerification: true } : never, steps: [{ name: "review_item_loaded", status: "blocked", message: "service-role secret memory text evidence key=abc" }], blockers: [{ code: "x", message: "service-role secret evidence" }], warnings: [] } as never); expect(JSON.stringify(dto)).not.toMatch(/service-role|secret memory text|evidence key=abc/i); expect(dto.redactions.serviceRoleExposed).toBe(false); });
  it("route GET is safe, POST disabled by default, rejects user_id, and requires internal header/gates", async () => { expect((await GET(new NextRequest("https://x"))).status).toBe(200); expect((await POST(new NextRequest("https://x", { method: "POST", body: "{}" }))).status).toBe(501); expect((await createOperatorManualMemoryWorkflowRouteHandler({ enabled: true }).POST(new NextRequest("https://x", { method: "POST", body: JSON.stringify({ user_id: "u" }) }))).status).toBe(400); const res = await createOperatorManualMemoryWorkflowRouteHandler({ enabled: true, resolveSession: async () => sessionResult, env: () => ({}) as never }).POST(new NextRequest("https://x", { method: "POST", body: JSON.stringify({ namespace: "real_life", reviewItemId: "r1", decisionId: "d1", idempotencyKey: "i", typedConfirmation: "APPEND MEMORY" }) })); expect(res.status).toBe(403); });
  it("UI renders disabled execute state and confirmation copy", () => { const html = renderToStaticMarkup(<Page />); expect(html).toContain("Manual memory workflow"); expect(html).toContain("Internal operator workflow"); expect(html).toContain("Execution requires typed confirmation: APPEND MEMORY"); expect(html).toContain("Execute disabled"); });
  it("public route and import safety remains intact", () => { const files = ["app/api/admin/memory/manual-workflow/route.ts", "lib/api/operator-manual-memory-workflow-route-handler.ts", "lib/services/operator-manual-memory-workflow-runner.ts", "app/admin/memory/manual-workflow/page.tsx"]; const text = files.map((f) => readFileSync(join(root, f), "utf8")).join("\n"); expect(text).not.toMatch(/service-role|SUPABASE_SERVICE_ROLE|from [^;]*(openai|anthropic|retrieval-service|pgvector|embedding|mcp)/i); expect(readFileSync(join(root, "lib/api/memory-ingest-route-handler.ts"), "utf8")).toMatch(/Memory ingest is intentionally disabled/); expect(readFileSync(join(root, "app/api/memory/review/[id]/persist/route.ts"), "utf8")).toMatch(/disabled/); expect(readFileSync(join(root, "lib/services/persisted-memory-browser-loader.ts"), "utf8")).not.toMatch(/executeApproved|appendReviewDecision|deleteMemory|updateMemory/); expect(readFileSync(join(root, "app/api/admin/memory/qa-flow/route.ts"), "utf8")).toMatch(/enabled: false/); });
});
