/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, expect, it } from "vitest";
import { approveOperatorAction, cancelOperatorAction, dryRunOperatorAction, executeApprovedOperatorAction, listOperatorActionEvents, listOperatorActions, proposeOperatorAction } from "@/lib/services/pandora-operator-action-service";

const USER = "11111111-1111-4111-8111-111111111111";
const OTHER = "22222222-2222-4222-8222-222222222222";
type Store = Record<string, any[]>;
function client(store: Store) { return { from(table: string) { const eqs: Record<string, any> = {}; let lim = Infinity; let patch: any; let insertRow: any; const rows=()=> (store[table]??[]).filter(r=>Object.entries(eqs).every(([k,v])=>r[k]===v)).slice(0,lim); const b:any={ select(){return b}, eq(k:string,v:any){eqs[k]=v;return b}, order(){return b}, limit(n:number){lim=n;return b}, single(){return b}, insert(row:any){insertRow=Array.isArray(row)?row[0]:row; store[table]=store[table]??[]; store[table].push(insertRow); return b}, update(row:any){patch=row; return b}, then(res:any,rej:any){ if(patch){ const r=rows()[0]; if(r) Object.assign(r,patch); return Promise.resolve({data:r??null,error:r?null:{message:"missing"}}).then(res,rej)} return Promise.resolve({data:insertRow??rows(),error:null}).then(res,rej)}}; return b; }} as any; }
function store(): Store { return { pandora_operator_actions: [], pandora_operator_action_events: [], memory_context_packs: [{ id:"rl", user_id: USER, namespace:"real_life", pack_type:"master", status:"active", title:"RL", created_at:"2026-07-03" }, { id:"au", user_id: USER, namespace:"au", pack_type:"master", status:"active", title:"AU", created_at:"2026-07-03" }], audit_logs: [], retrieval_logs: [], memory_events: [], memory_profiles: [], memory_open_loops: [], memory_capture_candidates: [], memory_review_queue_items: [], memory_pruning_candidates: [] }; }

describe("pandora operator action service", () => {
  it("proposes allowed action and returns existing duplicate by idempotency", async () => { const s=store(); const c=client(s); const a=await proposeOperatorAction(c,{userId:USER, actionType:"verify_namespace_invariants", namespace:"real_life", mode:"dry_run", payload:{a:1}}); const b=await proposeOperatorAction(c,{userId:USER, actionType:"verify_namespace_invariants", namespace:"real_life", mode:"dry_run", payload:{a:1}}); expect(a.id).toBe(b.id); expect(s.pandora_operator_actions).toHaveLength(1); });
  it("rejects unknown action_type and live mode", async () => { await expect(proposeOperatorAction(client(store()),{userId:USER, actionType:"delete_memory", mode:"dry_run"})).rejects.toThrow(/Unsupported/); await expect(proposeOperatorAction(client(store()),{userId:USER, actionType:"verify_namespace_invariants", mode:"live"})).rejects.toThrow(/Unsupported/); });
  it("never lists another user's action", async () => { const s=store(); s.pandora_operator_actions.push({id:"other", user_id:OTHER}); expect(await listOperatorActions(client(s),{userId:USER})).toEqual([]); });
  it("dry-run verify_namespace_invariants uses read-only verification and includes no_mutation_performed", async () => { const s=store(); const c=client(s); const a=await proposeOperatorAction(c,{userId:USER, actionType:"verify_namespace_invariants", namespace:"real_life"}); const d=await dryRunOperatorAction(c,{userId:USER, actionId:a.id}); expect(JSON.stringify(d.result)).toContain("namespace_invariants"); expect(JSON.stringify(d.result)).toContain("no_mutation_performed"); expect(s.memory_context_packs).toHaveLength(2); });
  it("prepare_distill_smoke_plan returns a plan only", async () => { const s=store(); const c=client(s); const a=await proposeOperatorAction(c,{userId:USER, actionType:"prepare_distill_smoke_plan", namespace:"au"}); const d=await dryRunOperatorAction(c,{userId:USER, actionId:a.id}); expect(d.result.no_mutation_performed).toBe(true); expect(JSON.stringify(d.result)).toContain("plan_only"); });
  it("cancel only own action", async () => { const s=store(); const c=client(s); const a=await proposeOperatorAction(c,{userId:USER, actionType:"check_retrieval_eval_status"}); await expect(cancelOperatorAction(c,{userId:OTHER, actionId:a.id})).rejects.toThrow(/not found/); const cancelled=await cancelOperatorAction(c,{userId:USER, actionId:a.id}); expect(cancelled.status).toBe("cancelled"); });
  it("approves proposed and dry_ran actions, then executes approved read-only action", async () => { const s=store(); const c=client(s); const a=await proposeOperatorAction(c,{userId:USER, actionType:"verify_pack_supersession", namespace:"real_life"}); const approved=await approveOperatorAction(c,{userId:USER, actionId:a.id}); expect(approved.status).toBe("approved"); const completed=await executeApprovedOperatorAction(c,{userId:USER, actionId:a.id}); expect(completed.status).toBe("completed"); expect(completed.result.no_mutation_performed).toBe(true); expect(JSON.stringify(completed.result)).toContain("pack_supersession"); expect(s.memory_context_packs).toHaveLength(2); });
  it("blocks invalid transitions and cross-user events", async () => { const s=store(); const c=client(s); const a=await proposeOperatorAction(c,{userId:USER, actionType:"refresh_dashboard_snapshot"}); await expect(executeApprovedOperatorAction(c,{userId:USER, actionId:a.id})).rejects.toThrow(/Invalid/); await expect(approveOperatorAction(c,{userId:OTHER, actionId:a.id})).rejects.toThrow(/not found/); await expect(listOperatorActionEvents(c,{userId:OTHER, actionId:a.id})).rejects.toThrow(/not found/); const cancelled=await cancelOperatorAction(c,{userId:USER, actionId:a.id}); await expect(cancelOperatorAction(c,{userId:USER, actionId:cancelled.id})).rejects.toThrow(/terminal/); });
  it("check_retrieval_eval_status reports unavailable evidence without fabricated accuracy", async () => { const s=store(); const c=client(s); const a=await proposeOperatorAction(c,{userId:USER, actionType:"check_retrieval_eval_status"}); await approveOperatorAction(c,{userId:USER, actionId:a.id}); const completed=await executeApprovedOperatorAction(c,{userId:USER, actionId:a.id}); expect(JSON.stringify(completed.result)).toContain("retrieval_eval_status"); expect(JSON.stringify(completed.result)).not.toContain("94.3"); });
});
