/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, expect, it } from "vitest";
import { createShadowContextPackCandidate, dryRunShadowContextPackCandidate, listShadowContextPacks, updateShadowContextPackStatus } from "@/lib/services/pandora-shadow-context-pack-service";
const USER="11111111-1111-4111-8111-111111111111", OTHER="22222222-2222-4222-8222-222222222222";
type Store=Record<string, any[]>;
function client(store:Store){ return { from(table:string){ const eqs:Record<string,any>={}; let lim=Infinity; let patch:any; let inserted:any; const rows=()=> (store[table]??[]).filter(r=>Object.entries(eqs).every(([k,v])=>r[k]===v)).slice(0,lim); const b:any={ select(){return b}, eq(k:string,v:any){eqs[k]=v;return b}, order(){return b}, limit(n:number){lim=n;return b}, single(){return b}, insert(row:any){inserted=Array.isArray(row)?row[0]:row; store[table]=store[table]??[]; store[table].push(inserted); return b}, update(row:any){patch=row; return b}, then(res:any,rej:any){ if(patch){ const r=rows()[0]; if(r) Object.assign(r,patch); return Promise.resolve({data:r??null,error:r?null:{message:"missing"}}).then(res,rej)} return Promise.resolve({data:inserted??rows(),error:null}).then(res,rej)}}; return b; }} as any; }
function store():Store{return { memory_events:[{id:"e1",user_id:USER,namespace:"real_life",status:"reviewed",extracted_summary:"Real project update",created_at:"2026-07-03"},{id:"e2",user_id:USER,namespace:"au",status:"promoted",extracted_summary:"AU story beat",created_at:"2026-07-02"},{id:"e3",user_id:OTHER,namespace:"real_life",status:"reviewed",extracted_summary:"Other user",created_at:"2026-07-03"}], memory_context_packs:[{id:"m1",user_id:USER,namespace:"real_life",pack_type:"master",status:"active",created_at:"2026-07-01"},{id:"m2",user_id:USER,namespace:"au",pack_type:"master",status:"active",created_at:"2026-07-01"}], memory_open_loops:[{id:"l1",user_id:USER,namespace:"real_life",status:"open",created_at:"2026-07-03"}], memory_review_queue_items:[{id:"r1",user_id:USER,namespace:"real_life",status:"pending_review",created_at:"2026-07-03"}], pandora_shadow_context_packs:[], pandora_shadow_context_pack_events:[]};}
describe("shadow context pack service",()=>{
 it("dry-runs deterministically for real_life and never includes au rows", async()=>{const s=store(); const r=await dryRunShadowContextPackCandidate(client(s),{userId:USER,namespace:"real_life"}); expect(r.summary).toBe("Shadow candidate for real_life: 1 events considered, 1 open loops, 1 review items. Promotion is gated."); expect(JSON.stringify(r)).toContain("Real project update"); expect(JSON.stringify(r)).not.toContain("AU story beat");});
 it("dry-runs deterministically for au", async()=>{const r=await dryRunShadowContextPackCandidate(client(store()),{userId:USER,namespace:"au"}); expect(r.summary).toContain("Shadow candidate for au: 1 events considered"); expect(r.status).toBe("ready_for_review");});
 it("another user's rows never appear", async()=>{const r=await dryRunShadowContextPackCandidate(client(store()),{userId:OTHER,namespace:"real_life"}); expect(JSON.stringify(r)).toContain("Other user"); expect(JSON.stringify(r)).not.toContain("Real project update");});
 it("creates only shadow row and matching event", async()=>{const s=store(); const pack=await createShadowContextPackCandidate(client(s),{userId:USER,namespace:"real_life",requestId:"req"}); expect(pack.id).toBeTruthy(); expect(s.pandora_shadow_context_packs).toHaveLength(1); expect(s.pandora_shadow_context_pack_events).toHaveLength(1); expect(s.memory_events).toHaveLength(3); expect(s.memory_context_packs).toHaveLength(2);});
 it("missing evidence warns and stays draft", async()=>{const s=store(); s.memory_events=[]; s.memory_context_packs=[]; const r=await dryRunShadowContextPackCandidate(client(s),{userId:USER,namespace:"real_life"}); expect(r.status).toBe("draft"); expect(r.warnings.join(" ")).toContain("No active master"); expect(r.warnings.join(" ")).toContain("No memory_events");});
 it("updates status only for own pack and supports terminal review states", async()=>{const s=store(); const c=client(s); const p=await createShadowContextPackCandidate(c,{userId:USER,namespace:"real_life",requestId:"req"}); expect((await updateShadowContextPackStatus(c,{userId:USER,shadowPackId:p.id,status:"reviewed"})).status).toBe("reviewed"); expect((await updateShadowContextPackStatus(c,{userId:USER,shadowPackId:p.id,status:"rejected"})).status).toBe("rejected"); expect((await updateShadowContextPackStatus(c,{userId:USER,shadowPackId:p.id,status:"archived"})).status).toBe("archived"); await expect(updateShadowContextPackStatus(c,{userId:OTHER,shadowPackId:p.id,status:"reviewed"})).rejects.toThrow(/not found/);});
 it("list filters own namespace/status", async()=>{const s=store(); const c=client(s); await createShadowContextPackCandidate(c,{userId:USER,namespace:"real_life",requestId:"req"}); await createShadowContextPackCandidate(c,{userId:USER,namespace:"au",requestId:"req2"}); expect(await listShadowContextPacks(c,{userId:USER,namespace:"real_life"})).toHaveLength(1);});
});
