import { describe, expect, it } from "vitest";
import { NextRequest } from "next/server";
import { InMemoryPersistedMemoryReadRepository } from "@/lib/db/in-memory-persisted-memory-read-repository";
import { toPersistedMemoryItemDto, toPersistedMemorySourceDto } from "@/lib/api/persisted-memory-read-dto";
import { createPersistedMemoryReadRouteHandler } from "@/lib/api/persisted-memory-read-route-handler";

const ctx = { userId: "u1", namespace: "real_life" as const };
function repo() { const r = new InMemoryPersistedMemoryReadRepository(); r.seed({ items: [
  { id: "i1", user_id: "u1", namespace: "real_life", memory_type: "real_life_fact", title: "Coffee", body: "Likes black coffee", metadata: { review_item_id: "r1", decision_id: "d1", category: "preference" }, created_at: "2026-01-01" },
  { id: "i2", user_id: "u2", namespace: "real_life", title: "Other", body: "secret", metadata: {}, created_at: "2026-01-02" },
  { id: "i3", user_id: "u1", namespace: "au", title: "AU", body: "story", metadata: {}, created_at: "2026-01-03" },
], sources: [{ id: "s1", user_id: "u1", namespace: "real_life", memory_item_id: "i1", source_type: "document", excerpt: "raw evidence excerpt", metadata: {}, created_at: "2026-01-01" }], patches: [{ id: "p1", user_id: "u1", namespace: "real_life", memory_item_id: "i1", patch_type: "create", before_snapshot: { blob: "secret" }, after_snapshot: { body: "Likes black coffee" }, metadata: {}, created_at: "2026-01-01" }], auditEvents: [{ id: "a1", user_id: "u1", namespace: "real_life", action: "persist", table_name: "memory_items", record_id: "i1", metadata: {}, created_at: "2026-01-01" }] }); return r; }

describe("persisted memory read repository", () => {
  it("rejects missing userId, missing namespace, client user_id/userId override, and namespace mismatch", async () => { const r = repo(); await expect(r.listMemoryItems({ ...ctx, userId: "" }, { namespace: "real_life" })).resolves.toMatchObject({ ok: false, blocker: { code: "auth_required" } }); await expect(r.listMemoryItems(ctx, { namespace: undefined as never })).resolves.toMatchObject({ ok: false, blocker: { code: "namespace_required" } }); await expect(r.listMemoryItems(ctx, { namespace: "real_life", user_id: "evil" } as never)).resolves.toMatchObject({ ok: false, blocker: { code: "client_user_id_rejected" } }); await expect(r.listMemoryItems(ctx, { namespace: "au" })).resolves.toMatchObject({ ok: false, blocker: { code: "namespace_mismatch" } }); });
  it("filters by userId and namespace and supports pagination and keyword without embeddings", async () => { const r = repo(); const out = await r.listMemoryItems(ctx, { namespace: "real_life", page: 1, pageSize: 1, filter: { keyword: "coffee" } }); expect(out.ok && out.items).toHaveLength(1); expect(out.ok && out.items[0].id).toBe("i1"); expect(out.ok && out.total).toBe(1); });
  it("reads item detail, source list/detail, patch list, and audit list", async () => { const r = repo(); await expect(r.getMemoryItemDetail(ctx, { namespace: "real_life", id: "i1" })).resolves.toMatchObject({ ok: true, item: { id: "i1" } }); await expect(r.listMemorySources(ctx, { namespace: "real_life" })).resolves.toMatchObject({ ok: true, items: [{ id: "s1" }] }); await expect(r.getMemorySourceDetail(ctx, { namespace: "real_life", id: "s1" })).resolves.toMatchObject({ ok: true, item: { id: "s1" } }); await expect(r.listMemoryPatches(ctx, { namespace: "real_life", filter: { itemId: "i1" } })).resolves.toMatchObject({ ok: true, items: [{ id: "p1" }] }); await expect(r.listMemoryAuditEvents(ctx, { namespace: "real_life" })).resolves.toMatchObject({ ok: true, items: [{ id: "a1" }] }); });
});

describe("persisted memory read DTOs", () => {
  it("redacts long memory text, raw sensitive evidence, and includes safety booleans", () => { const dto = toPersistedMemoryItemDto({ id: "i", namespace: "real_life", body: "x".repeat(300), metadata: {} }); expect(dto.textPreview?.length).toBeLessThan(300); expect(dto.fullText).toBeUndefined(); expect(dto).toMatchObject({ readOnly: true, wouldWrite: false, requiresAuth: true, sensitiveEvidenceRedacted: true }); const src = toPersistedMemorySourceDto({ id: "s", namespace: "real_life", source_ref: "y".repeat(200), excerpt: "z".repeat(400), metadata: {} }); expect(src.excerptPreview?.length).toBeLessThan(400); expect(JSON.stringify(src)).not.toContain("raw_sensitive_evidence"); });
});

describe("persisted memory read route factory", () => {
  it("rejects unauthenticated, missing namespace, client user_id/userId, and supports GET only", async () => { const handler = createPersistedMemoryReadRouteHandler({ repository: repo(), resolveAuth: async () => null, resolveEnv: () => ({ enabled: true }) }, "listItems"); expect((await handler(new NextRequest("http://x.test/api/memory/items?namespace=real_life"))).status).toBe(403); expect((await handler(new NextRequest("http://x.test/api/memory/items"))).status).toBe(400); expect((await handler(new NextRequest("http://x.test/api/memory/items?namespace=real_life&user_id=u2"))).status).toBe(400); const ok = createPersistedMemoryReadRouteHandler({ repository: repo(), resolveAuth: async () => ({ userId: "u1" }), resolveEnv: () => ({ enabled: true }) }, "listItems"); expect((await ok(new NextRequest("http://x.test/api/memory/items?namespace=real_life"))).status).toBe(200); });
  it("public route stubs are disabled by default", async () => { const { GET } = await import("@/app/api/memory/items/route"); expect((await GET(new NextRequest("http://x.test/api/memory/items?namespace=real_life"))).status).toBe(501); });
});
