import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { withBridge } from "@/app/api/memory/adaptive/route-helper";
import { inferMemoryNamespace } from "@/lib/services/memory-autopilot-policy-service";
import { disabledPostAnswer, disabledPreAnswer, runPostAnswerTurn, runPreAnswerTurn } from "@/lib/services/memory-adaptive-turn-service";
import { resolvePandoraRuntimeSafetyConfig } from "@/lib/config/pandora-runtime-safety-config";

const schema=z.object({namespace:z.enum(["real_life","au"]).optional(),user_message:z.string().min(1).max(20000),assistant_draft:z.string().max(30000).optional(),current_task:z.string().max(1000).optional(),conversation_type:z.string().max(120).optional(),mode:z.enum(["pre_answer","post_answer"])});
export async function POST(request:NextRequest){ const parsed=schema.safeParse(await request.json().catch(()=>({}))); if(!parsed.success)return NextResponse.json({ok:false,blockers:["invalid_request"],issues:parsed.error.flatten()},{status:400}); const body=parsed.data; const namespace=inferMemoryNamespace({userMessage:body.user_message,namespace:body.namespace,currentTask:body.current_task}); const input={...body,namespace}; const env=process.env; const runtime=resolvePandoraRuntimeSafetyConfig(env).config;
  if(body.mode==="pre_answer"){ const preview=disabledPreAnswer(input,env); if(!preview.should_retrieve)return NextResponse.json(preview); if(!runtime.memoryContextApiEnabled)return NextResponse.json({...preview,ok:false,blockers:["memoryContextApiEnabled_disabled"],next_step:"Set PANDORA_ENABLE_MEMORY_CONTEXT_API=true in a reviewed environment."},{status:403}); const bridge=await withBridge(request,"memoryContextApiEnabled"); if("error" in bridge)return bridge.error; return NextResponse.json(await runPreAnswerTurn(bridge.client,bridge.principal.userId,input,env)); }
  const preview=disabledPostAnswer(input,env); if(!preview.should_create_candidate)return NextResponse.json(preview); if(!runtime.memoryCaptureApiEnabled)return NextResponse.json({...preview,ok:false,blockers:["memoryCaptureApiEnabled_disabled"],next_step:"Set PANDORA_ENABLE_MEMORY_CAPTURE_API=true in a reviewed environment."},{status:403}); const bridge=await withBridge(request,"memoryCaptureApiEnabled"); if("error" in bridge)return bridge.error; return NextResponse.json(await runPostAnswerTurn(bridge.client,bridge.principal.userId,input,env)); }
